# Practice run for PreRun code

In [1]:
from PreRun_alt import PreRun
import pandas as pd
import numpy as np
import pyarrow.parquet as pq

In [2]:
systems_cleaned = pd.read_csv('../../../data/core/systems_cleaned.csv')

In [3]:
my_rough_data_pq = pq.ParquetDataset('./temp_fix/other/4/')
my_rough_data_df = my_rough_data_pq.read().to_pandas()

In [4]:
my_rough_data_df['date'] = my_rough_data_df['time'].dt.date

In [5]:
my_rough_data_df['forward_diff'] = -my_rough_data_df['time'].diff(periods=-1)

In [6]:
my_rough_data_df['in_day_time_diff'] = my_rough_data_df.groupby('date')['time'].diff().dt.total_seconds() / 3600

In [9]:
my_rough_data_df['in_day_time_diff'].value_counts().sort_index()

in_day_time_diff
1.0     48829
2.0        43
3.0        12
4.0         3
5.0         2
6.0         4
7.0         1
10.0        1
14.0        3
Name: count, dtype: int64

In [ ]:
maintainer_4 = PreRun(4, './temp_fix', None, systems_cleaned)

                     time    energy
0     2007-08-27 12:00:00  0.188190
1     2007-08-27 14:00:00  0.024962
2     2007-08-27 15:00:00  0.035136
3     2007-08-27 16:00:00  0.039177
4     2007-08-27 17:00:00  0.037669
...                   ...       ...
53489 2023-02-27 13:00:00  0.366943
53490 2023-02-27 14:00:00  0.297565
53491 2023-02-27 15:00:00  0.348322
53492 2023-02-27 16:00:00  0.188479
53493 2023-02-27 17:00:00  0.017879

[53494 rows x 2 columns]

In [ ]:
df_temp = maintainer_4.data.copy(deep=True)

In [ ]:
maintainer_4.data.loc[65:75]

                  time    energy
65 2007-08-31 16:00:00  0.057845
66 2007-08-31 17:00:00  0.002598
67 2007-09-01 06:00:00  0.032494
68 2007-09-01 07:00:00  0.159633
69 2007-09-01 08:00:00  0.304443
70 2007-09-01 09:00:00  0.265836
71 2007-09-01 10:00:00  0.804245
72 2007-09-01 11:00:00  0.259111
73 2007-09-01 12:00:00  0.161788
74 2007-09-01 13:00:00  0.704303
75 2007-09-01 14:00:00  0.536415

In [5]:
maintainer_4.add_energy_features_only(
    daily_lags=2,
    remove_daily_lags_nans=False,
    include_last_year=True,
    remove_last_year_nans=False,
    remove_todays_lags_nans=False,
)

AttributeError: module 'pandas' has no attribute 'daterange'

Sidebar for good_runs

In [4]:
good_days_temp = pd.read_csv('./temp_fix/good_days/4_good_days_other.csv')
len(good_days_temp)

4596

In [9]:
good_days_temp_set = set(good_days_temp['date'].unique())
good_days_retry_set = set(good_days_retry['date'].unique())
good_days_retry_set.difference(good_days_temp_set)

{'2010-01-22', '2023-02-28'}

In [13]:
good_days_temp['date'] = pd.to_datetime(good_days_temp['date']).dt.date
good_days_retry['date'] = pd.to_datetime(good_days_retry['date']).dt.date

In [7]:
good_days_retry = pd.read_csv('./try_again_4/good_days/4_good_days_other.csv')

In [8]:
set(good_days_temp['date'].unique()).difference(set(good_days_retry['date'].unique()))

{'2014-12-04',
 '2011-12-01',
 '2011-12-14',
 '2008-08-28',
 '2022-11-05',
 '2022-12-29',
 '2018-11-20',
 '2011-09-14',
 '2013-03-04',
 '2013-05-02',
 '2015-06-28',
 '2009-05-02',
 '2010-10-11',
 '2020-12-01',
 '2019-06-03',
 '2022-12-07',
 '2022-03-09',
 '2008-01-07',
 '2014-12-29',
 '2015-04-27',
 '2007-08-27',
 '2022-11-18',
 '2020-06-21',
 '2019-03-28',
 '2011-05-23',
 '2016-08-11',
 '2012-06-02',
 '2011-11-28',
 '2021-01-10',
 '2020-07-25',
 '2008-06-26',
 '2016-04-17',
 '2016-11-18',
 '2009-05-01',
 '2022-02-03',
 '2012-11-14',
 '2014-10-16',
 '2012-12-06',
 '2023-02-23',
 '2014-05-30',
 '2019-06-07',
 '2007-12-29',
 '2015-08-31',
 '2018-04-21',
 '2011-07-13',
 '2012-12-09',
 '2015-06-07',
 '2019-07-01',
 '2013-12-20',
 '2018-11-09',
 '2019-06-05',
 '2015-05-07',
 '2011-02-05',
 '2007-09-02',
 '2019-07-20',
 '2010-05-14',
 '2019-08-15',
 '2013-02-08',
 '2007-11-22',
 '2015-06-24',
 '2008-11-03',
 '2015-11-11',
 '2013-06-23',
 '2021-07-14',
 '2007-10-07',
 '2015-07-13',
 '2019-06-18',
 '2021-04-06',
 '2015-10-06',
 '2016-06-20',
 '2021-04-16',
 '2020-08-27',
 '2020-03-28',
 '2011-11-02',
 '2021-08-21',
 '2014-07-11',
 '2015-07-02',
 '2012-11-10',
 '2022-12-12',
 '2011-01-10',
 '2009-01-24',
 '2012-07-29',
 '2019-07-03',
 '2023-01-15',
 '2015-12-25',
 '2019-04-10',
 '2019-06-26',
 '2021-05-03',
 '2021-12-10',
 '2014-06-18',
 '2010-12-14',
 '2019-12-14',
 '2016-05-19',
 '2014-07-18',
 '2013-09-27',
 '2014-11-07',
 '2022-04-22',
 '2022-07-22',
 '2013-08-03',
 '2008-02-05',
 '2009-03-26',
 '2020-06-24',
 '2018-07-04',
 '2010-12-05',
 '2010-03-26',
 '2018-03-28',
 '2012-10-05',
 '2018-01-12',
 '2011-04-03',
 '2020-05-21',
 '2012-11-07',
 '2016-05-16',
 '2007-12-04',
 '2008-04-29',
 '2022-03-29',
 '2020-04-12',
 '2013-09-10',
 '2008-06-02',
 '2021-03-23',
 '2014-12-02',
 '2013-09-15',
 '2022-09-10',
 '2008-06-29',
 '2021-03-22',
 '2022-07-20',
 '2013-11-04',
 '2016-05-01',
 '2014-05-12',
 '2018-02-10',
 '2018-05-19',
 '2016-03-26',
 '2014-04-13',
 '2010-07-15',
 '2007-09-10',
 '2021-12-15',
 '2009-01-23',
 '2016-01-29',
 '2008-05-12',
 '2020-10-27',
 '2008-02-25',
 '2021-09-29',
 '2008-03-30',
 '2013-12-09',
 '2011-10-17',
 '2012-10-27',
 '2007-12-25',
 '2013-02-22',
 '2008-03-01',
 '2013-02-25',
 '2019-10-24',
 '2013-10-18',
 '2020-02-08',
 '2023-01-11',
 '2022-07-07',
 '2020-01-23',
 '2011-06-16',
 '2020-10-18',
 '2015-11-26',
 '2014-02-16',
 '2008-12-08',
 '2020-05-29',
 '2010-12-01',
 '2016-08-13',
 '2016-03-24',
 '2010-12-15',
 '2017-12-22',
 '2011-09-21',
 '2011-04-24',
 '2014-06-05',
 '2011-07-05',
 '2013-02-20',
 '2019-10-01',
 '2018-10-16',
 '2008-09-11',
 '2008-04-26',
 '2018-03-26',
 '2021-02-25',
 '2011-02-25',
 '2011-09-18',
 '2008-09-28',
 '2014-11-11',
 '2008-07-02',
 '2011-03-18',
 '2014-06-08',
 '2015-02-25',
 '2018-02-23',
 '2008-11-29',
 '2012-01-06',
 '2022-11-15',
 '2008-11-25',
 '2013-02-04',
 '2020-01-27',
 '2020-05-27',
 '2021-01-25',
 '2018-05-18',
 '2009-04-16',
 '2020-04-02',
 '2011-09-23',
 '2015-05-22',
 '2022-02-23',
 '2018-12-12',
 '2007-11-23',
 '2014-11-03',
 '2020-02-03',
 '2022-02-15',
 '2016-03-07',
 '2020-02-05',
 '2012-04-15',
 '2019-02-06',
 '2013-10-04',
 '2014-01-23',
 '2020-10-22',
 '2016-03-19',
 '2019-05-07',
 '2013-07-12',
 '2021-11-01',
 '2022-07-03',
 '2011-06-20',
 '2014-12-15',
 '2022-09-30',
 '2013-08-22',
 '2007-09-09',
 '2014-11-10',
 '2015-01-03',
 '2011-01-13',
 '2009-01-12',
 '2011-09-26',
 '2013-02-14',
 '2013-11-25',
 '2010-06-08',
 '2018-04-12',
 '2019-07-15',
 '2022-11-17',
 '2014-07-17',
 '2008-06-23',
 '2021-04-17',
 '2010-07-04',
 '2018-03-18',
 '2007-12-27',
 '2015-04-18',
 '2022-08-15',
 '2014-12-27',
 '2016-12-13',
 '2015-04-02',
 '2020-11-09',
 '2022-01-18',
 '2018-01-10',
 '2018-10-12',
 '2011-12-05',
 '2021-01-02',
 '2019-10-30',
 '2008-05-28',
 '2011-10-18',
 '2010-03-30',
 '2014-09-29',
 '2015-01-13',
 '2018-01-22',
 '2015-03-02',
 '2014-02-02',
 '2013-08-23',
 '2012-05-23',
 '2023-01-19',
 '2018-02-19',
 '2022-01-06',
 '2022-01-21',
 '2007-12-21',
 '2014-10-09',
 '2014-07-15',
 '2022-02-21',
 '2019-06-22',
 '2013-03-24',
 '2019-02-20',
 '2012-11-24',
 '2022-02-16',
 '2022-09-21',
 '2012-04-03',
 '2019-11-06',
 '2021-03-21',
 '2013-10-20',
 '2016-10-16',
 '2009-03-27',
 '2016-08-09',
 '2016-05-15',
 '2014-02-04',
 '2011-02-08',
 '2020-12-28',
 '2019-12-17',
 '2012-02-07',
 '2018-05-20',
 '2008-05-01',
 '2020-11-18',
 '2009-04-23',
 '2016-04-10',
 '2008-12-14',
 '2013-07-30',
 '2011-01-11',
 '2020-07-31',
 '2014-08-15',
 '2018-03-19',
 '2015-07-24',
 '2021-01-03',
 '2020-03-13',
 '2016-02-23',
 '2018-09-24',
 '2021-01-07',
 '2008-02-14',
 '2016-06-07',
 '2014-11-30',
 '2021-01-12',
 '2019-05-20',
 '2012-12-15',
 '2021-04-22',
 '2008-12-01',
 '2019-04-29',
 '2012-11-01',
 '2019-11-21',
 '2012-07-06',
 '2010-11-09',
 '2021-07-01',
 '2007-11-28',
 '2010-11-05',
 '2022-02-22',
 '2008-06-30',
 '2012-09-03',
 '2021-12-07',
 '2009-02-13',
 '2008-06-08',
 '2008-08-31',
 '2014-01-28',
 '2015-11-17',
 '2012-08-11',
 '2008-10-23',
 '2019-04-26',
 '2010-04-13',
 '2020-12-29',
 '2009-02-14',
 '2018-05-13',
 '2011-12-22',
 '2013-06-16',
 '2021-05-10',
 '2015-11-28',
 '2011-10-25',
 '2018-05-12',
 '2022-08-07',
 '2023-02-16',
 '2011-07-10',
 '2012-10-06',
 '2014-12-26',
 '2013-10-10',
 '2008-01-21',
 '2014-09-11',
 '2021-12-24',
 '2022-02-17',
 '2018-12-04',
 '2015-10-18',
 '2010-04-29',
 '2010-03-08',
 '2010-06-13',
 '2016-04-18',
 '2021-12-05',
 '2010-03-24',
 '2021-04-27',
 '2010-12-17',
 '2015-01-16',
 '2014-05-26',
 '2022-07-08',
 '2010-12-31',
 '2019-05-08',
 '2015-11-05',
 '2011-10-08',
 '2010-11-28',
 '2021-05-24',
 '2008-08-16',
 '2008-07-07',
 '2012-10-25',
 '2019-05-24',
 '2013-12-05',
 '2021-03-26',
 '2018-07-27',
 '2010-06-29',
 '2018-07-23',
 '2013-12-08',
 '2014-03-11',
 '2008-05-30',
 '2018-12-07',
 '2011-01-17',
 '2021-03-30',
 '2015-04-03',
 '2007-09-20',
 '2011-01-15',
 '2008-10-11',
 '2009-01-03',
 '2014-12-20',
 '2019-07-23',
 '2021-10-08',
 '2013-05-08',
 '2016-11-17',
 '2014-04-03',
 '2018-03-15',
 '2008-12-13',
 '2013-03-25',
 '2021-06-27',
 '2018-11-27',
 '2020-12-22',
 '2013-02-09',
 '2020-02-23',
 '2008-01-08',
 '2019-09-06',
 '2012-08-22',
 '2021-04-20',
 '2021-05-15',
 '2016-02-04',
 '2020-09-01',
 '2021-07-13',
 '2015-11-25',
 '2012-10-24',
 '2011-01-31',
 '2014-08-31',
 '2008-04-16',
 '2020-07-24',
 '2018-11-26',
 '2015-05-04',
 '2007-12-01',
 '2019-11-22',
 '2010-12-10',
 '2019-02-19',
 '2020-02-13',
 '2015-05-20',
 '2015-10-22',
 '2010-03-14',
 '2010-01-28',
 '2020-12-04',
 '2013-10-14',
 '2011-03-08',
 '2008-04-28',
 '2020-06-03',
 '2020-06-06',
 '2016-09-02',
 '2010-11-03',
 '2021-11-07',
 '2010-02-25',
 '2008-04-01',
 '2018-06-16',
 '2018-07-15',
 '2019-08-25',
 '2020-12-12',
 '2023-02-24',
 '2007-10-14',
 '2018-06-19',
 '2008-01-15',
 '2015-06-10',
 '2016-05-08',
 '2009-05-10',
 '2021-03-12',
 '2019-03-04',
 '2021-07-31',
 '2014-12-22',
 '2022-02-01',
 '2021-05-17',
 '2022-07-28',
 '2015-09-03',
 '2022-12-28',
 '2010-12-24',
 '2008-05-27',
 '2014-11-19',
 '2015-05-08',
 '2008-03-05',
 '2011-11-07',
 '2022-01-25',
 '2010-05-04',
 '2015-05-09',
 '2022-10-07',
 '2013-10-29',
 '2010-04-30',
 '2010-02-28',
 '2008-02-17',
 '2009-01-02',
 '2007-09-17',
 '2015-11-27',
 '2020-03-27',
 '2014-04-23',
 '2012-07-27',
 '2011-06-08',
 '2012-07-10',
 '2013-01-28',
 '2009-01-25',
 '2011-09-25',
 '2008-05-31',
 '2013-12-01',
 '2014-11-15',
 '2010-07-07',
 '2009-04-12',
 '2014-02-10',
 '2022-10-16',
 '2014-04-27',
 '2010-11-11',
 '2019-06-08',
 '2014-10-01',
 '2021-03-24',
 '2019-05-14',
 '2019-07-06',
 '2011-11-05',
 '2007-12-28',
 '2020-02-19',
 '2019-02-14',
 '2008-05-29',
 '2019-07-08',
 '2008-09-05',
 '2008-11-05',
 '2010-12-06',
 '2018-11-16',
 '2014-07-12',
 '2014-12-23',
 '2020-04-17',
 '2016-01-08',
 '2013-04-18',
 '2008-04-10',
 '2021-12-12',
 '2008-04-17',
 '2011-05-18',
 '2019-05-31',
 '2009-04-22',
 '2013-05-15',
 '2015-11-30',
 '2014-08-26',
 '2020-03-21',
 '2018-11-13',
 '2019-04-21',
 '2015-07-06',
 '2011-03-07',
 '2018-07-05',
 '2019-02-07',
 '2013-02-19',
 '2021-04-21',
 '2016-04-30',
 '2016-11-27',
 '2018-02-22',
 '2015-05-25',
 '2019-08-21',
 '2007-08-29',
 '2008-03-29',
 '2015-02-17',
 '2018-10-01',
 '2013-01-29',
 '2012-02-23',
 '2018-12-08',
 '2020-07-13',
 '2018-01-08',
 '2008-06-05',
 '2020-07-22',
 '2019-03-29',
 '2011-11-13',
 '2015-02-21',
 '2018-03-29',
 '2007-11-20',
 '2018-11-15',
 '2014-01-15',
 '2018-10-04',
 '2008-02-26',
 '2011-11-12',
 '2018-11-28',
 '2008-01-18',
 '2018-10-10',
 '2009-01-27',
 '2010-07-14',
 '2015-11-20',
 '2011-07-07',
 '2018-10-08',
 '2023-01-29',
 '2018-04-16',
 '2011-02-01',
 '2014-09-22',
 '2014-07-03',
 '2022-11-04',
 '2018-05-28',
 '2022-09-22',
 '2014-07-30',
 '2008-02-04',
 '2008-06-25',
 '2014-05-08',
 '2007-11-17',
 '2008-08-21',
 '2015-10-21',
 '2012-05-11',
 '2014-03-01',
 '2020-12-15',
 '2015-04-20',
 '2007-10-13',
 '2019-07-30',
 '2013-04-23',
 '2015-01-22',
 '2013-07-13',
 '2014-08-19',
 '2014-02-05',
 '2014-07-25',
 '2012-01-22',
 '2012-12-05',
 '2020-08-01',
 '2012-01-03',
 '2010-06-11',
 '2010-07-06',
 '2011-08-03',
 '2016-11-22',
 '2019-01-29',
 '2019-10-28',
 '2014-08-20',
 '2018-12-06',
 '2007-08-30',
 '2019-05-21',
 '2013-03-12',
 '2008-07-01',
 '2019-12-13',
 '2013-09-09',
 '2008-08-06',
 '2013-12-06',
 '2011-09-17',
 '2019-11-20',
 '2008-01-11',
 '2019-04-11',
 '2018-01-20',
 '2011-05-14',
 '2018-01-15',
 '2020-04-14',
 '2019-12-15',
 '2007-09-16',
 '2015-10-05',
 '2018-11-07',
 '2016-08-19',
 '2014-05-11',
 '2008-06-04',
 '2008-04-30',
 '2015-04-16',
 '2021-05-30',
 '2011-04-06',
 '2018-11-19',
 '2010-11-15',
 '2014-07-29',
 '2019-04-30',
 '2015-03-25',
 '2009-05-16',
 '2018-05-02',
 '2013-03-10',
 '2018-12-05',
 '2008-03-17',
 '2012-12-12',
 '2023-02-22',
 '2018-06-17',
 '2007-12-26',
 '2011-09-22',
 '2022-03-07',
 '2008-12-03',
 '2021-06-11',
 '2008-12-09',
 '2011-08-28',
 '2019-03-24',
 '2012-04-14',
 '2012-06-20',
 '2010-05-10',
 '2008-08-15',
 '2007-09-06',
 '2008-11-14',
 '2020-02-11',
 '2019-02-02',
 '2022-07-06',
 '2019-10-31',
 '2018-02-09',
 '2012-06-24',
 '2008-05-02',
 '2015-08-17',
 '2020-12-10',
 '2010-03-15',
 '2011-07-12',
 '2016-12-08',
 '2013-12-03',
 '2015-06-16',
 '2012-05-16',
 '2013-09-12',
 '2008-10-20',
 '2022-11-03',
 '2011-07-08',
 '2014-07-07',
 '2012-06-15',
 '2019-08-05',
 '2019-07-05',
 '2020-03-02',
 '2008-06-24',
 '2020-05-23',
 '2014-07-16',
 '2016-07-09',
 '2013-04-02',
 '2015-06-05',
 '2011-02-06',
 '2008-06-27',
 '2011-09-24',
 '2009-04-01',
 '2019-10-23',
 '2007-09-24',
 '2015-05-10',
 '2022-12-21',
 '2012-07-16',
 '2020-01-28',
 '2020-07-23',
 '2022-03-21',
 '2008-02-27',
 '2012-06-27',
 '2010-12-03',
 '2019-04-19',
 '2019-11-25',
 '2008-07-28',
 '2009-03-09',
 '2016-05-07',
 '2019-05-12',
 '2012-09-17',
 '2008-03-27',
 '2021-03-15',
 '2019-11-11',
 '2008-04-27',
 '2021-01-26',
 '2019-05-26',
 '2013-01-11',
 '2010-10-12',
 '2009-03-20',
 '2010-10-25',
 '2015-05-19',
 '2019-03-23',
 '2011-07-09',
 '2011-08-30',
 '2009-05-24',
 '2013-12-07',
 '2018-09-25',
 '2016-09-06',
 '2013-06-12',
 '2014-08-13',
 '2009-05-29',
 '2011-07-26',
 '2012-05-07',
 '2007-08-28',
 '2018-02-12',
 '2018-08-21',
 '2008-02-29',
 '2020-02-07',
 '2014-09-28',
 '2021-06-25',
 '2011-06-30',
 '2008-04-02',
 '2010-05-29',
 '2020-06-18',
 '2019-02-16',
 '2013-09-11',
 '2008-04-07',
 '2012-09-12',
 '2020-09-09',
 '2010-04-12',
 '2015-02-23',
 '2014-01-07',
 '2021-02-18',
 '2018-11-29',
 '2019-09-08',
 '2012-11-22',
 '2015-01-04',
 '2008-04-09',
 '2012-10-31',
 '2014-05-22',
 '2008-08-08',
 '2016-03-30',
 '2015-03-04',
 '2015-01-11',
 '2019-05-23',
 '2008-06-01',
 '2008-10-02',
 '2016-07-23',
 '2015-12-26',
 '2014-11-27',
 '2021-05-14',
 '2012-11-11',
 '2010-06-10',
 '2012-10-26',
 '2020-07-30',
 '2009-01-04',
 '2021-02-14',
 '2010-11-30',
 '2011-12-31',
 '2020-09-27',
 '2012-12-19',
 '2019-04-18',
 '2008-10-12',
 '2008-01-20',
 '2014-05-07',
 '2022-03-10',
 '2012-06-26',
 '2008-08-19',
 '2013-08-30',
 '2010-04-06',
 '2009-04-27',
 '2008-09-12',
 '2019-02-17',
 '2008-09-08',
 '2021-01-09',
 '2011-12-19',
 '2015-06-03',
 '2021-04-19',
 '2009-03-10',
 '2013-04-22',
 '2014-05-25',
 '2015-05-14',
 '2018-09-05',
 '2014-02-23',
 '2019-07-22',
 '2014-03-05',
 '2019-12-02',
 '2012-01-11',
 '2012-05-06',
 '2022-08-28',
 '2014-01-27',
 '2021-07-21',
 '2019-05-09',
 '2015-11-29',
 '2012-01-27',
 '2007-09-05',
 '2011-12-03',
 '2018-04-24',
 '2008-12-18',
 '2016-01-19',
 '2014-04-08',
 '2022-02-12',
 '2013-05-29',
 '2020-05-24',
 '2016-06-06',
 '2021-06-15',
 '2015-05-16',
 '2011-07-19',
 '2012-02-03',
 '2009-04-25',
 '2021-10-31',
 '2011-07-16',
 '2015-04-24',
 '2022-10-27',
 '2008-08-11',
 '2015-04-26',
 '2019-04-16',
 '2011-09-20',
 '2015-06-09',
 '2008-02-28',
 '2008-03-31',
 '2015-10-19',
 '2021-11-24',
 '2014-07-21',
 '2022-12-30',
 '2021-11-02',
 '2013-04-10',
 '2014-01-05',
 '2011-04-14',
 '2018-11-14',
 '2022-02-11',
 '2022-11-30',
 '2015-06-25',
 '2014-01-06',
 '2018-10-15',
 '2012-10-29',
 '2008-03-28',
 '2018-08-04',
 '2008-11-20',
 '2015-12-13',
 '2012-04-02',
 '2014-12-30',
 '2014-01-14',
 '2008-03-03',
 '2013-07-25',
 '2022-12-22',
 '2019-06-30',
 '2014-06-11',
 '2022-11-29',
 '2010-05-18',
 '2018-02-21',
 '2014-03-08',
 '2014-03-07',
 '2014-12-25',
 '2019-06-25',
 '2018-11-12',
 '2012-01-08',
 '2009-01-09',
 '2010-05-13',
 '2015-05-12',
 '2018-04-06',
 '2015-01-12',
 '2013-01-07',
 '2021-04-28',
 '2019-02-18',
 '2021-03-13',
 '2011-11-30',
 '2021-04-14',
 '2014-11-13',
 '2018-09-19',
 '2015-02-01',
 '2014-12-21',
 '2011-01-19',
 '2010-12-30',
 '2008-04-08',
 '2019-10-27',
 '2011-07-11',
 '2015-06-29',
 '2018-10-02',
 '2008-06-28',
 '2012-05-12',
 '2007-08-31',
 '2008-07-27',
 '2011-08-27',
 '2021-01-01',
 '2007-10-21',
 '2020-12-18',
 '2008-08-03',
 '2013-02-10',
 '2014-07-04',
 '2019-06-17',
 '2012-10-13',
 '2008-05-26',
 '2022-10-02',
 '2021-04-15',
 '2014-08-07',
 '2014-08-05',
 '2013-10-28',
 '2018-03-27',
 '2012-01-07',
 '2011-05-24',
 '2019-05-17',
 '2014-06-12',
 '2023-01-30',
 '2020-07-14',
 '2012-11-26',
 '2015-12-30',
 '2010-04-01',
 '2021-12-31',
 '2014-03-22',
 '2021-07-09',
 '2012-03-07',
 '2010-04-22',
 '2015-11-24',
 '2010-03-19',
 '2014-07-23',
 '2014-07-22',
 '2016-06-13',
 '2019-03-30',
 '2011-05-11',
 '2022-07-13',
 '2013-06-13',
 '2020-08-28',
 '2015-07-08',
 '2008-01-01',
 '2013-09-13',
 '2008-02-16',
 '2015-02-15',
 '2021-01-20',
 '2014-10-24',
 '2011-10-27',
 '2021-03-10',
 '2012-02-04',
 '2019-06-21',
 '2020-10-25',
 '2022-10-30',
 '2018-08-14',
 '2010-04-23',
 '2018-12-13',
 '2008-01-16',
 '2022-02-24',
 '2020-11-24',
 '2013-02-21',
 '2012-05-19',
 '2020-09-08',
 '2013-08-10',
 '2016-03-31',
 '2008-07-23',
 '2015-05-17',
 '2022-01-19',
 '2008-10-10',
 '2019-03-14',
 '2014-09-02',
 '2019-04-13',
 '2021-02-13',
 '2015-01-07',
 '2015-04-17',
 '2010-01-31',
 '2011-04-29',
 '2014-02-06',
 '2009-04-05',
 '2018-10-09',
 '2017-12-26',
 '2008-06-16',
 '2020-06-23',
 '2008-05-07',
 '2022-01-14',
 '2012-07-28',
 '2022-10-03',
 '2016-05-26',
 '2016-12-07',
 '2010-03-23',
 '2018-09-27',
 '2015-04-23',
 '2019-11-27',
 '2019-10-10',
 '2010-11-04'}

In [15]:
def good_runs_series(dates_ser):
    runs_list = []
    num_dates = len(dates_ser)
    if num_dates == 0:
        return []
    elif num_dates == 1:
        return [[dates_ser.at[0],],]
    else:
        dates_ser = dates_ser.sort_values()
        dates_df = pd.DataFrame(dates_ser)
        dates_df.loc[:, 'forward_diff'] = -dates_df['date'].diff(periods=-1)
        dates_df.loc[:, 'good_forward'] = dates_df.apply(
            lambda row: row['forward_diff'] == pd.Timedelta(days=1),
            axis=1
        )
        end_runs = dates_df[~dates_df['good_forward']]
        num_runs = end_runs.shape[0]
        for j in range(num_runs):
            if j == 0:
                start_ind = 0
            else:
                start_ind = end_runs.index[j-1] + 1
            end_ind = end_runs.index[j]
            jth_run = dates_df.loc[start_ind:end_ind]
            runs_list.append(sorted(jth_run['date']))
        return runs_list

In [23]:
def good_runs_reader(dates_ser):
    run_lengths = []
    good_runs = good_runs_series(dates_ser)
    for run in good_runs:
        print(f'From {run[0]} to {run[-1]}, a run of {len(run)} days.')
        run_lengths.append(len(run))
    run_lengths = pd.Series(run_lengths, name='run_len')
    return run_lengths

In [24]:
loose_runs = good_runs_reader(good_days_temp['date'])

From 2007-08-27 to 2007-11-20, a run of 86 days.
From 2007-11-22 to 2007-12-04, a run of 13 days.
From 2007-12-20 to 2008-03-01, a run of 73 days.
From 2008-03-03 to 2008-04-02, a run of 31 days.
From 2008-04-07 to 2008-08-21, a run of 137 days.
From 2008-08-28 to 2008-11-29, a run of 94 days.
From 2008-12-01 to 2008-12-03, a run of 3 days.
From 2008-12-05 to 2009-01-25, a run of 52 days.
From 2009-01-27 to 2009-04-03, a run of 67 days.
From 2009-04-05 to 2009-04-16, a run of 12 days.
From 2009-04-19 to 2009-05-29, a run of 41 days.
From 2010-01-23 to 2010-01-31, a run of 9 days.
From 2010-02-25 to 2010-03-26, a run of 30 days.
From 2010-03-30 to 2010-04-01, a run of 3 days.
From 2010-04-06 to 2010-04-09, a run of 4 days.
From 2010-04-12 to 2010-04-30, a run of 19 days.
From 2010-05-04 to 2010-05-10, a run of 7 days.
From 2010-05-13 to 2010-06-24, a run of 43 days.
From 2010-06-29 to 2010-07-09, a run of 11 days.
From 2010-07-14 to 2010-07-15, a run of 2 days.
From 2010-10-11 to 2011-01-08, a run of 90 days.
From 2011-01-10 to 2011-10-25, a run of 289 days.
From 2011-10-27 to 2012-07-06, a run of 254 days.
From 2012-07-10 to 2012-10-17, a run of 100 days.
From 2012-10-19 to 2013-02-23, a run of 128 days.
From 2013-02-25 to 2013-03-08, a run of 12 days.
From 2013-03-10 to 2013-03-22, a run of 13 days.
From 2013-03-24 to 2013-04-08, a run of 16 days.
From 2013-04-10 to 2013-04-14, a run of 5 days.
From 2013-04-18 to 2013-04-30, a run of 13 days.
From 2013-05-02 to 2013-11-20, a run of 203 days.
From 2013-11-22 to 2013-12-03, a run of 12 days.
From 2013-12-05 to 2014-01-03, a run of 30 days.
From 2014-01-05 to 2014-01-30, a run of 26 days.
From 2014-02-02 to 2014-08-01, a run of 181 days.
From 2014-08-04 to 2014-10-05, a run of 63 days.
From 2014-10-07 to 2014-11-11, a run of 36 days.
From 2014-11-13 to 2014-12-13, a run of 31 days.
From 2014-12-15 to 2015-01-20, a run of 37 days.
From 2015-01-22 to 2015-02-03, a run of 13 days.
From 2015-02-05 to 2015-02-15, a run of 11 days.
From 2015-02-17 to 2015-02-21, a run of 5 days.
From 2015-02-23 to 2015-02-25, a run of 3 days.
From 2015-03-02 to 2015-12-11, a run of 285 days.
From 2015-12-13 to 2015-12-14, a run of 2 days.
From 2015-12-16 to 2016-01-30, a run of 46 days.
From 2016-02-04 to 2016-03-17, a run of 43 days.
From 2016-03-19 to 2016-03-22, a run of 4 days.
From 2016-03-24 to 2016-04-15, a run of 23 days.
From 2016-04-17 to 2016-12-13, a run of 241 days.
From 2017-12-22 to 2018-01-20, a run of 30 days.
From 2018-01-22 to 2018-02-19, a run of 29 days.
From 2018-02-21 to 2018-04-12, a run of 51 days.
From 2018-04-16 to 2018-09-09, a run of 147 days.
From 2018-09-19 to 2018-09-19, a run of 1 days.
From 2018-09-24 to 2018-09-25, a run of 2 days.
From 2018-09-27 to 2018-09-27, a run of 1 days.
From 2018-10-01 to 2018-10-04, a run of 4 days.
From 2018-10-08 to 2018-10-12, a run of 5 days.
From 2018-10-15 to 2018-10-18, a run of 4 days.
From 2018-11-07 to 2018-11-09, a run of 3 days.
From 2018-11-12 to 2018-11-16, a run of 5 days.
From 2018-11-19 to 2018-11-20, a run of 2 days.
From 2018-11-26 to 2018-11-29, a run of 4 days.
From 2018-12-04 to 2018-12-13, a run of 10 days.
From 2019-01-29 to 2019-02-02, a run of 5 days.
From 2019-02-04 to 2019-02-07, a run of 4 days.
From 2019-02-14 to 2019-02-21, a run of 8 days.
From 2019-03-01 to 2019-03-01, a run of 1 days.
From 2019-03-04 to 2019-03-12, a run of 9 days.
From 2019-03-14 to 2019-10-28, a run of 229 days.
From 2019-10-30 to 2019-11-25, a run of 27 days.
From 2019-11-27 to 2019-12-02, a run of 6 days.
From 2019-12-11 to 2019-12-17, a run of 7 days.
From 2020-01-23 to 2020-02-03, a run of 12 days.
From 2020-02-05 to 2020-02-27, a run of 23 days.
From 2020-02-29 to 2020-03-18, a run of 19 days.
From 2020-03-21 to 2020-04-12, a run of 23 days.
From 2020-04-14 to 2020-04-15, a run of 2 days.
From 2020-04-17 to 2020-06-04, a run of 49 days.
From 2020-06-06 to 2020-06-25, a run of 20 days.
From 2020-06-27 to 2020-07-02, a run of 6 days.
From 2020-07-06 to 2020-10-25, a run of 112 days.
From 2020-10-27 to 2020-12-10, a run of 45 days.
From 2020-12-12 to 2021-03-13, a run of 92 days.
From 2021-03-15 to 2021-12-31, a run of 292 days.
From 2022-01-02 to 2022-02-01, a run of 31 days.
From 2022-02-03 to 2022-03-05, a run of 31 days.
From 2022-03-07 to 2022-03-16, a run of 10 days.
From 2022-03-18 to 2022-04-30, a run of 44 days.
From 2022-07-01 to 2023-01-01, a run of 185 days.
From 2023-01-03 to 2023-01-17, a run of 15 days.
From 2023-01-19 to 2023-02-14, a run of 27 days.
From 2023-02-16 to 2023-02-27, a run of 12 days.

In [28]:
loose_runs.value_counts().sort_index().tail(15)

run_len
94     1
100    1
112    1
128    1
137    1
147    1
181    1
185    1
203    1
229    1
241    1
254    1
285    1
289    1
292    1
Name: count, dtype: int64

In [87]:
tight_runs = good_runs_reader(good_days_retry['date'])

From 2007-09-01 to 2007-09-01, a run of 1 days.
From 2007-09-03 to 2007-09-04, a run of 2 days.
From 2007-09-07 to 2007-09-08, a run of 2 days.
From 2007-09-11 to 2007-09-15, a run of 5 days.
From 2007-09-18 to 2007-09-19, a run of 2 days.
From 2007-09-21 to 2007-09-23, a run of 3 days.
From 2007-09-25 to 2007-10-06, a run of 12 days.
From 2007-10-08 to 2007-10-12, a run of 5 days.
From 2007-10-15 to 2007-10-20, a run of 6 days.
From 2007-10-22 to 2007-11-16, a run of 26 days.
From 2007-11-18 to 2007-11-19, a run of 2 days.
From 2007-11-24 to 2007-11-27, a run of 4 days.
From 2007-11-29 to 2007-11-30, a run of 2 days.
From 2007-12-02 to 2007-12-03, a run of 2 days.
From 2007-12-20 to 2007-12-20, a run of 1 days.
From 2007-12-22 to 2007-12-24, a run of 3 days.
From 2007-12-30 to 2007-12-31, a run of 2 days.
From 2008-01-02 to 2008-01-06, a run of 5 days.
From 2008-01-09 to 2008-01-10, a run of 2 days.
From 2008-01-12 to 2008-01-14, a run of 3 days.
From 2008-01-17 to 2008-01-17, a run of 1 days.
From 2008-01-19 to 2008-01-19, a run of 1 days.
From 2008-01-22 to 2008-02-03, a run of 13 days.
From 2008-02-06 to 2008-02-13, a run of 8 days.
From 2008-02-15 to 2008-02-15, a run of 1 days.
From 2008-02-18 to 2008-02-24, a run of 7 days.
From 2008-03-04 to 2008-03-04, a run of 1 days.
From 2008-03-06 to 2008-03-16, a run of 11 days.
From 2008-03-18 to 2008-03-26, a run of 9 days.
From 2008-04-11 to 2008-04-15, a run of 5 days.
From 2008-04-18 to 2008-04-25, a run of 8 days.
From 2008-05-03 to 2008-05-06, a run of 4 days.
From 2008-05-08 to 2008-05-11, a run of 4 days.
From 2008-05-13 to 2008-05-25, a run of 13 days.
From 2008-06-03 to 2008-06-03, a run of 1 days.
From 2008-06-06 to 2008-06-07, a run of 2 days.
From 2008-06-09 to 2008-06-15, a run of 7 days.
From 2008-06-17 to 2008-06-22, a run of 6 days.
From 2008-07-03 to 2008-07-06, a run of 4 days.
From 2008-07-08 to 2008-07-22, a run of 15 days.
From 2008-07-24 to 2008-07-26, a run of 3 days.
From 2008-07-29 to 2008-08-02, a run of 5 days.
From 2008-08-04 to 2008-08-05, a run of 2 days.
From 2008-08-07 to 2008-08-07, a run of 1 days.
From 2008-08-09 to 2008-08-10, a run of 2 days.
From 2008-08-12 to 2008-08-14, a run of 3 days.
From 2008-08-17 to 2008-08-18, a run of 2 days.
From 2008-08-20 to 2008-08-20, a run of 1 days.
From 2008-08-29 to 2008-08-30, a run of 2 days.
From 2008-09-01 to 2008-09-04, a run of 4 days.
From 2008-09-06 to 2008-09-07, a run of 2 days.
From 2008-09-09 to 2008-09-10, a run of 2 days.
From 2008-09-13 to 2008-09-27, a run of 15 days.
From 2008-09-29 to 2008-10-01, a run of 3 days.
From 2008-10-03 to 2008-10-09, a run of 7 days.
From 2008-10-13 to 2008-10-19, a run of 7 days.
From 2008-10-21 to 2008-10-22, a run of 2 days.
From 2008-10-24 to 2008-11-02, a run of 10 days.
From 2008-11-04 to 2008-11-04, a run of 1 days.
From 2008-11-06 to 2008-11-13, a run of 8 days.
From 2008-11-15 to 2008-11-19, a run of 5 days.
From 2008-11-21 to 2008-11-24, a run of 4 days.
From 2008-11-26 to 2008-11-28, a run of 3 days.
From 2008-12-02 to 2008-12-02, a run of 1 days.
From 2008-12-05 to 2008-12-07, a run of 3 days.
From 2008-12-10 to 2008-12-12, a run of 3 days.
From 2008-12-15 to 2008-12-17, a run of 3 days.
From 2008-12-19 to 2009-01-01, a run of 14 days.
From 2009-01-05 to 2009-01-08, a run of 4 days.
From 2009-01-10 to 2009-01-11, a run of 2 days.
From 2009-01-13 to 2009-01-22, a run of 10 days.
From 2009-01-28 to 2009-02-12, a run of 16 days.
From 2009-02-15 to 2009-03-08, a run of 22 days.
From 2009-03-11 to 2009-03-19, a run of 9 days.
From 2009-03-21 to 2009-03-25, a run of 5 days.
From 2009-03-28 to 2009-03-31, a run of 4 days.
From 2009-04-02 to 2009-04-03, a run of 2 days.
From 2009-04-06 to 2009-04-11, a run of 6 days.
From 2009-04-13 to 2009-04-15, a run of 3 days.
From 2009-04-19 to 2009-04-21, a run of 3 days.
From 2009-04-24 to 2009-04-24, a run of 1 days.
From 2009-04-26 to 2009-04-26, a run of 1 days.
From 2009-04-28 to 2009-04-30, a run of 3 days.
From 2009-05-03 to 2009-05-09, a run of 7 days.
From 2009-05-11 to 2009-05-15, a run of 5 days.
From 2009-05-17 to 2009-05-23, a run of 7 days.
From 2009-05-25 to 2009-05-28, a run of 4 days.
From 2010-01-22 to 2010-01-27, a run of 6 days.
From 2010-01-29 to 2010-01-30, a run of 2 days.
From 2010-02-26 to 2010-02-27, a run of 2 days.
From 2010-03-01 to 2010-03-07, a run of 7 days.
From 2010-03-09 to 2010-03-13, a run of 5 days.
From 2010-03-16 to 2010-03-18, a run of 3 days.
From 2010-03-20 to 2010-03-22, a run of 3 days.
From 2010-03-25 to 2010-03-25, a run of 1 days.
From 2010-03-31 to 2010-03-31, a run of 1 days.
From 2010-04-07 to 2010-04-09, a run of 3 days.
From 2010-04-14 to 2010-04-21, a run of 8 days.
From 2010-04-24 to 2010-04-28, a run of 5 days.
From 2010-05-05 to 2010-05-09, a run of 5 days.
From 2010-05-15 to 2010-05-17, a run of 3 days.
From 2010-05-19 to 2010-05-28, a run of 10 days.
From 2010-05-30 to 2010-06-07, a run of 9 days.
From 2010-06-09 to 2010-06-09, a run of 1 days.
From 2010-06-12 to 2010-06-12, a run of 1 days.
From 2010-06-14 to 2010-06-24, a run of 11 days.
From 2010-06-30 to 2010-07-03, a run of 4 days.
From 2010-07-05 to 2010-07-05, a run of 1 days.
From 2010-07-08 to 2010-07-09, a run of 2 days.
From 2010-10-13 to 2010-10-24, a run of 12 days.
From 2010-10-26 to 2010-11-02, a run of 8 days.
From 2010-11-06 to 2010-11-08, a run of 3 days.
From 2010-11-10 to 2010-11-10, a run of 1 days.
From 2010-11-12 to 2010-11-14, a run of 3 days.
From 2010-11-16 to 2010-11-27, a run of 12 days.
From 2010-11-29 to 2010-11-29, a run of 1 days.
From 2010-12-02 to 2010-12-02, a run of 1 days.
From 2010-12-04 to 2010-12-04, a run of 1 days.
From 2010-12-07 to 2010-12-09, a run of 3 days.
From 2010-12-11 to 2010-12-13, a run of 3 days.
From 2010-12-16 to 2010-12-16, a run of 1 days.
From 2010-12-18 to 2010-12-23, a run of 6 days.
From 2010-12-25 to 2010-12-29, a run of 5 days.
From 2011-01-01 to 2011-01-08, a run of 8 days.
From 2011-01-12 to 2011-01-12, a run of 1 days.
From 2011-01-14 to 2011-01-14, a run of 1 days.
From 2011-01-16 to 2011-01-16, a run of 1 days.
From 2011-01-18 to 2011-01-18, a run of 1 days.
From 2011-01-20 to 2011-01-30, a run of 11 days.
From 2011-02-02 to 2011-02-04, a run of 3 days.
From 2011-02-07 to 2011-02-07, a run of 1 days.
From 2011-02-09 to 2011-02-24, a run of 16 days.
From 2011-02-26 to 2011-03-06, a run of 9 days.
From 2011-03-09 to 2011-03-17, a run of 9 days.
From 2011-03-19 to 2011-04-02, a run of 15 days.
From 2011-04-04 to 2011-04-05, a run of 2 days.
From 2011-04-07 to 2011-04-13, a run of 7 days.
From 2011-04-15 to 2011-04-23, a run of 9 days.
From 2011-04-25 to 2011-04-28, a run of 4 days.
From 2011-04-30 to 2011-05-10, a run of 11 days.
From 2011-05-12 to 2011-05-13, a run of 2 days.
From 2011-05-15 to 2011-05-17, a run of 3 days.
From 2011-05-19 to 2011-05-22, a run of 4 days.
From 2011-05-25 to 2011-06-07, a run of 14 days.
From 2011-06-09 to 2011-06-15, a run of 7 days.
From 2011-06-17 to 2011-06-19, a run of 3 days.
From 2011-06-21 to 2011-06-29, a run of 9 days.
From 2011-07-01 to 2011-07-04, a run of 4 days.
From 2011-07-06 to 2011-07-06, a run of 1 days.
From 2011-07-14 to 2011-07-15, a run of 2 days.
From 2011-07-17 to 2011-07-18, a run of 2 days.
From 2011-07-20 to 2011-07-25, a run of 6 days.
From 2011-07-27 to 2011-08-02, a run of 7 days.
From 2011-08-04 to 2011-08-26, a run of 23 days.
From 2011-08-29 to 2011-08-29, a run of 1 days.
From 2011-08-31 to 2011-09-13, a run of 14 days.
From 2011-09-15 to 2011-09-16, a run of 2 days.
From 2011-09-19 to 2011-09-19, a run of 1 days.
From 2011-09-27 to 2011-10-07, a run of 11 days.
From 2011-10-09 to 2011-10-16, a run of 8 days.
From 2011-10-19 to 2011-10-24, a run of 6 days.
From 2011-10-28 to 2011-11-01, a run of 5 days.
From 2011-11-03 to 2011-11-04, a run of 2 days.
From 2011-11-06 to 2011-11-06, a run of 1 days.
From 2011-11-08 to 2011-11-11, a run of 4 days.
From 2011-11-14 to 2011-11-27, a run of 14 days.
From 2011-11-29 to 2011-11-29, a run of 1 days.
From 2011-12-02 to 2011-12-02, a run of 1 days.
From 2011-12-04 to 2011-12-04, a run of 1 days.
From 2011-12-06 to 2011-12-13, a run of 8 days.
From 2011-12-15 to 2011-12-18, a run of 4 days.
From 2011-12-20 to 2011-12-21, a run of 2 days.
From 2011-12-23 to 2011-12-30, a run of 8 days.
From 2012-01-01 to 2012-01-02, a run of 2 days.
From 2012-01-04 to 2012-01-05, a run of 2 days.
From 2012-01-09 to 2012-01-10, a run of 2 days.
From 2012-01-12 to 2012-01-21, a run of 10 days.
From 2012-01-23 to 2012-01-26, a run of 4 days.
From 2012-01-28 to 2012-02-02, a run of 6 days.
From 2012-02-05 to 2012-02-06, a run of 2 days.
From 2012-02-08 to 2012-02-22, a run of 15 days.
From 2012-02-24 to 2012-03-06, a run of 12 days.
From 2012-03-08 to 2012-04-01, a run of 25 days.
From 2012-04-04 to 2012-04-13, a run of 10 days.
From 2012-04-16 to 2012-05-05, a run of 20 days.
From 2012-05-08 to 2012-05-10, a run of 3 days.
From 2012-05-13 to 2012-05-15, a run of 3 days.
From 2012-05-17 to 2012-05-18, a run of 2 days.
From 2012-05-20 to 2012-05-22, a run of 3 days.
From 2012-05-24 to 2012-06-01, a run of 9 days.
From 2012-06-03 to 2012-06-14, a run of 12 days.
From 2012-06-16 to 2012-06-19, a run of 4 days.
From 2012-06-21 to 2012-06-23, a run of 3 days.
From 2012-06-25 to 2012-06-25, a run of 1 days.
From 2012-06-28 to 2012-07-05, a run of 8 days.
From 2012-07-11 to 2012-07-15, a run of 5 days.
From 2012-07-17 to 2012-07-26, a run of 10 days.
From 2012-07-30 to 2012-08-10, a run of 12 days.
From 2012-08-12 to 2012-08-21, a run of 10 days.
From 2012-08-23 to 2012-09-02, a run of 11 days.
From 2012-09-04 to 2012-09-11, a run of 8 days.
From 2012-09-13 to 2012-09-16, a run of 4 days.
From 2012-09-18 to 2012-10-04, a run of 17 days.
From 2012-10-07 to 2012-10-12, a run of 6 days.
From 2012-10-14 to 2012-10-17, a run of 4 days.
From 2012-10-19 to 2012-10-23, a run of 5 days.
From 2012-10-28 to 2012-10-28, a run of 1 days.
From 2012-10-30 to 2012-10-30, a run of 1 days.
From 2012-11-02 to 2012-11-06, a run of 5 days.
From 2012-11-08 to 2012-11-09, a run of 2 days.
From 2012-11-12 to 2012-11-13, a run of 2 days.
From 2012-11-15 to 2012-11-21, a run of 7 days.
From 2012-11-23 to 2012-11-23, a run of 1 days.
From 2012-11-25 to 2012-11-25, a run of 1 days.
From 2012-11-27 to 2012-12-04, a run of 8 days.
From 2012-12-07 to 2012-12-08, a run of 2 days.
From 2012-12-10 to 2012-12-11, a run of 2 days.
From 2012-12-13 to 2012-12-14, a run of 2 days.
From 2012-12-16 to 2012-12-18, a run of 3 days.
From 2012-12-20 to 2013-01-06, a run of 18 days.
From 2013-01-08 to 2013-01-10, a run of 3 days.
From 2013-01-12 to 2013-01-27, a run of 16 days.
From 2013-01-30 to 2013-02-03, a run of 5 days.
From 2013-02-05 to 2013-02-07, a run of 3 days.
From 2013-02-11 to 2013-02-13, a run of 3 days.
From 2013-02-15 to 2013-02-18, a run of 4 days.
From 2013-02-23 to 2013-02-23, a run of 1 days.
From 2013-02-26 to 2013-03-03, a run of 6 days.
From 2013-03-05 to 2013-03-08, a run of 4 days.
From 2013-03-11 to 2013-03-11, a run of 1 days.
From 2013-03-13 to 2013-03-22, a run of 10 days.
From 2013-03-26 to 2013-04-01, a run of 7 days.
From 2013-04-03 to 2013-04-08, a run of 6 days.
From 2013-04-11 to 2013-04-14, a run of 4 days.
From 2013-04-19 to 2013-04-21, a run of 3 days.
From 2013-04-24 to 2013-04-30, a run of 7 days.
From 2013-05-03 to 2013-05-07, a run of 5 days.
From 2013-05-09 to 2013-05-14, a run of 6 days.
From 2013-05-16 to 2013-05-28, a run of 13 days.
From 2013-05-30 to 2013-06-11, a run of 13 days.
From 2013-06-14 to 2013-06-15, a run of 2 days.
From 2013-06-17 to 2013-06-22, a run of 6 days.
From 2013-06-24 to 2013-07-11, a run of 18 days.
From 2013-07-14 to 2013-07-24, a run of 11 days.
From 2013-07-26 to 2013-07-29, a run of 4 days.
From 2013-07-31 to 2013-08-02, a run of 3 days.
From 2013-08-04 to 2013-08-09, a run of 6 days.
From 2013-08-11 to 2013-08-21, a run of 11 days.
From 2013-08-24 to 2013-08-29, a run of 6 days.
From 2013-08-31 to 2013-09-08, a run of 9 days.
From 2013-09-14 to 2013-09-14, a run of 1 days.
From 2013-09-16 to 2013-09-26, a run of 11 days.
From 2013-09-28 to 2013-10-03, a run of 6 days.
From 2013-10-05 to 2013-10-09, a run of 5 days.
From 2013-10-11 to 2013-10-13, a run of 3 days.
From 2013-10-15 to 2013-10-17, a run of 3 days.
From 2013-10-19 to 2013-10-19, a run of 1 days.
From 2013-10-21 to 2013-10-27, a run of 7 days.
From 2013-10-30 to 2013-11-03, a run of 5 days.
From 2013-11-05 to 2013-11-20, a run of 16 days.
From 2013-11-22 to 2013-11-24, a run of 3 days.
From 2013-11-26 to 2013-11-30, a run of 5 days.
From 2013-12-02 to 2013-12-02, a run of 1 days.
From 2013-12-10 to 2013-12-19, a run of 10 days.
From 2013-12-21 to 2014-01-03, a run of 14 days.
From 2014-01-08 to 2014-01-13, a run of 6 days.
From 2014-01-16 to 2014-01-22, a run of 7 days.
From 2014-01-24 to 2014-01-26, a run of 3 days.
From 2014-01-29 to 2014-01-30, a run of 2 days.
From 2014-02-03 to 2014-02-03, a run of 1 days.
From 2014-02-07 to 2014-02-09, a run of 3 days.
From 2014-02-11 to 2014-02-15, a run of 5 days.
From 2014-02-17 to 2014-02-22, a run of 6 days.
From 2014-02-24 to 2014-02-28, a run of 5 days.
From 2014-03-02 to 2014-03-04, a run of 3 days.
From 2014-03-06 to 2014-03-06, a run of 1 days.
From 2014-03-09 to 2014-03-10, a run of 2 days.
From 2014-03-12 to 2014-03-21, a run of 10 days.
From 2014-03-23 to 2014-04-02, a run of 11 days.
From 2014-04-04 to 2014-04-07, a run of 4 days.
From 2014-04-09 to 2014-04-12, a run of 4 days.
From 2014-04-14 to 2014-04-22, a run of 9 days.
From 2014-04-24 to 2014-04-26, a run of 3 days.
From 2014-04-28 to 2014-05-06, a run of 9 days.
From 2014-05-09 to 2014-05-10, a run of 2 days.
From 2014-05-13 to 2014-05-21, a run of 9 days.
From 2014-05-23 to 2014-05-24, a run of 2 days.
From 2014-05-27 to 2014-05-29, a run of 3 days.
From 2014-05-31 to 2014-06-04, a run of 5 days.
From 2014-06-06 to 2014-06-07, a run of 2 days.
From 2014-06-09 to 2014-06-10, a run of 2 days.
From 2014-06-13 to 2014-06-17, a run of 5 days.
From 2014-06-19 to 2014-07-02, a run of 14 days.
From 2014-07-05 to 2014-07-06, a run of 2 days.
From 2014-07-08 to 2014-07-10, a run of 3 days.
From 2014-07-13 to 2014-07-14, a run of 2 days.
From 2014-07-19 to 2014-07-20, a run of 2 days.
From 2014-07-24 to 2014-07-24, a run of 1 days.
From 2014-07-26 to 2014-07-28, a run of 3 days.
From 2014-07-31 to 2014-08-01, a run of 2 days.
From 2014-08-04 to 2014-08-04, a run of 1 days.
From 2014-08-06 to 2014-08-06, a run of 1 days.
From 2014-08-08 to 2014-08-12, a run of 5 days.
From 2014-08-14 to 2014-08-14, a run of 1 days.
From 2014-08-16 to 2014-08-18, a run of 3 days.
From 2014-08-21 to 2014-08-25, a run of 5 days.
From 2014-08-27 to 2014-08-30, a run of 4 days.
From 2014-09-01 to 2014-09-01, a run of 1 days.
From 2014-09-03 to 2014-09-10, a run of 8 days.
From 2014-09-12 to 2014-09-21, a run of 10 days.
From 2014-09-23 to 2014-09-27, a run of 5 days.
From 2014-09-30 to 2014-09-30, a run of 1 days.
From 2014-10-02 to 2014-10-05, a run of 4 days.
From 2014-10-07 to 2014-10-08, a run of 2 days.
From 2014-10-10 to 2014-10-15, a run of 6 days.
From 2014-10-17 to 2014-10-23, a run of 7 days.
From 2014-10-25 to 2014-11-02, a run of 9 days.
From 2014-11-04 to 2014-11-06, a run of 3 days.
From 2014-11-08 to 2014-11-09, a run of 2 days.
From 2014-11-14 to 2014-11-14, a run of 1 days.
From 2014-11-16 to 2014-11-18, a run of 3 days.
From 2014-11-20 to 2014-11-26, a run of 7 days.
From 2014-11-28 to 2014-11-29, a run of 2 days.
From 2014-12-01 to 2014-12-01, a run of 1 days.
From 2014-12-03 to 2014-12-03, a run of 1 days.
From 2014-12-05 to 2014-12-13, a run of 9 days.
From 2014-12-16 to 2014-12-19, a run of 4 days.
From 2014-12-24 to 2014-12-24, a run of 1 days.
From 2014-12-28 to 2014-12-28, a run of 1 days.
From 2014-12-31 to 2015-01-02, a run of 3 days.
From 2015-01-05 to 2015-01-06, a run of 2 days.
From 2015-01-08 to 2015-01-10, a run of 3 days.
From 2015-01-14 to 2015-01-15, a run of 2 days.
From 2015-01-17 to 2015-01-20, a run of 4 days.
From 2015-01-23 to 2015-01-31, a run of 9 days.
From 2015-02-02 to 2015-02-03, a run of 2 days.
From 2015-02-05 to 2015-02-14, a run of 10 days.
From 2015-02-18 to 2015-02-20, a run of 3 days.
From 2015-02-24 to 2015-02-24, a run of 1 days.
From 2015-03-03 to 2015-03-03, a run of 1 days.
From 2015-03-05 to 2015-03-24, a run of 20 days.
From 2015-03-26 to 2015-04-01, a run of 7 days.
From 2015-04-04 to 2015-04-15, a run of 12 days.
From 2015-04-19 to 2015-04-19, a run of 1 days.
From 2015-04-21 to 2015-04-22, a run of 2 days.
From 2015-04-25 to 2015-04-25, a run of 1 days.
From 2015-04-28 to 2015-05-03, a run of 6 days.
From 2015-05-05 to 2015-05-06, a run of 2 days.
From 2015-05-11 to 2015-05-11, a run of 1 days.
From 2015-05-13 to 2015-05-13, a run of 1 days.
From 2015-05-15 to 2015-05-15, a run of 1 days.
From 2015-05-18 to 2015-05-18, a run of 1 days.
From 2015-05-21 to 2015-05-21, a run of 1 days.
From 2015-05-23 to 2015-05-24, a run of 2 days.
From 2015-05-26 to 2015-06-02, a run of 8 days.
From 2015-06-04 to 2015-06-04, a run of 1 days.
From 2015-06-06 to 2015-06-06, a run of 1 days.
From 2015-06-08 to 2015-06-08, a run of 1 days.
From 2015-06-11 to 2015-06-15, a run of 5 days.
From 2015-06-17 to 2015-06-23, a run of 7 days.
From 2015-06-26 to 2015-06-27, a run of 2 days.
From 2015-06-30 to 2015-07-01, a run of 2 days.
From 2015-07-03 to 2015-07-05, a run of 3 days.
From 2015-07-07 to 2015-07-07, a run of 1 days.
From 2015-07-09 to 2015-07-12, a run of 4 days.
From 2015-07-14 to 2015-07-23, a run of 10 days.
From 2015-07-25 to 2015-08-16, a run of 23 days.
From 2015-08-18 to 2015-08-30, a run of 13 days.
From 2015-09-01 to 2015-09-02, a run of 2 days.
From 2015-09-04 to 2015-10-04, a run of 31 days.
From 2015-10-07 to 2015-10-17, a run of 11 days.
From 2015-10-20 to 2015-10-20, a run of 1 days.
From 2015-10-23 to 2015-11-04, a run of 13 days.
From 2015-11-06 to 2015-11-10, a run of 5 days.
From 2015-11-12 to 2015-11-16, a run of 5 days.
From 2015-11-18 to 2015-11-19, a run of 2 days.
From 2015-11-21 to 2015-11-23, a run of 3 days.
From 2015-12-01 to 2015-12-11, a run of 11 days.
From 2015-12-14 to 2015-12-14, a run of 1 days.
From 2015-12-16 to 2015-12-24, a run of 9 days.
From 2015-12-27 to 2015-12-29, a run of 3 days.
From 2015-12-31 to 2016-01-07, a run of 8 days.
From 2016-01-09 to 2016-01-18, a run of 10 days.
From 2016-01-20 to 2016-01-28, a run of 9 days.
From 2016-01-30 to 2016-01-30, a run of 1 days.
From 2016-02-05 to 2016-02-22, a run of 18 days.
From 2016-02-24 to 2016-03-06, a run of 12 days.
From 2016-03-08 to 2016-03-17, a run of 10 days.
From 2016-03-20 to 2016-03-22, a run of 3 days.
From 2016-03-25 to 2016-03-25, a run of 1 days.
From 2016-03-27 to 2016-03-29, a run of 3 days.
From 2016-04-01 to 2016-04-09, a run of 9 days.
From 2016-04-11 to 2016-04-15, a run of 5 days.
From 2016-04-19 to 2016-04-29, a run of 11 days.
From 2016-05-02 to 2016-05-06, a run of 5 days.
From 2016-05-09 to 2016-05-14, a run of 6 days.
From 2016-05-17 to 2016-05-18, a run of 2 days.
From 2016-05-20 to 2016-05-25, a run of 6 days.
From 2016-05-27 to 2016-06-05, a run of 10 days.
From 2016-06-08 to 2016-06-12, a run of 5 days.
From 2016-06-14 to 2016-06-19, a run of 6 days.
From 2016-06-21 to 2016-07-08, a run of 18 days.
From 2016-07-10 to 2016-07-22, a run of 13 days.
From 2016-07-24 to 2016-08-08, a run of 16 days.
From 2016-08-10 to 2016-08-10, a run of 1 days.
From 2016-08-12 to 2016-08-12, a run of 1 days.
From 2016-08-14 to 2016-08-18, a run of 5 days.
From 2016-08-20 to 2016-09-01, a run of 13 days.
From 2016-09-03 to 2016-09-05, a run of 3 days.
From 2016-09-07 to 2016-10-15, a run of 39 days.
From 2016-10-17 to 2016-11-16, a run of 31 days.
From 2016-11-19 to 2016-11-21, a run of 3 days.
From 2016-11-23 to 2016-11-26, a run of 4 days.
From 2016-11-28 to 2016-12-06, a run of 9 days.
From 2016-12-09 to 2016-12-12, a run of 4 days.

In [27]:
tight_runs.value_counts().sort_index().tail(15)

run_len
14    8
15    5
16    6
17    4
18    5
19    1
20    4
22    3
23    3
25    2
26    1
31    2
33    1
38    1
39    1
Name: count, dtype: int64

In [33]:
df_ext = maintainer_4.data.copy(deep=True)

In [5]:
df_ext['time'].dtype

dtype('<M8[ns]')

In [6]:
df_ext['time'] = df_ext['time'].dt.tz_localize('Etc/GMT+7')

In [7]:
first_date = df_ext.at[0, 'time'].date()

In [8]:
first_date

datetime.date(2007, 8, 27)

In [9]:
last_date = df_ext.at[53493, 'time'].date()

In [10]:
df_ext['hour'] = df_ext['time'].dt.hour
df_ext['date'] = df_ext['time'].dt.date
good_dates = list(df_ext['date'].unique())
good_dates.sort()

In [24]:
df_ext['hour'].value_counts(dropna=False)

hour
12    4557
13    4545
11    4539
14    4536
10    4519
15    4480
9     4480
8     4398
16    4324
7     4175
6     3045
17    2851
18    1508
5     1392
19     103
4       10
23       8
0        5
21       4
20       3
22       3
1        3
2        3
3        3
Name: count, dtype: int64

In [25]:
first_date = good_dates[0]
last_date = good_dates[-1]

In [26]:
last_date

datetime.date(2023, 2, 27)

In [115]:
maintainer_4 = PreRun(4, './temp_fix', None, systems_cleaned)
maintainer_4.fill_missing_hours(0)
maintainer_4.add_energy_features_only(daily_lags=3, remove_daily_lags_nans=True, todays_lags=1, remove_todays_lags_nans=False, remove_last_year_nans=False, include_day_of_year_cyclic=True)

                     time    energy
0     2007-08-27 12:00:00  0.188190
1     2007-08-27 14:00:00  0.024962
2     2007-08-27 15:00:00  0.035136
3     2007-08-27 16:00:00  0.039177
4     2007-08-27 17:00:00  0.037669
...                   ...       ...
53489 2023-02-27 13:00:00  0.366943
53490 2023-02-27 14:00:00  0.297565
53491 2023-02-27 15:00:00  0.348322
53492 2023-02-27 16:00:00  0.188479
53493 2023-02-27 17:00:00  0.017879

[53494 rows x 2 columns]

,time,energy,day,1_days_ago,2_days_ago,3_days_ago,1_hours_ago_today,day_of_year_sin,day_of_year_cos
0,2007-11-07 00:00:00,0.0,2007-11-07,0.0,0.0,0.0,NaN,-0.811539,0.584298
1,2007-11-07 01:00:00,0.0,2007-11-07,0.0,0.0,0.0,0.0,-0.811539,0.584298
2,2007-11-07 02:00:00,0.0,2007-11-07,0.0,0.0,0.0,0.0,-0.811539,0.584298
3,2007-11-07 03:00:00,0.0,2007-11-07,0.0,0.0,0.0,0.0,-0.811539,0.584298
4,2007-11-07 04:00:00,0.0,2007-11-07,0.0,0.0,0.0,0.0,-0.811539,0.584298
...,...,...,...,...,...,...,...,...,...
108571,2023-02-27 19:00:00,0.0,2023-02-27,0.0,0.0,0.0,0.0,0.831171,0.556017
108572,2023-02-27 20:00:00,0.0,2023-02-27,0.0,0.0,0.0,0.0,0.831171,0.556017
108573,2023-02-27 21:00:00,0.0,2023-02-27,0.0,0.0,0.0,0.0,0.831171,0.556017
108574,2023-02-27 22:00:00,0.0,2023-02-27,0.0,0.0,0.0,0.0,0.831171,0.556017
108575,2023-02-27 23:00:00,0.0,2023-02-27,0.0,0.0,0.0,0.0,0.831171,0.556017

In [113]:
maintainer_4.amended_data.iloc[50:60]

,time,energy,1_days_ago,2_days_ago,3_days_ago,1_hours_ago_today,day_of_year_sin,day_of_year_cos
50,2007-08-30 13:00:00,0.828614,NaN,NaN,NaN,0.861318,-0.845249,-0.534373
51,2007-08-30 14:00:00,0.381335,NaN,NaN,NaN,0.828614,-0.845249,-0.534373
52,2007-08-30 15:00:00,0.466359,NaN,NaN,NaN,0.381335,-0.845249,-0.534373
53,2007-08-30 16:00:00,0.110435,NaN,NaN,NaN,0.466359,-0.845249,-0.534373
54,2007-08-30 17:00:00,0.100978,NaN,NaN,NaN,0.110435,-0.845249,-0.534373
55,2007-08-31 06:00:00,0.036473,NaN,NaN,NaN,NaN,-0.854322,-0.519744
56,2007-08-31 07:00:00,0.227354,NaN,NaN,NaN,0.036473,-0.854322,-0.519744
57,2007-08-31 08:00:00,0.458783,NaN,NaN,NaN,0.227354,-0.854322,-0.519744
58,2007-08-31 09:00:00,0.641724,NaN,NaN,NaN,0.458783,-0.854322,-0.519744
59,2007-08-31 10:00:00,0.782232,NaN,NaN,NaN,0.641724,-0.854322,-0.519744

In [107]:
maintainer_4.add_weather_features_only()

In [108]:
maintainer_4.amended_data[['time', 'global_tilted_irradiance']].iloc[0:20]

                  time  global_tilted_irradiance
0  2007-08-27 00:00:00                  0.000000
1  2007-08-27 01:00:00                  0.000000
2  2007-08-27 02:00:00                  0.000000
3  2007-08-27 03:00:00                  0.000000
4  2007-08-27 04:00:00                  0.000000
5  2007-08-27 05:00:00                  0.000000
6  2007-08-27 06:00:00                  7.415111
7  2007-08-27 07:00:00                103.396584
8  2007-08-27 08:00:00                260.044617
9  2007-08-27 09:00:00                446.956970
10 2007-08-27 10:00:00                683.930786
11 2007-08-27 11:00:00                886.674927
12 2007-08-27 12:00:00                589.836304
13 2007-08-27 13:00:00                577.622986
14 2007-08-27 14:00:00                539.520020
15 2007-08-27 15:00:00                254.299561
16 2007-08-27 16:00:00                177.902924
17 2007-08-27 17:00:00                129.548172
18 2007-08-27 18:00:00                 76.307098
19 2007-08-27 19:00:00                  9.970595

In [58]:
df_alt = maintainer_4.amended_data

In [59]:
df_alt['time'].iloc[10:20]

10   2008-04-27 11:00:00
11   2008-04-27 12:00:00
12   2008-04-27 13:00:00
13   2008-04-27 14:00:00
14   2008-04-27 15:00:00
15   2008-04-28 10:00:00
16   2008-04-28 11:00:00
17   2008-04-28 12:00:00
18   2008-04-28 13:00:00
19   2008-04-28 14:00:00
Name: time, dtype: datetime64[ns]

In [64]:
(df_alt['energy'].shift(5) - df_alt['energy']).iloc[10:30]

10   -0.665120
11   -0.347420
12   -0.586441
13   -0.190517
14    0.274686
15    0.720866
16    0.677961
17    0.290237
18   -0.134023
19   -0.218939
20   -0.290716
21   -9.822985
22   -1.665314
23    0.849888
24    0.562392
25    0.117735
26    9.648816
27    2.179393
28   -0.246763
29   -0.150788
Name: energy, dtype: float64

In [11]:
fixed_index = pd.date_range(
    start=pd.Timestamp(year=first_date.year, month=first_date.month, day=first_date.day, hour=0, minute=0, second=0, tz='Etc/GMT+7'),
    end=pd.Timestamp(year=last_date.year, month=last_date.month, day=last_date.day, hour=23, minute=0, second=0, tz='Etc/GMT+7'),
    freq='h'
)

In [12]:
df_fill_na = df_ext.set_index('time').reindex(fixed_index, fill_value=np.nan)

In [15]:
df_fill_na.loc[:, 'energy_alt'] = df_fill_na['energy'].copy(deep=True)

In [14]:
df_fill_na

                           energy  hour date
2007-08-27 00:00:00-07:00     NaN   NaN  NaN
2007-08-27 01:00:00-07:00     NaN   NaN  NaN
2007-08-27 02:00:00-07:00     NaN   NaN  NaN
2007-08-27 03:00:00-07:00     NaN   NaN  NaN
2007-08-27 04:00:00-07:00     NaN   NaN  NaN
...                           ...   ...  ...
2023-02-27 19:00:00-07:00     NaN   NaN  NaN
2023-02-27 20:00:00-07:00     NaN   NaN  NaN
2023-02-27 21:00:00-07:00     NaN   NaN  NaN
2023-02-27 22:00:00-07:00     NaN   NaN  NaN
2023-02-27 23:00:00-07:00     NaN   NaN  NaN

[135936 rows x 3 columns]

In [19]:
for the_date in df_fill_na['date'].unique():
    df_date = df_fill_na[df_fill_na['date'] == the_date]
    df_date['energy_alt'] = df_date['energy_alt'].interpolate(method='time', limit=2, limit_area='inside')
    df_fill_na.loc[df_date.index, 'energy_alt'] = df_date['energy_alt']

In [22]:
sample_timestamp = pd.Timestamp(year=2026, month=5, day=4, hour=15, tz='ETC/GMT+4')

In [23]:
sample_timestamp.tz_convert('Etc/GMT+5')

Timestamp('2026-05-04 14:00:00-0500', tz='Etc/GMT+5')

In [21]:
df_fill_na.iloc[10:20]

                             energy  hour        date  energy_alt
2007-08-27 10:00:00-07:00       NaN   NaN         NaN         NaN
2007-08-27 11:00:00-07:00       NaN   NaN         NaN         NaN
2007-08-27 12:00:00-07:00  0.188190  12.0  2007-08-27    0.188190
2007-08-27 13:00:00-07:00       NaN   NaN         NaN         NaN
2007-08-27 14:00:00-07:00  0.024962  14.0  2007-08-27    0.024962
2007-08-27 15:00:00-07:00  0.035136  15.0  2007-08-27    0.035136
2007-08-27 16:00:00-07:00  0.039177  16.0  2007-08-27    0.039177
2007-08-27 17:00:00-07:00  0.037669  17.0  2007-08-27    0.037669
2007-08-27 18:00:00-07:00  0.033000  18.0  2007-08-27    0.033000
2007-08-27 19:00:00-07:00  0.018578  19.0  2007-08-27    0.018578

In [31]:
df_ext_alt = df_ext.set_index('time')

In [33]:
df_ext_alt = df_ext_alt.interpolate(method='time', limit=2)

In [34]:
df_ext_alt.head()

                             energy
time
2007-08-27 12:00:00-07:00  0.188190
2007-08-27 14:00:00-07:00  0.024962
2007-08-27 15:00:00-07:00  0.035136
2007-08-27 16:00:00-07:00  0.039177
2007-08-27 17:00:00-07:00  0.037669

In [17]:
df_fill_na.iloc[10:20]

                             energy  hour        date
2007-08-27 10:00:00-07:00  0.000000     0           0
2007-08-27 11:00:00-07:00  0.000000     0           0
2007-08-27 12:00:00-07:00  0.188190    12  2007-08-27
2007-08-27 13:00:00-07:00  0.000000     0           0
2007-08-27 14:00:00-07:00  0.024962    14  2007-08-27
2007-08-27 15:00:00-07:00  0.035136    15  2007-08-27
2007-08-27 16:00:00-07:00  0.039177    16  2007-08-27
2007-08-27 17:00:00-07:00  0.037669    17  2007-08-27
2007-08-27 18:00:00-07:00  0.033000    18  2007-08-27
2007-08-27 19:00:00-07:00  0.018578    19  2007-08-27

In [12]:
# interpolate short gaps
df_fill_na['energy_ext'] = df_fill_na['energy'].interpolate(method='time', limit=2, limit_area='inside')

In [13]:
df_fill_na.iloc[40:50]

                             energy  energy_ext
2007-08-28 16:00:00-07:00  0.283550    0.283550
2007-08-28 17:00:00-07:00  0.088194    0.088194
2007-08-28 18:00:00-07:00  0.003795    0.003795
2007-08-28 19:00:00-07:00       NaN    0.005690
2007-08-28 20:00:00-07:00       NaN    0.007585
2007-08-28 21:00:00-07:00       NaN         NaN
2007-08-28 22:00:00-07:00       NaN         NaN
2007-08-28 23:00:00-07:00       NaN         NaN
2007-08-29 00:00:00-07:00       NaN         NaN
2007-08-29 01:00:00-07:00       NaN         NaN

In [15]:
df_fill_na.iloc[40:50]

                             energy  hour        date
2007-08-28 16:00:00-07:00  0.283550  16.0  2007-08-28
2007-08-28 17:00:00-07:00  0.088194  17.0  2007-08-28
2007-08-28 18:00:00-07:00  0.003795  18.0  2007-08-28
2007-08-28 19:00:00-07:00  0.005690   NaN         NaN
2007-08-28 20:00:00-07:00  0.007585   NaN         NaN
2007-08-28 21:00:00-07:00       NaN   NaN         NaN
2007-08-28 22:00:00-07:00       NaN   NaN         NaN
2007-08-28 23:00:00-07:00       NaN   NaN         NaN
2007-08-29 00:00:00-07:00       NaN   NaN         NaN
2007-08-29 01:00:00-07:00       NaN   NaN         NaN

In [ ]:
maintainer_4.data

In [90]:
maintainer_4.amended_data.head()

                 time  energy
0 2007-08-27 00:00:00     0.0
1 2007-08-27 01:00:00     0.0
2 2007-08-27 02:00:00     0.0
3 2007-08-27 03:00:00     0.0
4 2007-08-27 04:00:00     0.0

In [ ]:
maintainer_4.amended_data = maintainer_4.data.copy(deep=True)

In [ ]:
maintainer_4.amended_data = maintainer_4.amended_data.set_index('time')

In [ ]:
maintainer_4.amended_data['energy'] = maintainer_4.amended_data['energy'].interpolate(limit=2)

In [ ]:
data_with_lags = maintainer_4.add_energy_features_only(daily_lags=14, include_last_year=True)

In [ ]:
data_good_ends = maintainer_4.good_end_days_naive(14)

In [ ]:
data_good_ends.columns

In [ ]:
data_good_ends.head()

In [ ]:
len(data_good_ends)