In [1]:
from PreRun import PreRun, PostRun
import pandas as pd
import numpy as np
import pyarrow.parquet as pq
import lightgbm as lgb
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import make_scorer
from itertools import product
from datetime import date, datetime
from by_dates_Kfold import k_fold_split_option_a
from tqdm import tqdm
from time import sleep
from sklearn.model_selection import GridSearchCV

In [2]:
systems_cleaned = pd.read_csv('../../../data/core/systems_cleaned.csv')

In [3]:
systems_cleaned.head()

,system_id,system_public_name,site_location,timezone_or_utc_offset,latitude,longitude,elevation_m,dc_capacity_kW,kg_climate,pvcz_composite,...,has_power_data,has_current_data,has_voltage_data,has_ac_data,has_dc_data,module_type,simplified_type,system_source,num_days_actual_records,sample_year
0,2,Residential 1a,"Lakewood, CO",America/Denver,39.7214,-105.0972,1675.0,2.912,Dfb,12,...,True,True,True,False,True,multi-Si,multicrystalline_Si,PVDAQ General,2180,2011
1,3,Residential 1b,"Lakewood, CO",America/Denver,39.7214,-105.0972,1675.0,2.720,Dfb,12,...,True,True,True,False,True,amorphous si,thin_film,PVDAQ General,2094,2011
2,4,NREL x-Si -1,"Golden, CO",7,39.7406,-105.1774,1795.3,1.000,BSk,12,...,True,True,True,True,True,mono-Si,monocrystalline_Si,PVDAQ General,5063,2008
3,10,NREL CIS -1,"Golden, CO",7,39.7404,-105.1774,1792.8,1.120,BSk,12,...,True,True,True,True,True,cis family thin-film,thin_film,PVDAQ General,5893,2007
4,33,Silicor Materials,"Golden, CO",7,39.7404,-105.1772,1794.0,2.400,BSk,12,...,True,True,True,True,True,Unknown,unknown,PVDAQ General,4438,2011

In [4]:
params = {
    'objective': 'regression',
    'task': 'train',
    'num_leaves': 10,
    'learning_rate': 0.1,
    'max_depth': 10,
    'num_iterations': 1000,
    'metric': 'custom',
    'verbose': -1
}

In [7]:
name_val = (('inverter', 'inverter'), ('meter', 'meter'), ('other', 'None'))
names_list = ('inverter', 'meter', 'other')
# 1332 dropped!
systems_good_timezones_manual_edit = [4, 10, 33, 36, 50, 51, 1199, 1204, 1283, 1284, 1289, 4902, 4903]

In [6]:
start_stop_dict = {
    system_id: {
        name[0]: [0, 0] for name in name_val
    } for system_id in systems_good_timezones_manual_edit
}
for system_id, (name, val) in product(systems_good_timezones_manual_edit, name_val):
    try:
        data_pq = pq.ParquetDataset(
            f'./test_results/{system_id}-{val}/{name}/{system_id}'
        )
        good_days_df = pd.read_csv(
            f'./test_results/{system_id}-{val}/good_days/{system_id}_good_days_{name}.csv'
        )
    except FileNotFoundError:
        start_stop_dict[system_id].pop(name)
        continue
    if val == 'None':
        real_val = None
    else:
        real_val = val
    prerun_system = PreRun(system_id, f'./test_results/{system_id}-{val}/', real_val, systems_cleaned)
    start_stop_dict[system_id][name][0] = prerun_system.data.at[0, 'time'].date()
    last_index = prerun_system.data.index[-1]
    start_stop_dict[system_id][name][1] = prerun_system.data.at[last_index, 'time'].date()

In [7]:
start_stop_dict

{4: {'other': [datetime.date(2007, 9, 1), datetime.date(2023, 2, 28)]},
 10: {'other': [datetime.date(2006, 1, 25), datetime.date(2023, 2, 28)]},
 33: {'other': [datetime.date(2010, 11, 10), datetime.date(2023, 2, 28)]},
 36: {'other': [datetime.date(2012, 3, 30), datetime.date(2019, 7, 21)]},
 50: {'other': [datetime.date(1994, 5, 14), datetime.date(2023, 2, 28)]},
 51: {'other': [datetime.date(1994, 5, 14), datetime.date(2023, 2, 28)]},
 1199: {'inverter': [datetime.date(2010, 5, 29), datetime.date(2018, 8, 3)]},
 1204: {'inverter': [datetime.date(2011, 2, 9), datetime.date(2015, 1, 5)]},
 1283: {'inverter': [datetime.date(2012, 1, 10), datetime.date(2022, 2, 8)],
  'meter': [datetime.date(2012, 1, 10), datetime.date(2022, 2, 8)]},
 1284: {'other': [datetime.date(2012, 6, 30), datetime.date(2015, 3, 15)]},
 1289: {'other': [datetime.date(2012, 9, 28), datetime.date(2020, 5, 13)]},
 4902: {'inverter': [datetime.date(2014, 7, 29), datetime.date(2018, 3, 14)],
  'meter': [datetime.date(2014, 7, 29), datetime.date(2018, 3, 14)]},
 4903: {'inverter': [datetime.date(2014, 8, 2), datetime.date(2018, 2, 16)],
  'meter': [datetime.date(2014, 8, 2), datetime.date(2018, 2, 16)]}}

### Wrappers on custom objective function

In [8]:
def custom_obj(preds: np.ndarray, eval_data: lgb.Dataset):
    y_true = eval_data.get_label()
    # first derivative is (2x) * [0.5 signum(x) + 1.5]
    multiplier = 1.5 + 0.5 * np.sign(preds - y_true)
    grad = 2 * (preds - y_true) * multiplier
    hess = 2 * multiplier * np.ones_like(preds)
    return (grad, hess)


def custom_eval(preds: np.ndarray, eval_data: lgb.Dataset):
    y_true = eval_data.get_label()
    metric_name = 'weight_over'
    value = PostRun.custom_error(y_true, preds,a=1,b=2)
    is_higher_better = False
    return (metric_name, value, is_higher_better)

In [9]:
params_b = {
    'objective': custom_obj,
    'task': 'train',
    'num_leaves': 10,
    'learning_rate': 0.1,
    'max_depth': 10,
    'num_iterations': 1000,
    'metric': 'custom',
    'verbose': -1
}

In [10]:
starter_kit = PreRun(50, './test_results/50-None', None, systems_cleaned)
starter_kit.add_energy_features_only(daily_lags=2, include_last_year=True, include_hour_cyclic=True, include_day_of_year_cyclic=True)
starter_kit.add_weather_features_only()
starter_kit.good_end_days_naive(streak=7)
good_ends = starter_kit.end_days_naive.copy(deep=True)
df = starter_kit.amended_data.copy(deep=True)
df['year'] = df['time'].dt.year
my_cols = ['year', 'hour_sin', 'hour_cos', 'day_of_year_sin', 'day_of_year_cos', 'last_year', '2_days_ago', 'cloud_cover', 'global_tilted_irradiance', 'proportion_daytime']
df_train = df.iloc[0:int(len(df)*0.8)]
outer_cv = k_fold_split_option_a(
    df_train=df_train,
    good_ends=good_ends,
    n_splits=1,
    window_size=None,
    front_or_back='back',
    gap_day=True,
    return_type='index'
)
last_train, last_test = outer_cv[0]

In [11]:
X_tt = df_train[my_cols]
y_tt = df_train['energy']
X_test = df_train[my_cols]
y_test = df_train['energy']
lgb_last_tt = lgb.Dataset(data=X_tt,label=y_tt)
lgb_last_ho = lgb.Dataset(data=X_test,label=y_test, reference=lgb_last_tt)

In [12]:
bst_a = lgb.train(params,lgb_last_tt)
bst_b = lgb.train(params,train_set=lgb_last_tt, feval=custom_eval, valid_sets=[lgb_last_ho,])
bst_c = lgb.train(params_b, train_set=lgb_last_tt, feval=custom_eval, valid_sets=[lgb_last_ho,])

In [13]:
preds = bst_a.predict(X_test)

In [14]:
preds_b = bst_b.predict(X_test)
preds_c = bst_c.predict(X_test)

In [15]:
custom_eval(preds, lgb_last_ho)

('weight_over', np.float64(0.740840911402962), False)

In [16]:
custom_eval(preds_b, lgb_last_ho)

('weight_over', np.float64(0.740840911402962), False)

In [17]:
custom_eval(preds_c, lgb_last_ho)

('weight_over', np.float64(0.6753456742220194), False)

#### OK, so the custom objective function is doing something!

In [18]:
bst_c.dump_model(None)

{'name': 'tree',
 'version': 'v4',
 'num_class': 1,
 'num_tree_per_iteration': 1,
 'label_index': 0,
 'max_feature_idx': 9,
 'average_output': False,
 'feature_names': ['year',
  'hour_sin',
  'hour_cos',
  'day_of_year_sin',
  'day_of_year_cos',
  'last_year',
  '2_days_ago',
  'cloud_cover',
  'global_tilted_irradiance',
  'proportion_daytime'],
 'monotone_constraints': [],
 'feature_infos': {'year': {'min_value': 1994,
   'max_value': 2018,
   'values': []},
  'hour_sin': {'min_value': -1, 'max_value': 1, 'values': []},
  'hour_cos': {'min_value': -1, 'max_value': 1, 'values': []},
  'day_of_year_sin': {'min_value': -0.9999907397361901,
   'max_value': 0.9999907397361901,
   'values': []},
  'day_of_year_cos': {'min_value': -1, 'max_value': 1, 'values': []},
  'last_year': {'min_value': 0, 'max_value': 6.997999999999999, 'values': []},
  '2_days_ago': {'min_value': 0, 'max_value': 7.072975, 'values': []},
  'cloud_cover': {'min_value': 0, 'max_value': 1, 'values': []},
  'global_tilted_irradiance': {'min_value': 0,
   'max_value': 1185.6412353515625,
   'values': []},
  'proportion_daytime': {'min_value': 0, 'max_value': 1, 'values': []}},
 'tree_info': [{'tree_index': 0,
   'num_leaves': 10,
   'num_cat': 0,
   'shrinkage': 0.1,
   'tree_structure': {'split_index': 0,
    'split_feature': 8,
    'split_gain': 211106,
    'threshold': 467.52827453613287,
    'decision_type': '<=',
    'default_left': True,
    'missing_type': 'None',
    'internal_value': 0.22918,
    'internal_weight': 120452,
    'internal_count': 58534,
    'left_child': {'split_index': 3,
     'split_feature': 6,
     'split_gain': 19398.400390625,
     'threshold': 1.415739416666667,
     'decision_type': '<=',
     'default_left': True,
     'missing_type': 'NaN',
     'internal_value': 0.0877943,
     'internal_weight': 56271,
     'internal_count': 26911,
     'left_child': {'split_index': 5,
      'split_feature': 8,
      'split_gain': 6153.0400390625,
      'threshold': 202.94299316406253,
      'decision_type': '<=',
      'default_left': True,
      'missing_type': 'None',
      'internal_value': 0.05864,
      'internal_weight': 45141,
      'internal_count': 21346,
      'left_child': {'leaf_index': 0,
       'leaf_value': 0.034621058596556106,
       'leaf_weight': 31717,
       'leaf_count': 14815},
      'right_child': {'split_index': 7,
       'split_feature': 1,
       'split_gain': 4173.85009765625,
       'threshold': 0.37940952255126054,
       'decision_type': '<=',
       'default_left': True,
       'missing_type': 'None',
       'internal_value': 0.11539,
       'internal_weight': 13424,
       'internal_count': 6531,
       'left_child': {'leaf_index': 6,
        'leaf_value': 0.08176962314958929,
        'leaf_weight': 9845,
        'leaf_count': 4818},
       'right_child': {'leaf_index': 8,
        'leaf_value': 0.2078712711127223,
        'leaf_weight': 3579,
        'leaf_count': 1713}}},
     'right_child': {'leaf_index': 4,
      'leaf_value': 0.2060382496652939,
      'leaf_weight': 11130,
      'leaf_count': 5565}},
    'right_child': {'split_index': 1,
     'split_feature': 6,
     'split_gain': 46452.1015625,
     'threshold': 0.06211108333333334,
     'decision_type': '<=',
     'default_left': False,
     'missing_type': 'NaN',
     'internal_value': 0.35314,
     'internal_weight': 64181,
     'internal_count': 31623,
     'left_child': {'leaf_index': 1,
      'leaf_value': 0.00023566322527223218,
      'leaf_weight': 3525,
      'leaf_count': 1365},
     'right_child': {'split_index': 2,
      'split_feature': 1,
      'split_gain': 25307.80078125,
      'threshold': -0.25881904510252113,
      'decision_type': '<=',
      'default_left': True,
      'missing_type': 'None',
      'internal_value': 0.373649,
      'internal_weight': 60656,
      'internal_count': 30258,
      'left_child': {'split_index': 6,
       'split_feature': 8,
       'split_gain': 5344.39013671875,
       'threshold': 689.1770019531251,
       'decision_type': '<=',
       'default_left': True,
       'missing_type': 'None',
       'internal_value': 0.262073,
       'internal_weight': 15226,
       'internal_count': 7597,
       'left_child': {'leaf_index': 2,
        'leaf_value': 0.2123739094700007,
        'leaf_weight': 8937,
        'leaf_count': 4458},
       'right_child': {'leaf_index': 7,
        'leaf_value': 0.33269874463600957,
        'leaf_weight': 6289,
        'leaf_count': 3139}},
      'right_child': {'split_index': 4,
       'split_feature': 7,
       'split_gain': 10116.2001953125,
       'threshold': 0.3949999958276749,
       'decision_type': '<=',
       'default_left': True,
       'missing_type': 'None',
       'internal_value': 0.411044,
       'internal_weight': 45430,
       'internal_count': 22661,
       'left_child': {'split_index': 8,
        'split_feature': 4,
        'split_gain': 3930.139892578125,
        'threshold': -0.28435918728100346,
        'decision_type': '<=',
        'default_left': True,
        'missing_type': 'None',
        'internal_value': 0.448521,
        'internal_weight': 27858,
        'internal_count': 13894,
        'left_child': {'leaf_index': 3,
         'leaf_value': 0.40432314291364246,
         'leaf_weight': 11682,
         'leaf_count': 5815},
        'right_child': {'leaf_index': 9,
         'leaf_value': 0.4804406461110431,
         'leaf_weight': 16176,
         'leaf_count': 8079}},
       'right_child': {'leaf_index': 5,
        'leaf_value': 0.35162781414589206,
        'leaf_weight': 17572,
        'leaf_count': 8767}}}}}},
  {'tree_index': 1,
   'num_leaves': 10,
   'num_cat': 0,
   'shrinkage': 0.1,
   'tree_structure': {'split_index': 0,
    'split_feature': 8,
    'split_gain': 187174,
    'threshold': 450.2267150878907,
    'decision_type': '<=',
    'default_left': True,
    'missing_type': 'None',
    'internal_value': 0.188496,
    'internal_weight': 131570,
    'internal_count': 58534,
    'left_child': {'split_index': 3,
     'split_feature': 6,
     'split_gain': 16484.5,
     'threshold': 1.090293666666667,
     'decision_type': '<=',
     'default_left': True,
     'missing_type': 'NaN',
     'internal_value': 0.065331,
     'internal_weight': 63674,
     'internal_count': 26284,
     'left_child': {'split_index': 6,
      'split_feature': 6,
      'split_gain': 4973.39013671875,
      'threshold': 0.20010286666666668,
      'decision_type': '<=',
      'default_left': False,
      'missing_type': 'NaN',
      'internal_value': 0.0389655,
      'internal_weight': 50196,
      'internal_count': 19729,
      'left_child': {'leaf_index': 0,
       'leaf_value': 0.004803469432792546,
       'leaf_weight': 23048,
       'leaf_count': 7320},
      'right_child': {'split_index': 7,
       'split_feature': 8,
       'split_gain': 3106.489990234375,
       'threshold': 209.38714599609378,
       'decision_type': '<=',
       'default_left': True,
       'missing_type': 'None',
       'internal_value': 0.0679683,
       'internal_weight': 27148,
       'internal_count': 12409,
       'left_child': {'leaf_index': 7,
        'leaf_value': 0.04372962625001558,
        'leaf_weight': 17938,
        'leaf_count': 7916},
       'right_child': {'split_index': 8,
        'split_feature': 1,
        'split_gain': 3430.449951171875,
        'threshold': -0.25881904510252113,
        'decision_type': '<=',
        'default_left': True,
        'missing_type': 'None',
        'internal_value': 0.115177,
        'internal_weight': 9210,
        'internal_count': 4493,
        'left_child': {'leaf_index': 8,
         'leaf_value': 0.07517180292478182,
         'leaf_weight': 6442,
         'leaf_count': 3148},
        'right_child': {'leaf_index': 9,
         'leaf_value': 0.20828214681190774,
         'leaf_weight': 2768,
         'leaf_count': 1345}}}},
     'right_child': {'leaf_index': 4,
      'leaf_value': 0.16352360336672242,
      'leaf_weight': 13478,
      'leaf_count': 6555}},
    'right_child': {'split_index': 1,
     'split_feature': 6,
     'split_gain': 56600.30078125,
     'threshold': 0.06211108333333334,
     'decision_type': '<=',
     'default_left': False,
     'missing_type': 'NaN',
     'internal_value': 0.304001,
     'internal_weight': 67896,
     'internal_count': 32250,
     'left_child': {'leaf_index': 1,
      'leaf_value': -0.00022799755120193402,
      'leaf_weight': 5610,
      'leaf_count': 1404},
     'right_child': {'split_index': 2,
      'split_feature': 8,
      'split_gain': 23403.599609375,
      'threshold': 741.9786376953126,
      'decision_type': '<=',
      'default_left': True,
      'missing_type': 'None',
      'internal_value': 0.331403,
      'internal_weight': 62286,
      'internal_count': 30846,
      'left_child': {'split_index': 4,
       'split_feature': 1,
       'split_gain': 8620.0498046875,
       'threshold': 0.2588190451025209,
       'decision_type': '<=',
       'default_left': True,
       'missing_type': 'None',
       'internal_value': 0.260436,
       'internal_weight': 26614,
       'internal_count': 13137,
       'left_child': {'leaf_index': 2,
        'leaf_value': 0.2074803164980208,
        'leaf_weight': 14264,
        'leaf_count': 7060},
       'right_child': {'leaf_index': 5,
        'leaf_value': 0.3215987533389361,
        'leaf_weight': 12350,
        'leaf_count': 6077}},
      'right_child': {'split_index': 5,
       'split_feature': 7,
       'split_gain': 5955.2099609375,
       'threshold': 0.21499999612569812,
       'decision_type': '<=',
       'default_left': True,
       'missing_type': 'None',
       'internal_value': 0.384349,
       'internal_weight': 35672,
       'internal_count': 17709,
       'left_child': {'leaf_index': 3,
        'leaf_value': 0.4277910684811964,
        'leaf_weight': 16744,
        'leaf_count': 8307},
       'right_child': {'leaf_index': 6,
        'leaf_value': 0.3459200199907821,
        'leaf_weight': 18928,
        'leaf_count': 9402}}}}}},
  {'tree_index': 2,
   'num_leaves': 10,
   'num_cat': 0,
   'shrinkage': 0.1,
   'tree_structure': {'split_index': 0,
    'split_feature': 8,
    'split_gain': 154822,
    'threshold': 478.9939270019532,
    'decision_type': '<=',
    'default_left': True,
    'missing_type': 'None',
    'internal_value': 0.165857,
    'internal_weight': 134464,
    'internal_count': 58534,
    'left_child': {'split_index': 3,
     'split_feature': 6,
     'split_gain': 14418.099609375,
     'threshold': 1.5257895000000001,
     'decision_type': '<=',
     'default_left': True,
     'missing_type': 'NaN',
     'internal_value': 0.0601604,
     'internal_weight': 68246,
     'internal_count': 27329,
     'left_child': {'split_index': 5,
      'split_feature': 9,
      'split_gain': 5059.330078125,
      'threshold': 0.9998611111111112,
      'decision_type': '<=',
      'default_left': True,
      'missing_type': 'None',
      'internal_value': 0.0389879,
      'internal_weight': 56300,
      'internal_count': 21767,
      'left_child': {'leaf_index': 0,
       'leaf_value': 0.0022189264634813444,
       'leaf_weight': 22480,
       'leaf_count': 6815},
      'right_child': {'split_index': 8,
       'split_feature': 6,
       'split_gain': 2930.280029296875,
       'threshold': 0.2362379166666667,
       'decision_type': '<=',
       'default_left': False,
       'missing_type': 'NaN',
       'internal_value': 0.063428,
       'internal_weight': 33820,
       'internal_count': 14952,
       'left_child': {'leaf_index': 6,
        'leaf_value': 0.016667157800811124,
        'leaf_weight': 9598,
        'leaf_count': 3661},
       'right_child': {'leaf_index': 9,
        'leaf_value': 0.0819570340041425,
        'leaf_weight': 24222,
        'leaf_count': 11291}}},
     'right_child': {'split_index': 7,
      'split_feature': 7,
      'split_gain': 3410.590087890625,
      'threshold': 0.7450000047683717,
      'decision_type': '<=',
      'default_left': True,
      'missing_type': 'None',
      'internal_value': 0.159944,
      'internal_weight': 11946,
      'internal_count': 5562,
      'left_child': {'leaf_index': 4,
       'leaf_value': 0.2068715409597752,
       'leaf_weight': 6744,
       'leaf_count': 3278},
      'right_child': {'leaf_index': 8,
       'leaf_value': 0.09910543694223026,
       'leaf_weight': 5202,
       'leaf_count': 2284}}},
    'right_child': {'split_index': 1,
     'split_feature': 6,
     'split_gain': 44145.69921875,
     'threshold': 0.0004766416666666668,
     'decision_type': '<=',
     'default_left': False,
     'missing_type': 'NaN',
     'internal_value': 0.274792,
     'internal_weight': 66218,
     'internal_count': 31205,
     'left_child': {'leaf_index': 1,
      'leaf_value': -5.851638433235256e-07,
      'leaf_weight': 5372,
      'leaf_count': 1343},
     'right_child': {'split_index': 2,
      'split_feature': 8,
      'split_gain': 18094.900390625,
      'threshold': 868.534393310547,
      'decision_type': '<=',
      'default_left': True,
      'missing_type': 'None',
      'internal_value': 0.299053,
      'internal_weight': 60846,
      'internal_count': 29862,
      'left_child': {'split_index': 4,
       'split_feature': 1,
       'split_gain': 8598.2099609375,
       'threshold': 0.2588190451025209,
       'decision_type': '<=',
       'default_left': True,
       'missing_type': 'None',
       'internal_value': 0.257937,
       'internal_weight': 38794,
       'internal_count': 18936,
       'left_child': {'split_index': 6,
        'split_feature': 8,
        'split_gain': 3575,
        'threshold': 628.3854980468751,
        'decision_type': '<=',
        'default_left': True,
        'missing_type': 'None',
        'internal_value': 0.21404,
        'internal_weight': 20752,
        'internal_count': 10128,
        'left_child': {'leaf_index': 2,
         'leaf_value': 0.15997966682706138,
         'leaf_weight': 7696,
         'leaf_count': 3720},
        'right_child': {'leaf_index': 7,
         'leaf_value': 0.2459067953526292,
         'leaf_weight': 13056,
         'leaf_count': 6408}},
       'right_child': {'leaf_index': 5,
        'leaf_value': 0.3084275985966596,
        'leaf_weight': 18042,
        'leaf_count': 8808}},
      'right_child': {'leaf_index': 3,
       'leaf_value': 0.3713828726203156,
       'leaf_weight': 22052,
       'leaf_count': 10926}}}}},
  {'tree_index': 3,
   'num_leaves': 10,
   'num_cat': 0,
   'shrinkage': 0.1,
   'tree_structure': {'split_index': 0,
    'split_feature': 8,
    'split_gain': 126802,
    'threshold': 439.07406616210943,
    'decision_type': '<=',
    'default_left': True,
    'missing_type': 'None',
    'internal_value': 0.146028,
    'internal_weight': 137328,
    'internal_count': 58534,
    'left_child': {'split_index': 3,
     'split_feature': 6,
     'split_gain': 9367.3896484375,
     'threshold': 1.5963881583333335,
     'decision_type': '<=',
     'default_left': True,
     'missing_type': 'NaN',
     'internal_value': 0.0477624,
     'internal_weight': 67128,
     'internal_count': 25866,
     'left_child': {'split_index': 6,
      'split_feature': 9,
      'split_gain': 3305.469970703125,
      'threshold': 0.9998611111111112,
      'decision_type': '<=',
      'default_left': True,
      'missing_type': 'None',
      'internal_value': 0.0317023,
      'internal_weight': 56656,
      'internal_count': 21176,
      'left_child': {'leaf_index': 0,
       'leaf_value': 0.0020012422639293518,
       'leaf_weight': 22554,
       'leaf_count': 6817},
      'right_child': {'split_index': 8,
       'split_feature': 1,
       'split_gain': 2199.860107421875,
       'threshold': -0.9159756150367533,
       'decision_type': '<=',
       'default_left': True,
       'missing_type': 'None',
       'internal_value': 0.0513456,
       'internal_weight': 34102,
       'internal_count': 14359,
       'left_child': {'leaf_index': 7,
        'leaf_value': 0.008832351243177241,
        'leaf_weight': 8970,
        'leaf_count': 3663},
       'right_child': {'leaf_index': 9,
        'leaf_value': 0.06651930384804174,
        'leaf_weight': 25132,
        'leaf_count': 10696}}},
     'right_child': {'split_index': 7,
      'split_feature': 7,
      'split_gain': 2601.6201171875,
      'threshold': 0.6050000190734864,
      'decision_type': '<=',
      'default_left': True,
      'missing_type': 'None',
      'internal_value': 0.134652,
      'internal_weight': 10472,
      'internal_count': 4690,
      'left_child': {'leaf_index': 4,
       'leaf_value': 0.1866749065155946,
       'leaf_weight': 5012,
       'leaf_count': 2395},
      'right_child': {'leaf_index': 8,
       'leaf_value': 0.08689687708036459,
       'leaf_weight': 5460,
       'leaf_count': 2295}}},
    'right_child': {'split_index': 1,
     'split_feature': 6,
     'split_gain': 35803.6015625,
     'threshold': 0.03228025833333334,
     'decision_type': '<=',
     'default_left': False,
     'missing_type': 'NaN',
     'internal_value': 0.239993,
     'internal_weight': 70200,
     'internal_count': 32668,
     'left_child': {'leaf_index': 1,
      'leaf_value': -0.0005643508902554414,
      'leaf_weight': 5686,
      'leaf_count': 1422},
     'right_child': {'split_index': 2,
      'split_feature': 8,
      'split_gain': 18129.5,
      'threshold': 731.5895385742189,
      'decision_type': '<=',
      'default_left': True,
      'missing_type': 'None',
      'internal_value': 0.261195,
      'internal_weight': 64514,
      'internal_count': 31246,
      'left_child': {'split_index': 4,
       'split_feature': 1,
       'split_gain': 5852.64013671875,
       'threshold': 0.37940952255126054,
       'decision_type': '<=',
       'default_left': True,
       'missing_type': 'None',
       'internal_value': 0.198935,
       'internal_weight': 27114,
       'internal_count': 12929,
       'left_child': {'leaf_index': 2,
        'leaf_value': 0.15920138910483284,
        'leaf_weight': 15660,
        'leaf_count': 7439},
       'right_child': {'leaf_index': 5,
        'leaf_value': 0.25325994716905437,
        'leaf_weight': 11454,
        'leaf_count': 5490}},
      'right_child': {'split_index': 5,
       'split_feature': 7,
       'split_gain': 5420.64013671875,
       'threshold': 0.28499999642372137,
       'decision_type': '<=',
       'default_left': True,
       'missing_type': 'None',
       'internal_value': 0.306331,
       'internal_weight': 37400,
       'internal_count': 18317,
       'left_child': {'leaf_index': 3,
        'leaf_value': 0.34221286188790045,
        'leaf_weight': 19806,
        'leaf_count': 9763},
       'right_child': {'leaf_index': 6,
        'leaf_value': 0.26593816132805626,
        'leaf_weight': 17594,
        'leaf_count': 8554}}}}}},
  {'tree_index': 4,
   'num_leaves': 10,
   'num_cat': 0,
   'shrinkage': 0.1,
   'tree_structure': {'split_index': 0,
    'split_feature': 8,
    'split_gain': 111239,
    'threshold': 478.9939270019532,
    'decision_type': '<=',
    'default_left': True,
    'missing_type': 'None',
    'internal_value': 0.131566,
    'internal_weight': 137060,
    'internal_count': 58534,
    'left_child': {'split_index': 3,
     'split_feature': 8,
     'split_gain': 9282.1103515625,
     'threshold': 202.94299316406253,
     'decision_type': '<=',
     'default_left': True,
     'missing_type': 'None',
     'internal_value': 0.045878,
     'internal_weight': 71960,
     'internal_count': 27329,
     'left_child': {'split_index': 8,
      'split_feature': 6,
      'split_gain': 2078.8701171875,
      'threshold': 0.625022625,
      'decision_type': '<=',
      'default_left': True,
      'missing_type': 'NaN',
      'internal_value': 0.0199023,
      'internal_weight': 47246,
      'internal_count': 16461,
      'left_child': {'leaf_index': 0,
       'leaf_value': 0.010222919850037192,
       'leaf_weight': 38952,
       'leaf_count': 12960},
      'right_child': {'leaf_index': 9,

### Trial 2: LGBMRegressor variant

In [10]:
def custom_lgbm_regressor_obj(y_true: np.ndarray, y_pred: np.ndarray):
    # first derivative is (2x) * [0.5 signum(x) + 1.5]
    multiplier = 1.5 + 0.5 * np.sign(y_pred - y_true)
    grad = 2 * (y_pred - y_true) * multiplier
    hess = 2 * multiplier * np.ones_like(y_pred)
    return (grad, hess)


def custom_lgbm_regressor_eval(y_true:np.ndarray, y_pred: np.ndarray):
    metric_name = 'weight_over'
    value = PostRun.custom_error(y_true, y_pred,a=1,b=2)
    maximize = False
    return (metric_name, value, maximize)


def custom_pre_scorer(y_true, y_pred):
    return PostRun.custom_error(y_true, y_pred, a=1, b=2)

In [11]:
params_b = {
    'objective': custom_obj,
    'task': 'train',
    'num_leaves': 10,
    'learning_rate': 0.1,
    'max_depth': 10,
    'num_iterations': 1000,
    'metric': 'custom',
    'verbose': -1
}

In [21]:
trial_reg = lgb.LGBMRegressor(num_leaves=10, max_depth=10,
                              objective=custom_lgbm_regressor_obj,
                              learning_rate=0.1,
                              n_estimators=1000  # equivalent of num_iterations!
                              )
# if LightGBM 4.7.0, use eval_X and eval_y instead of eval_set!
trial_reg.fit(X=X_tt, y=y_tt, eval_metric=custom_lgbm_regressor_eval, eval_set=[(X_test, y_test)])
y_pred = trial_reg.predict(X_test)
PostRun.custom_error(y_tt, y_pred)

np.float64(0.6753456738811889)

OK, same results so far!

In [12]:
def lightgbm_one_layer(system_id: int, read_path: str, met_or_inv, systems_cleaned: pd.DataFrame, params: dict, streak_len: int,
                         n_splits_outer: int):
    prerun_system = PreRun(system_id, read_path, met_or_inv, systems_cleaned)
    prerun_system.add_energy_features_only(daily_lags=2, include_last_year=True, include_hour_cyclic=True, include_day_of_year_cyclic=True)
    prerun_system.add_weather_features_only()
    prerun_system.good_end_days_naive(streak=streak_len)
    good_ends = prerun_system.end_days_naive.copy(deep=True)
    df = prerun_system.amended_data.copy(deep=True)
    df['year'] = df['time'].dt.year
    my_cols = ['year', 'hour_sin', 'hour_cos', 'day_of_year_sin', 'day_of_year_cos', 'last_year', '2_days_ago', 'cloud_cover', 'global_tilted_irradiance', 'proportion_daytime']
    df_train = df.iloc[0:int(len(df)*0.8)]
    outer_cv = k_fold_split_option_a(
        df_train=df_train,
        good_ends=good_ends,
        n_splits=n_splits_outer,
        window_size=None,
        front_or_back='back',
        gap_day=True,
        return_type='index')
    outer_test_results = []
    for (train_ind, test_ind) in tqdm(outer_cv):
        df_tt = df_train.loc[train_ind]
        df_ho = df_train.loc[test_ind]
        X_tt = df_tt[my_cols]
        y_tt = df_tt['energy']
        lgb_tt = lgb.Dataset(data=X_tt, label=y_tt)
        X_ho = df_ho[my_cols]
        y_ho = df_ho['energy']
        lgb_ho = lgb.Dataset(X_ho, y_ho, reference=lgb_tt)
        bst = lgb.train(
            params=params,
            train_set=lgb_tt,
            feval=custom_eval,
            valid_sets=[lgb_ho,]
        )
        y_pred = bst.predict(X_ho)
        val_error = PostRun.custom_error(y_pred,y_ho,1,2)
        outer_test_results.append(val_error)
    outer_test_results = pd.Series(outer_test_results, name='custom_error')
    return outer_test_results

In [23]:
names_list = [name[0] for name in name_val]

In [24]:
good_ends_count = pd.Series(
    data = np.zeros((len(systems_good_timezones_manual_edit)*3,)),
    index=pd.MultiIndex.from_product((systems_good_timezones_manual_edit, names_list)),
    name='num_good_ends'
)
for system_id, (name, val) in product(systems_good_timezones_manual_edit, name_val):
    try:
        data_pq = pq.ParquetDataset(
            f'./test_results/{system_id}-{val}/{name}/{system_id}'
        )
        good_days_df = pd.read_csv(
            f'./test_results/{system_id}-{val}/good_days/{system_id}_good_days_{name}.csv'
        )
    except FileNotFoundError:
        continue
    if val == 'None':
        real_val = None
    else:
        real_val = val
    trial_data = PreRun(system_id, f'./test_results/{system_id}-{val}', real_val, systems_cleaned)
    trial_data.good_end_days_naive(streak=7)
    num_good_ends = len(trial_data.end_days_naive)
    good_ends_count.at[(system_id, name)] = num_good_ends
# drop empty
good_ends_count = good_ends_count[good_ends_count > 0]
good_ends_count = good_ends_count.sort_values(ascending=False)

In [25]:
good_ends_count

50    other       2062.0
51    other       1784.0
33    other       1484.0
4     other       1127.0
10    other        891.0
1283  meter        864.0
      inverter     857.0
1199  inverter     828.0
4903  meter        452.0
1204  inverter     428.0
4903  inverter     427.0
4902  meter        394.0
      inverter     374.0
36    other        358.0
1289  other        322.0
1284  other        177.0
Name: num_good_ends, dtype: float64

In [26]:
early_results = lightgbm_one_layer(
    50, './test_results/50-None', None, systems_cleaned, params_b, 7, 100
)

100%|██████████| 100/100 [07:49<00:00,  4.69s/it]

In [27]:
early_results.describe()

count    100.000000
mean       1.273282
std        1.165655
min        0.029381
25%        0.392297
50%        0.888917
75%        1.778331
max        5.927781
Name: custom_error, dtype: float64

### Practice sklearn.API variants of commands

In [26]:
params_b = {
    'objective': custom_obj,
    'task': 'train',
    'num_leaves': 10,
    'learning_rate': 0.1,
    'max_depth': 10,
    'num_iterations': 1000,
    'metric': 'custom',
    'verbose': -1
}

In [27]:
def lightgbm_one_layer_b(system_id: int, read_path: str, met_or_inv, systems_cleaned: pd.DataFrame, params: dict, streak_len: int,
                         n_splits_outer: int):
    prerun_system = PreRun(system_id, read_path, met_or_inv, systems_cleaned)
    prerun_system.add_energy_features_only(daily_lags=2, include_last_year=True, include_hour_cyclic=True, include_day_of_year_cyclic=True)
    prerun_system.add_weather_features_only()
    prerun_system.good_end_days_naive(streak=streak_len)
    good_ends = prerun_system.end_days_naive.copy(deep=True)
    df = prerun_system.amended_data.copy(deep=True)
    df['year'] = df['time'].dt.year
    my_cols = ['year', 'hour_sin', 'hour_cos', 'day_of_year_sin', 'day_of_year_cos', 'last_year', '2_days_ago', 'cloud_cover', 'global_tilted_irradiance', 'proportion_daytime']
    df_train = df.iloc[0:int(len(df)*0.8)]
    outer_cv = k_fold_split_option_a(
        df_train=df_train,
        good_ends=good_ends,
        n_splits=n_splits_outer,
        window_size=None,
        front_or_back='back',
        gap_day=True,
        return_type='index')
    outer_test_results = []
    for (train_ind, test_ind) in tqdm(outer_cv):
        df_tt = df_train.loc[train_ind]
        df_ho = df_train.loc[test_ind]
        X_tt = df_tt[my_cols]
        y_tt = df_tt['energy']
        X_ho = df_ho[my_cols]
        y_ho = df_ho['energy']
        my_regressor = lgb.LGBMRegressor(num_leaves=params['num_leaves'], 
                                         learning_rate=params['learning_rate'],
                                         objective=custom_lgbm_regressor_obj,
                                         max_depth=params['max_depth'],
                                         n_estimators=params['num_iterations'])
        my_regressor.fit(X_tt, y_tt, eval_metric=custom_lgbm_regressor_eval, eval_set=(X_ho, y_ho))
        lgb_tt = lgb.Dataset(data=X_tt, label=y_tt)
        X_ho = df_ho[my_cols]
        y_ho = df_ho['energy']
        lgb_ho = lgb.Dataset(X_ho, y_ho, reference=lgb_tt)
        bst = lgb.train(
            params=params,
            train_set=lgb_tt,
            feval=custom_eval,
            valid_sets=[lgb_ho,]
        )
        y_pred = bst.predict(X_ho)
        val_error = PostRun.custom_error(y_pred,y_ho,1,2)
        outer_test_results.append(val_error)
    outer_test_results = pd.Series(outer_test_results, name='custom_error')
    return outer_test_results

In [30]:
early_results_b = lightgbm_one_layer_b(
    50, './test_results/50-None', None, systems_cleaned, params_b, 7, 100
)

100%|██████████| 100/100 [13:29<00:00,  8.09s/it]

In [31]:
mse(early_results,early_results_b)

8.319729439552853e-24

In [32]:
np.mean(np.abs(early_results - early_results_b))

np.float64(9.235544273789032e-13)

#### Not perfect, but decidedly close enough!

In [33]:
early_results = np.asarray(early_results)

In [34]:
systems_cleaned[systems_cleaned['system_id']==50]

,system_id,system_public_name,site_location,timezone_or_utc_offset,latitude,longitude,elevation_m,dc_capacity_kW,kg_climate,pvcz_composite,...,has_power_data,has_current_data,has_voltage_data,has_ac_data,has_dc_data,module_type,simplified_type,system_source,num_days_actual_records,sample_year
8,50,NREL x-Si 6,"Golden, CO",7,39.742,-105.1727,1994.7,6.0,BSk,12,...,True,True,True,True,True,Unknown,unknown,PVDAQ General,8455,1995

In [35]:
terms = [early_results.mean(), early_results.std(), early_results.min(), early_results.max()]

In [36]:
print(f'Mean: {terms[0]}, std: {terms[1]}, range:{terms[2]}, {terms[3]}')

Mean: 1.2732820683285153, std: 1.1598119460555265, range:0.029380985558968016, 5.927781187257565

## Add in some hyperparameter tuning!

In [28]:
def better_lightbgm_test(system_id: int, read_path: str, met_or_inv, systems_cleaned: pd.DataFrame,
                         streak_len: int,
                         n_splits_outer: int, n_splits_inner: int):
    prerun_system = PreRun(system_id, read_path, met_or_inv, systems_cleaned)
    prerun_system.add_energy_features_only(daily_lags=2, include_last_year=True, include_hour_cyclic=True, include_day_of_year_cyclic=True)
    prerun_system.add_weather_features_only()
    prerun_system.good_end_days_naive(streak=streak_len)
    good_ends = prerun_system.end_days_naive.copy(deep=True)
    df = prerun_system.amended_data.copy(deep=True)
    df['year'] = df['time'].dt.year
    my_cols = ['year', 'hour_sin', 'hour_cos', 'day_of_year_sin', 'day_of_year_cos', 'last_year', '2_days_ago', 'cloud_cover', 'global_tilted_irradiance', 'proportion_daytime']
    df_train_max = df.iloc[0:int(len(df)*0.8)]
    outer_cv = k_fold_split_option_a(
        df_train=df_train_max,
        good_ends=good_ends,
        n_splits=n_splits_outer, 
        window_size=None, 
        front_or_back='back',
        gap_day=False,
        return_type='index')
    outer_results = np.zeros((len(outer_cv),))
    for i, (train_ind, test_ind) in enumerate(outer_cv):
        df_train_out = df_train.loc[train_ind]
        df_val_out = df_train.loc[test_ind]
        X_train_out = df_train_out[my_cols]
        y_train_out = df_train_out['energy']
        lgb_train_out = lgb.Dataset(data=X_train_out, label=y_train_out)
        X_val_out = df_val_out[my_cols]
        y_val_out = df_val_out['energy']
        lgb_val_out = lgb.Dataset(X_val_out, y_val_out, reference=lgb_train_out)
        # inner loop,
        inner_cv = k_fold_split_option_a(
            df_train=df_train_out,
            good_ends=good_ends,
            n_splits=n_splits_inner,
            window_size=None, 
            front_or_back='back',
            gap_day=False,
            return_type='index')
        param_grid = {
            'num_leaves': (7, 15, 31),
            'max_depth': (-1, 5, 7, 10),
            'learning_rate': (0.05, 0.1, 0.15, 0.2),
            'n_estimators': (10, 100, 1000),
            'subsample': (0.8, 1.0),
            'colsample_bytree': (0.8, 1.0),
        }
        in_regressor = lgb.LGBMRegressor()
        local_scorer = make_scorer(custom_pre_scorer, greater_is_better=False)
        searcher = GridSearchCV(in_regressor, param_grid, scoring=local_scorer, cv=inner_cv,)
        searcher.fit(X_train_out, y_train_out)
        print(i)
        print(searcher.cv_results_)
        bst = searcher.best_estimator_
        y_out_preds = bst.predict(X_val_out)
        outer_results[i] = PostRun.custom_error(y_test, y_out_preds)
    outer_results = pd.Series(outer_results, name = ['outer_error'])
    return outer_results

This code takes way too long to run.  Will need to adjust

In [66]:
early_results_c = better_lightbgm_test(
    50, './test_results/50-None', None, systems_cleaned, 7, 15, 15
)

KeyboardInterrupt:

In [13]:
def lightgbm_one_layer_c(system_id: int, read_path: str, met_or_inv, systems_cleaned: pd.DataFrame, streak_len: int,
                         n_splits_outer: int):
    prerun_system = PreRun(system_id, read_path, met_or_inv, systems_cleaned)
    prerun_system.add_energy_features_only(daily_lags=2, include_last_year=True, include_hour_cyclic=True, include_day_of_year_cyclic=True)
    prerun_system.add_weather_features_only()
    prerun_system.good_end_days_naive(streak=streak_len)
    good_ends = prerun_system.end_days_naive.copy(deep=True)
    df = prerun_system.amended_data.copy(deep=True)
    df['year'] = df['time'].dt.year
    my_cols = ['year', 'hour_sin', 'hour_cos', 'day_of_year_sin', 'day_of_year_cos', 'last_year', '2_days_ago', 'cloud_cover', 'global_tilted_irradiance', 'proportion_daytime']
    df_train = df.iloc[0:int(len(df)*0.8)]
    outer_cv = k_fold_split_option_a(
        df_train=df_train,
        good_ends=good_ends,
        n_splits=n_splits_outer,
        window_size=None,
        front_or_back='back',
        gap_day=True,
        return_type='index')
    outer_test_results = []
    for i, (train_ind, test_ind) in enumerate(outer_cv):
        df_tt = df_train.loc[train_ind]
        df_ho = df_train.loc[test_ind]
        X_tt = df_tt[my_cols]
        y_tt = df_tt['energy']
        X_ho = df_ho[my_cols]
        y_ho = df_ho['energy']
        param_grid = {
            'num_leaves': (7, 15, 31),
            'max_depth': (-1, 5, 7, 10),
            'learning_rate': (0.05, 0.1, 0.15, 0.2),
            'n_estimators': (10, 100, 1000),
            'subsample': (0.8, 1.0),
            'colsample_bytree': (0.8, 1.0),
        }
        out_regressor = lgb.LGBMRegressor()
        local_scorer = make_scorer(custom_pre_scorer, greater_is_better=False)
        searcher = GridSearchCV(out_regressor, param_grid, scoring=local_scorer, cv=5,)
        searcher.fit(X_tt, y_tt)
        print(i)
        print(searcher.cv_results_)
        bst = searcher.best_estimator_
        y_out_preds = bst.predict(X_ho)
        outer_results[i] = PostRun.custom_error(y_ho, y_out_preds)
    outer_test_results = pd.Series(outer_test_results, name='custom_error')
    return outer_test_results

In [34]:
from pathlib import Path

In [36]:
my_dir = Path('../../../../data_ds_project/parquet_cleaned_energy/')
print(my_dir.is_dir())

True

In [ ]:
early_results_c = lightgbm_one_layer_c(
    50, '../../../../data_ds_project/parquet_cleaned_energy/', None, systems_cleaned, 7, 15
)

0
{'mean_fit_time': array([0.03102789, 0.03211222, 0.03967242, 0.04147296, 0.04286056,
       0.04258604, 0.09079652, 0.09231019, 0.12193203, 0.12164493,
       0.17376943, 0.17092075, 0.57686481, 0.56076007, 0.7986402 ,
       0.79924455, 1.26065321, 1.28357515, 0.03828282, 0.03780603,
       0.04218712, 0.04166288, 0.04169049, 0.04099021, 0.08867059,
       0.08740745, 0.11910162, 0.11834989, 0.15390935, 0.34904985,
       1.19694662, 1.59443202, 2.84829588, 2.35025587, 1.02361298,
       0.98830366, 0.0350256 , 0.0328207 , 0.03908868, 0.03742471,
       0.04467998, 0.04508343, 0.08413692, 0.09433937, 0.1268424 ,
       0.12845035, 0.19571247, 0.18470583, 0.53468256, 0.56527352,
       0.88137488, 1.08014803, 2.67561135, 5.22110395, 0.03402662,
       0.0306675 , 0.03765669, 0.0395772 , 0.04661589, 0.04645443,
       0.08151588, 0.08260794, 0.12801814, 0.12774816, 0.20246186,
       0.21224775, 0.51792603, 0.5323463 , 0.83506889, 2.10344963,
       3.66268401, 5.8254735 , 0.06053624, 0.05494018, 0.07580643,
       0.07494049, 0.11460485, 0.10681114, 0.2284071 , 0.22448058,
       0.39788289, 0.36736751, 0.66268911, 0.6953321 , 1.76383557,
       1.04357924, 2.82568779, 3.16296158, 5.81335769, 1.14281015,
       0.03305411, 0.03237548, 0.03818536, 0.03525457, 0.04023385,
       0.04004455, 0.07757926, 0.08351398, 0.10823345, 0.1071259 ,
       0.13472524, 0.13862996, 0.49597178, 0.4932147 , 2.20191646,
       2.79898267, 4.06180449, 1.17944469, 0.03709264, 0.03453107,
       0.03976688, 0.03942599, 0.04769878, 0.04681129, 0.08483615,
       0.08666067, 0.12337823, 0.11996946, 0.16594839, 0.1660078 ,
       0.52170391, 0.50230517, 0.78128181, 0.75360026, 1.19143872,
       1.9082778 , 0.03823528, 0.05209131, 0.06351595, 0.07277594,
       0.10383954, 0.10332966, 0.21099396, 0.20205407, 0.35210247,
       0.347294  , 0.67004819, 0.69401565, 1.80035682, 1.51271949,
       1.18556123, 2.88854933, 4.943924  , 2.93073144, 0.03270979,
       0.03244562, 0.03672457, 0.03495665, 0.04517097, 0.0455018 ,
       0.07960439, 0.07951221, 0.10921397, 0.10719466, 0.16568441,
       0.16726222, 0.50774107, 0.49713187, 0.77675943, 0.89943137,
       1.48161645, 1.4629755 , 0.04398804, 0.03649445, 0.04068851,
       0.04316258, 0.04954453, 0.0482842 , 0.09859428, 0.0997889 ,
       0.13013883, 0.13039789, 0.16597242, 0.16309514, 0.61445107,
       0.90615239, 2.69807272, 2.71716075, 4.09145432, 4.08948526,
       0.06039505, 0.05700955, 0.07675781, 0.07458587, 0.1046144 ,
       0.1058671 , 0.21324143, 0.20551467, 0.37941194, 0.35697913,
       0.56481562, 0.55622473, 1.6956737 , 1.66925926, 2.83289247,
       2.89242692, 2.51467953, 1.07900877, 0.0336504 , 0.03472152,
       0.03787088, 0.03711185, 0.04431267, 0.04685578, 0.08188686,
       0.08533449, 0.11447453, 0.11260109, 0.16900606, 0.16548405,
       0.51437082, 0.53063622, 0.79108901, 0.78417983, 1.16968346,
       1.19497523, 0.03559914, 0.03483949, 0.03936801, 0.04011507,
       0.05042582, 0.04912877, 0.08036103, 0.08034992, 0.1151515 ,
       0.11327853, 0.16752381, 0.17166595, 0.54188204, 0.5679204 ,
       0.86298151, 0.8640532 , 1.36821933, 1.37156763, 0.03859882,
       0.03566279, 0.04251523, 0.04569006, 0.04873028, 0.04666247,
       0.09532819, 0.09419241, 0.1240037 , 0.12384129, 0.16313772,
       0.15641084, 0.59540586, 0.59531007, 0.8700212 , 0.85384212,
       1.17315536, 1.19254436, 0.04203334, 0.03974328, 0.04601765,
       0.04289732, 0.05292454, 0.05437703, 0.09067831, 0.10164475,
       0.13446875, 0.12711558, 0.19076571, 0.21440568, 0.70538087,
       0.7050837 , 1.03193173, 1.00446744, 1.5127213 , 1.54563508,
       0.04081178, 0.04773874, 0.04659863, 0.04740086, 0.06099324,
       0.06201048, 0.10481696, 0.10849681, 0.14454546, 0.14799542,
       0.20943565, 0.21559258, 0.66227736, 0.67748842, 1.00319281,
       1.02201643, 1.53717518, 1.53100934, 0.04357014, 0.04133034,
       0.04723015, 0.04716167, 0.06352186, 0.0570272 , 0.11138597,
       0.11832051, 0.17095127, 0.17301106, 0.26076665, 0.26776552,
       0.67628446, 0.68544111, 1.04435725, 1.04109449, 1.64138799,
       1.59239316, 0.03985038, 0.04009404, 0.05117812, 0.05041442,
       0.05390944, 0.05162463, 0.10670576, 0.1056613 , 0.1513793 ,
       0.15196714, 0.18776011, 0.19015741, 0.67239518, 0.65532279,
       0.9403059 , 0.95236197, 1.30749755, 1.29271469, 0.03882651,
       0.0374577 , 0.04753208, 0.0475708 , 0.05181828, 0.05468774,
       0.1118022 , 0.10632329, 0.16401987, 0.15776043, 0.23205123,
       0.23415489, 0.6490098 , 0.65436625, 1.00085678, 0.99180007,
       1.47549109, 1.46278496, 0.04039359, 0.03886447, 0.04726481,
       0.04240098, 0.05696115, 0.0570755 , 0.10450206, 0.10370221,
       0.15807643, 0.15260081, 0.23389344, 0.27090211, 0.69207649,
       0.76177907, 1.10667372, 1.03323298, 1.59884486, 1.57278337,
       0.04096346, 0.03951817, 0.04434834, 0.04670238, 0.06043081,
       0.0531024 , 0.10022464, 0.10243034, 0.14583106, 0.14583855,
       0.21749601, 0.21836429, 0.63092551, 0.63265967, 0.97808328,
       0.94536033, 1.47008567, 1.46531377, 0.03627272, 0.03578534,
       0.04327731, 0.04146996, 0.04995418, 0.04858747, 0.09779038,
       0.09870224, 0.13050795, 0.12937365, 0.16985002, 0.16467395,
       0.60102553, 0.59866285, 0.87939544, 0.89949121, 1.17995453,
       1.16135321, 0.03823128, 0.03809624, 0.04303522, 0.04482374,
       0.05203452, 0.05309591, 0.09966803, 0.1018827 , 0.13474164,
       0.12887487, 0.18988643, 0.19971385, 0.6120563 , 0.58446193,
       0.88150191, 0.880585  , 1.34059005, 1.3275599 , 0.03598199,
       0.03797741, 0.04617987, 0.04300594, 0.05221214, 0.0517271 ,
       0.09939523, 0.09128809, 0.13820696, 0.13832278, 0.20536485,
       0.20105386, 0.59162893, 0.57591119, 0.88807383, 0.86934452,
       1.35444875, 1.35439882, 0.03805895, 0.03988242, 0.04304104,
       0.04186392, 0.05154376, 0.05253849, 0.09130988, 0.09290977,
       0.12416048, 0.12590151, 0.18643804, 0.19338164, 0.5660244 ,
       0.57104859, 0.86963925, 0.85938501, 1.33614206, 1.34138808,
       0.03748498, 0.03845968, 0.0360961 , 0.04051943, 0.04443107,
       0.0457252 , 0.09024816, 0.09038548, 0.13682508, 0.1180316 ,
       0.15501118, 0.14680271, 0.54432349, 0.55075316, 0.82266397,
       0.82550693, 1.14854584, 1.11929569, 0.0345871 , 0.0341795 ,
       0.04211378, 0.04200687, 0.05418768, 0.04856982, 0.09127502,
       0.0963119 , 0.12941208, 0.12757597, 0.18181663, 0.17631745,
       0.58702774, 0.58582349, 0.85238624, 0.86511378, 1.31166849,
       1.3221427 , 0.03740416, 0.0399333 , 0.04311175, 0.042208  ,
       0.05052037, 0.05247836, 0.09475899, 0.09358416, 0.12727132,
       0.12980261, 0.19001441, 0.18803706, 0.57180843, 0.56712437,
       0.882865  , 0.88991752, 1.32871299, 1.31212521, 0.03791232,
       0.0366621 , 0.04592395, 0.04358811, 0.04889207, 0.05431128,
       0.09006171, 0.08953404, 0.12402391, 0.12574077, 0.18645673,
       0.19024897, 0.56989183, 0.57583332, 0.86796775, 0.87569237,
       1.3540709 , 1.35787725, 0.03995442, 0.03729935, 0.03959861,
       0.0400588 , 0.04845138, 0.04451265, 0.0904882 , 0.09439454,
       0.11410494, 0.11596532, 0.15544825, 0.16142659, 0.55781283,
       0.56230497, 1.01426296, 0.91911883, 1.23740973, 1.21339369,
       0.03560014, 0.03815413, 0.04466829, 0.04295607, 0.05189672,
       0.05076308, 0.0952353 , 0.09604073, 0.12487774, 0.12987995,
       0.17998781, 0.18189001, 0.60426683, 0.60807014, 0.91936922,
       0.89748073, 1.3521699 , 1.35887165, 0.03950391, 0.03831773,
       0.04365225, 0.04598761, 0.05428662, 0.0536305 , 0.09666386,
       0.09445243, 0.13132291, 0.12812462, 0.19259777, 0.18464866,
       0.597543  , 0.5818675 , 0.90505672, 0.91576757, 1.33496776,
       1.35420928]), 'std_fit_time': array([2.10475419e-03, 2.08777991e-03, 9.59244297e-03, 4.80599713e-03,
       1.24009249e-03, 1.64548910e-03, 3.09828824e-03, 4.68398757e-03,
       2.96849333e-03, 7.00665232e-03, 1.07883300e-02, 3.59123127e-03,
       9.53365295e-03, 3.52639781e-02, 1.52986459e-02, 3.86816655e-02,
       4.97219408e-02, 1.89896199e-02, 1.99883431e-03, 1.41542253e-03,
       2.47129835e-03, 9.80148161e-04, 3.45544357e-03, 2.01248519e-03,
       2.38977487e-03, 2.94036411e-03, 5.02826606e-03, 2.91797642e-03,
       1.84106766e-03, 1.66169398e-01, 3.99696883e-01, 7.52062760e-02,
       2.45868254e-01, 7.43969844e-01, 1.12485014e-02, 1.09152808e-02,
       2.20456362e-03, 1.09725668e-03, 3.88710414e-03, 2.18438961e-03,
       3.17012075e-03, 2.12515772e-03, 3.28019657e-03, 2.80709965e-03,
       2.09786440e-03, 3.91768336e-03, 1.20610529e-02, 4.98070051e-03,
       2.83251540e-02, 3.38893256e-02, 2.90793562e-02, 2.62363210e-01,
       1.70670997e+00, 7.60761293e-01, 2.62159570e-03, 1.11472958e-03,
       2.36096739e-03, 1.52797976e-03, 3.85240733e-03, 3.63931380e-03,
       3.48100788e-03, 2.69320823e-03, 7.38973599e-03, 4.21604790e-03,
       1.15630770e-02, 8.59077093e-03, 1.12103761e-02, 1.87889585e-02,
       2.83335265e-02, 1.19322158e+00, 1.47240456e+00, 2.58911563e-01,
       2.94685138e-03, 1.42699190e-03, 2.59809595e-03, 2.78388981e-03,
       5.99467549e-03, 3.62844272e-03, 1.08502106e-02, 1.30374709e-02,
       3.07629985e-02, 1.42286208e-02, 7.03470924e-02, 1.92640044e-02,
       7.12645372e-02, 5.39065759e-01, 1.04454879e+00, 1.94194689e-01,
       3.10138990e-01, 4.09420553e-02, 1.56882443e-03, 1.75421258e-03,
       2.46433239e-03, 1.06095167e-03, 4.03061375e-03, 2.64976134e-03,
       2.23539829e-03, 2.02060125e-03, 1.83708360e-03, 4.27096289e-03,
       4.78496431e-03, 8.76381582e-03, 7.47515179e-03, 7.29199558e-03,
       9.06705863e-01, 1.27346016e-01, 3.07353052e-01, 2.99924545e-01,
       1.76024112e-03, 1.92648112e-03, 7.17167534e-04, 1.24293139e-03,
       3.11314620e-03, 4.24304807e-03, 1.23785535e-03, 2.67032990e-03,
       2.60161420e-03, 1.19002384e-03, 5.81628052e-03, 7.98402178e-03,
       1.07619756e-02, 1.01511418e-02, 2.64253331e-02, 2.67809201e-02,
       3.36209575e-02, 8.94431958e-01, 2.14298651e-03, 4.05323540e-03,
       4.38468702e-03, 4.68186137e-03, 9.64803352e-03, 2.51468699e-03,
       1.55339467e-02, 1.79891581e-02, 2.41533941e-02, 1.30454067e-02,
       4.09007654e-02, 3.52230212e-02, 7.44918790e-02, 4.38017601e-01,
       8.56982625e-01, 1.46446836e-01, 1.45877476e+00, 2.19665585e+00,
       1.34787226e-03, 2.50462208e-03, 2.25135758e-03, 6.79283033e-04,
       2.73287302e-03, 2.91787460e-03, 2.83890357e-03, 1.67841034e-03,
       7.82206356e-03, 2.87661495e-03, 7.73579415e-03, 8.75679280e-03,
       6.03703416e-03, 6.17117906e-03, 1.18757270e-02, 1.07065239e-01,
       1.75238147e-02, 2.61331899e-02, 3.52773063e-03, 2.97169990e-03,
       3.24212060e-03, 6.65758258e-04, 2.79618092e-03, 3.10024545e-03,
       3.88253186e-03, 5.09127356e-03, 6.09305542e-03, 5.27685189e-03,
       7.38435171e-03, 6.62115497e-03, 2.77123339e-02, 5.16622938e-01,
       7.83876070e-02, 8.34024824e-02, 9.03610710e-02, 1.29106409e-01,
       3.59243050e-03, 2.53548103e-03, 1.94785801e-03, 3.09384149e-03,
       4.58032442e-03, 1.23407379e-02, 1.14263598e-02, 9.50710505e-03,
       4.50981444e-02, 2.97629022e-02, 3.90192098e-02, 3.68505764e-02,
       3.95126160e-02, 5.71102430e-02, 1.82323766e-01, 1.56514062e-01,
       1.75247292e+00, 1.41513309e-02, 2.75129054e-03, 2.65556442e-03,
       8.70265163e-04, 7.81277008e-04, 2.83626706e-03, 3.99311393e-03,
       4.25456253e-03, 3.91652680e-03, 6.23740383e-03, 3.53377740e-03,
       4.90983487e-03, 7.79732446e-03, 8.22204215e-03, 1.63121947e-02,
       5.02739679e-03, 8.64527690e-03, 1.52728715e-02, 2.27382743e-02,
       2.68246961e-03, 2.72659640e-03, 7.11354610e-04, 1.39807528e-03,
       2.33343832e-03, 3.28445650e-03, 2.29531967e-03, 2.62271191e-03,
       6.08595291e-03, 4.62704845e-03, 6.62932501e-03, 6.30639650e-03,
       3.50907060e-02, 2.64014864e-02, 2.80594199e-02, 2.97773693e-02,
       1.42044780e-02, 3.45879363e-02, 1.89854959e-03, 2.62974120e-03,
       2.76999510e-03, 2.67817774e-03, 1.94282570e-03, 2.94455112e-03,
       1.55635486e-03, 3.59866104e-03, 3.79994957e-03, 5.68982792e-03,
       1.29764169e-02, 3.30887563e-03, 7.91965044e-03, 7.02995736e-03,
       1.36054551e-02, 2.21801948e-02, 4.68788525e-02, 5.10329173e-02,
       2.63031834e-03, 1.08454172e-03, 2.58513058e-03, 2.12638564e-03,
       1.51167536e-03, 3.67864873e-03, 5.09884692e-03, 3.56729945e-03,
       1.31022480e-02, 6.24803783e-03, 1.46515588e-02, 1.13656322e-02,
       6.13856941e-03, 8.78872427e-03, 3.48315670e-02, 3.93374182e-02,
       3.97111280e-02, 1.64008372e-02, 1.78704552e-03, 3.34103304e-03,
       1.45299202e-03, 5.08843003e-03, 5.40721853e-03, 2.56055364e-03,
       3.98002002e-03, 4.67173470e-03, 7.97639621e-03, 5.89594280e-03,
       8.06984196e-03, 7.99085745e-03, 1.88693646e-02, 9.62721744e-03,
       1.49565659e-02, 1.68785647e-02, 1.95287394e-02, 1.20452206e-02,
       4.48546905e-03, 2.92603530e-03, 2.77184942e-03, 1.90936322e-03,
       3.80541050e-03, 3.49229270e-03, 3.97583101e-03, 1.35968280e-02,
       7.91449249e-03, 5.51984044e-03, 4.26894796e-03, 5.95623479e-03,
       7.80799795e-03, 1.60742659e-02, 8.15352026e-03, 1.35951520e-02,
       2.05485349e-02, 1.56713452e-02, 1.91655994e-03, 2.99813512e-03,
       5.33409346e-03, 3.31265257e-03, 2.87510543e-03, 9.61998169e-04,
       4.41063864e-03, 3.33619287e-03, 2.63413921e-03, 7.02065514e-03,
       1.03512921e-02, 7.93286138e-03, 4.05803476e-02, 5.87718446e-03,
       2.74779588e-02, 2.12177870e-02, 3.49456125e-02, 2.14595076e-02,
       2.76784999e-03, 3.18477772e-03, 2.78262954e-03, 2.94547134e-03,
       1.62199043e-03, 8.51436336e-04, 7.67467099e-03, 5.59975558e-03,
       1.52953066e-02, 7.40526839e-03, 5.28125217e-03, 1.20575824e-02,
       7.43969226e-03, 5.75506574e-03, 2.40996914e-02, 1.58454829e-02,
       4.64353769e-02, 3.31129443e-02, 4.38359106e-03, 2.36045078e-03,
       3.73503979e-03, 3.65897063e-03, 3.17960710e-03, 3.50467232e-03,
       5.85573072e-03, 5.32197038e-03, 5.89182137e-03, 6.86812222e-03,
       9.52334322e-03, 4.36539011e-02, 2.24707163e-02, 4.93878968e-02,
       4.31451762e-02, 8.52844134e-03, 2.07604225e-02, 2.36217852e-02,
       2.41099569e-03, 2.14803238e-03, 3.01711847e-03, 3.43319067e-03,
       3.94260439e-03, 3.28770730e-03, 4.12837216e-03, 3.85209794e-03,
       5.89273935e-03, 7.13476114e-03, 5.83414771e-03, 5.21482718e-03,
       1.09682975e-02, 5.08348605e-03, 3.44120452e-02, 4.90358955e-03,
       2.55937528e-02, 4.16342110e-02, 4.33978149e-03, 2.90352467e-03,
       2.79435165e-03, 2.06049849e-03, 1.34854335e-03, 1.28790567e-03,
       5.16688739e-03, 5.86011563e-03, 4.24285122e-03, 2.85509239e-03,
       6.57040094e-03, 9.65371802e-03, 1.26425410e-02, 9.50801111e-03,
       2.22484388e-02, 2.85137871e-02, 3.65184482e-02, 2.40439525e-02,
       2.18220464e-03, 3.38119084e-03, 1.00855045e-03, 4.71719311e-03,
       3.18786649e-03, 3.76899868e-03, 3.79612685e-03, 2.57099502e-03,
       6.70242270e-03, 9.18035728e-03, 4.74284783e-03, 9.09623423e-03,
       2.30871241e-02, 2.54859900e-02, 1.79045960e-02, 1.36914497e-02,
       3.02840967e-02, 2.75857609e-02, 2.40674023e-03, 2.00052261e-03,
       3.02217315e-03, 2.35407561e-03, 2.30016647e-03, 1.86896490e-03,
       5.64279227e-03, 2.40600127e-03, 1.29572610e-02, 7.35756360e-03,
       5.23980540e-03, 3.31647304e-03, 8.94750600e-03, 3.05569077e-02,
       4.86965191e-02, 1.75662291e-02, 2.00613436e-02, 1.32163936e-02,
       7.12064704e-04, 3.01184341e-03, 3.05043997e-03, 8.76709990e-04,
       1.95509388e-03, 6.99958726e-04, 6.14939273e-03, 7.75287519e-03,
       2.48958729e-03, 6.51640460e-03, 8.40514283e-03, 9.31397667e-03,
       1.39115143e-02, 1.61145679e-02, 9.42461963e-03, 1.44871456e-02,
       1.79280130e-02, 2.03524120e-02, 5.38521958e-03, 7.56592210e-04,
       3.92260619e-03, 4.04867619e-03, 4.71261491e-03, 5.18440954e-03,
       3.69561847e-03, 5.36700773e-03, 5.24367331e-03, 4.25853089e-03,
       6.23190366e-03, 5.44342744e-03, 2.24777258e-02, 1.01934426e-02,
       2.26122535e-02, 1.48637954e-02, 8.87606993e-03, 2.47574451e-02,
       5.30930016e-04, 6.96239851e-04, 2.41529568e-03, 1.97689584e-03,
       3.31637002e-03, 2.84163930e-03, 5.07531288e-03, 3.92955612e-03,
       5.49775789e-03, 1.83290088e-03, 6.53330672e-03, 6.43726254e-03,
       1.65346809e-02, 1.17420608e-02, 3.65227916e-02, 1.89340147e-02,
       4.81259455e-02, 1.29873848e-02, 2.20072157e-03, 5.17785480e-03,
       4.08914609e-03, 1.30556211e-03, 3.52624625e-03, 2.16290504e-03,
       3.61141652e-03, 7.22274084e-03, 2.26113116e-03, 7.73749699e-03,
       4.71878693e-03, 5.64323925e-03, 1.92921032e-02, 1.08417546e-02,
       6.73759300e-03, 1.96746192e-02, 2.66504845e-02, 3.06421342e-02,
       2.41578420e-03, 2.54510921e-03, 2.70489529e-03, 4.75815671e-03,
       2.06730335e-03, 4.22390377e-03, 5.39920085e-03, 3.47024323e-03,
       3.42497903e-03, 8.64903854e-03, 4.66210353e-03, 1.32990292e-02,
       9.25564455e-03, 8.20111777e-03, 1.62006259e-02, 1.38032544e-02,
       2.70133639e-02, 4.72044852e-02, 2.35036620e-03, 2.52494475e-03,
       3.34521443e-03, 4.40746086e-03, 3.24173909e-03, 4.22631731e-03,
       4.55412950e-03, 2.43622739e-03, 3.57236106e-03, 5.99157027e-03,
       3.48194396e-03, 1.84613765e-02, 7.78168687e-03, 3.80047693e-02,
       7.34246123e-02, 4.64048619e-02, 2.69884123e-02, 2.71361247e-02,
       2.94740773e-03, 3.09220504e-03, 2.75285150e-03, 2.90215308e-03,
       2.22553108e-03, 2.34965152e-03, 1.73679262e-03, 2.47270620e-03,
       3.73984016e-03, 5.10187373e-03, 6.89796810e-03, 6.41709790e-03,
       3.62695709e-02, 1.49593827e-02, 1.36608369e-02, 1.75832117e-02,
       3.94986221e-02, 1.66352478e-02, 1.28535201e-03, 1.51495330e-03,
       2.04425226e-03, 4.79138871e-03, 2.15992238e-03, 3.66904499e-03,
       6.62742623e-03, 3.93193260e-03, 1.16162749e-03, 5.40390182e-03,
       5.48134589e-03, 9.27182096e-03, 6.77770552e-03, 2.19348447e-02,
       2.06926939e-02, 4.28517382e-03, 6.40347969e-02, 2.61560963e-02]), 'mean_score_time': array([0.00223169, 0.00243282, 0.00247154, 0.00296493, 0.00291071,
       0.00275536, 0.00567608, 0.0058125 , 0.00689011, 0.00710111,
       0.00797658, 0.0079865 , 0.03155279, 0.03189263, 0.03874869,
       0.03842931, 0.04734683, 0.04734988, 0.00308676, 0.00283079,
       0.00293159, 0.00293431, 0.00287628, 0.00307713, 0.006074  ,
       0.00596848, 0.00734096, 0.00719261, 0.00782576, 0.01524911,
       0.07428417, 0.10582509, 0.13502407, 0.10166426, 0.06853237,
       0.06824112, 0.0026041 , 0.00253081, 0.00291367, 0.00249953,
       0.00267596, 0.00284042, 0.00575533, 0.00632524, 0.00688925,
       0.0070776 , 0.00825634, 0.00846233, 0.03444524, 0.03675289,
       0.04257092, 0.06464896, 0.10434098, 0.14291997, 0.00266604,
       0.00242591, 0.00265479, 0.00292082, 0.00309906, 0.00290384,
       0.00567384, 0.00567842, 0.00707316, 0.00703478, 0.00824714,
       0.00827465, 0.03362813, 0.03451166, 0.04205208, 0.08650017,
       0.1060503 , 0.14482737, 0.00420632, 0.00416965, 0.00468054,
       0.00466733, 0.00574713, 0.00502105, 0.01428332, 0.01493845,
       0.01565313, 0.01541238, 0.01792226, 0.01906657, 0.09286466,
       0.05529232, 0.11026793, 0.11161752, 0.11711297, 0.04368305,
       0.00260324, 0.0027092 , 0.0029357 , 0.00288954, 0.00273499,
       0.00269613, 0.00556707, 0.0056344 , 0.0069025 , 0.00659041,
       0.00788951, 0.00789638, 0.03247452, 0.03168893, 0.12333159,
       0.13031778, 0.19594398, 0.06794081, 0.00277681, 0.00276532,
       0.00283618, 0.00268412, 0.00301957, 0.00303831, 0.00570889,
       0.00588403, 0.00674429, 0.00683122, 0.00805445, 0.00790591,
       0.03195062, 0.03238902, 0.04111433, 0.04095039, 0.05761867,
       0.08302979, 0.00324154, 0.00400305, 0.004286  , 0.00490069,
       0.00452738, 0.0047986 , 0.01355629, 0.01410704, 0.01624827,
       0.01553659, 0.01933637, 0.0190763 , 0.09859462, 0.07092457,
       0.05237155, 0.11251726, 0.12764688, 0.06364293, 0.0025311 ,

ValueError: operands could not be broadcast together with shapes (58534,) (14,)

In [20]:
def lightgbm_one_layer_d(system_id: int, read_path: str, met_or_inv, systems_cleaned: pd.DataFrame, streak_len: int,
                         n_splits_outer: int, sample_spacing: int):
    prerun_system = PreRun(system_id, read_path, met_or_inv, systems_cleaned)
    prerun_system.add_energy_features_only(daily_lags=2, include_last_year=True, include_hour_cyclic=True, include_day_of_year_cyclic=True)
    prerun_system.add_weather_features_only()
    prerun_system.good_end_days_naive(streak=streak_len)
    good_ends = prerun_system.end_days_naive.copy(deep=True)
    df = prerun_system.amended_data.copy(deep=True)
    df['year'] = df['time'].dt.year
    my_cols = ['year', 'hour_sin', 'hour_cos', 'day_of_year_sin', 'day_of_year_cos', 'last_year', '2_days_ago', 'cloud_cover', 'global_tilted_irradiance', 'proportion_daytime']
    df_train = df.iloc[0:int(len(df)*0.8)]
    outer_cv = k_fold_split_option_a(
        df_train=df_train,
        good_ends=good_ends,
        n_splits=n_splits_outer,
        window_size=None,
        front_or_back='back',
        gap_day=True,
        return_type='index',
        sample_spacing=sample_spacing)
    param_grid = {
        'num_leaves': (7, 15, 31),
        'max_depth': (-1, 5, 7),
        'learning_rate': (0.1, 0.2),
        'n_estimators': (100,),  # wanted more, but there is literally no time!
        'subsample': (0.8, 1.0),
        'colsample_bytree': (0.8, 1.0),
    }
    col_names = [str(param_settings) for param_settings in product(
        param_grid['num_leaves'],
        param_grid['max_depth'],
        param_grid['learning_rate'],
        param_grid['n_estimators'],
        param_grid['subsample'],
        param_grid['colsample_bytree'])]
    outer_test_results = pd.DataFrame(
        np.zeros((len(outer_cv), len(col_names))),
        columns=col_names
    )
    for i, (train_ind, test_ind) in enumerate(tqdm(outer_cv)):
        df_tt = df_train.loc[train_ind]
        df_ho = df_train.loc[test_ind]
        X_tt = df_tt[my_cols]
        y_tt = df_tt['energy']
        lgb_tt = lgb.Dataset(data=X_tt, label=y_tt)
        X_ho = df_ho[my_cols]
        y_ho = df_ho['energy']
        lgb_ho = lgb.Dataset(data=X_ho, label=y_ho, reference=lgb_tt)
        for j, param_settings in enumerate(product(param_grid['num_leaves'],
            param_grid['max_depth'],
            param_grid['learning_rate'],
            param_grid['n_estimators'],
            param_grid['subsample'],
            param_grid['colsample_bytree']
        )):
            temp_params = {
                'objective': custom_obj,
                'task': 'train',
                'num_leaves': param_settings[0],
                'max_depth': param_settings[1],
                'learning_rate': param_settings[2],
                'num_iterations': param_settings[3],
                'subsample': param_settings[4],
                'colsample_bytree': param_settings[5],
                'metric': 'custom',
                'verbose': -1
            }
            bst = lgb.train(
                params=temp_params,
                train_set=lgb_tt,
                feval=custom_eval,
                valid_sets=[lgb_ho,]
            )
            y_pred = bst.predict(X_ho)
            val_error = PostRun.custom_error(y_pred,y_ho,1,2)
            outer_test_results.at[i, col_names[j]] = val_error
    outer_test_results.to_csv(f'./testing_many_folds/{system_id}_{met_or_inv}.csv', index=False)
    return outer_test_results

In [ ]:
# full results for System 50 to see which one(s) are best.
early_results_d = lightgbm_one_layer_d(
    50, '../../../../data_ds_project/parquet_cleaned_energy/', None, systems_cleaned, 7, -1, 5
)

 42%|████▏     | 123/294 [28:11<45:18, 15.90s/it]