In [1]:
import numpy as np
import pandas as pd
import pyarrow.parquet as pq
from gen_variable_standard_static import metrics_search_for_two_fragments_df
from clean_and_collect_power_data_alt import Clean
from tqdm import tqdm

In [28]:
system_4_first_results = pq.ParquetDataset(
    './test_results_4_first_instance/other/4'
)
system_4_first_df = system_4_first_results.read().to_pandas()

In [29]:
system_4_second_results = pq.ParquetDataset(
    './test_results_4_second_instance/other/4'
)
system_4_second_df = system_4_second_results.read().to_pandas()

In [30]:
system_4_first_df

                     hour    energy  year
0     2007-09-01 06:00:00  0.032494  2007
1     2007-09-01 07:00:00  0.159633  2007
2     2007-09-01 08:00:00  0.304443  2007
3     2007-09-01 09:00:00  0.265836  2007
4     2007-09-01 10:00:00  0.804245  2007
...                   ...       ...   ...
34818 2023-02-28 13:00:00  0.610406  2023
34819 2023-02-28 14:00:00  0.408742  2023
34820 2023-02-28 15:00:00  0.395145  2023
34821 2023-02-28 16:00:00  0.230329  2023
34822 2023-02-28 17:00:00  0.003725  2023

[34823 rows x 3 columns]

In [31]:
for j in range(2):
    assert(system_4_first_df.shape[j] == system_4_second_df.shape[j])

In [32]:
system_4_first_df.equals(system_4_second_df)

True

In [33]:
from clean_and_collect_power_data_alt import Clean

In [34]:
systems_cleaned = pd.read_csv('../../../data/core/systems_cleaned.csv')
test_path = '../../../../data_ds_project/testing_yearly_parquet/'

In [35]:
test_10 = Clean(10, test_path, systems_cleaned, None, './test_results_10_first/')

In [36]:
my_year = 2016
year_2016_data_basic = test_10.extract_years_data_parquet(my_year)
year_2016_data_standard = test_10.standardize_dataframe(year_2016_data_basic)
year_2016_data_rem = test_10.remove_small_values(year_2016_data_standard)
year_2016_good_days = test_10.keep_good_days_only(year_2016_data_rem)
year_2016_energy_readings = test_10.convert_to_energy_LRS(year_2016_good_days)

In [11]:
year_2016_data_basic.head()

                 time  ac_power_kW  year
0 2016-01-01 00:00:00    -0.001732  2016
1 2016-01-01 00:01:00    -0.001776  2016
2 2016-01-01 00:02:00    -0.001721  2016
3 2016-01-01 00:03:00    -0.001743  2016
4 2016-01-01 00:04:00    -0.001687  2016

In [7]:
year_2016_start_data['has_large_gap'].value_counts(dropna=False)

has_large_gap
True     220
False    135
NaN        1
Name: count, dtype: int64

In [14]:
year_2016_start_nans = year_2016_start_data[year_2016_start_data['has_large_gap'].isna()]

In [15]:
year_2016_start_nans

            num_readings delta_t_mode has_large_gap good_span
date
2016-02-03             1          NaT           NaN       NaN

In [17]:
my_year = 2018
year_2018_data_basic = test_10.extract_years_data_parquet(my_year)
year_2018_data_standard = test_10.standardize_dataframe(year_2018_data_basic)
year_2018_data_rem = test_10.remove_small_values(year_2018_data_standard)
year_2018_start_data = test_10.good_days_prefix(year_2018_data_rem)
year_2018_start_nans = year_2018_start_data[year_2018_start_data['has_large_gap'].isna()]
year_2018_start_nans

         date  num_readings delta_t_mode has_large_gap
0  2018-01-01           531     0.016667         False
1  2018-01-02           528     0.016667         False
2  2018-01-03           532     0.016667         False
3  2018-01-04           532     0.016667          True
4  2018-01-05           516     0.016667         False

            num_readings delta_t_mode has_large_gap good_span
date
2018-12-21             1          NaT           NaN       NaN

In [24]:
from datetime import datetime

In [26]:
year_2018_data_rem[(year_2018_data_rem['time'] >= datetime(2018, 12, 20))
                   & (year_2018_data_rem['time'] < datetime(2018, 12, 23))]

                      time  power
467859 2018-12-20 10:13:00  0.784
467860 2018-12-20 12:28:00  0.854
467861 2018-12-20 13:18:00  0.802
467862 2018-12-20 13:39:00  0.778
467863 2018-12-20 14:02:00  0.723
467864 2018-12-21 10:20:00  0.816
467865 2018-12-22 07:49:00  0.192
467866 2018-12-22 11:29:00  0.162
467867 2018-12-22 12:10:00  0.609
467868 2018-12-22 12:36:00  1.032
467869 2018-12-22 12:54:00  0.178
467870 2018-12-22 14:45:00  0.192

In [21]:
year_2018_start_data.iloc[-12:-8]

            num_readings delta_t_mode has_large_gap good_span
date
2018-12-19             4     0.266667          True     False
2018-12-20             5         0.35          True     False
2018-12-21             1          NaT           NaN       NaN
2018-12-22             6          0.3          True      True

In [18]:
my_year = 2017
year_2017_data_basic = test_10.extract_years_data_parquet(my_year)
year_2017_data_standard = test_10.standardize_dataframe(year_2017_data_basic)
year_2017_data_rem = test_10.remove_small_values(year_2017_data_standard)
year_2017_start_data = test_10.good_days_prefix(year_2017_data_rem)
year_2017_start_nans = year_2017_start_data[year_2017_start_data['has_large_gap'].isna()]
year_2017_start_nans

         date  num_readings  delta_t_mode  has_large_gap
0  2017-01-01           526      0.016667          False
1  2017-01-02           529      0.016667          False
2  2017-01-03           489      0.016667           True
3  2017-01-04           181      0.016667           True
4  2017-01-06           344      0.016667           True

Empty DataFrame
Columns: [num_readings, delta_t_mode, has_large_gap, good_span]
Index: []