In [2]:
from PreRun import PreRun, PostRun
import pandas as pd
import numpy as np
import pyarrow.parquet as pq
import xgboost as xgb
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import make_scorer
from itertools import product
from datetime import date, datetime
from by_dates_Kfold import k_fold_split_option_a
from tqdm import tqdm
from sklearn.model_selection import GridSearchCV

In [3]:
systems_cleaned = pd.read_csv('../../../data/core/systems_cleaned.csv')

In [53]:
best_systems = [10, 50, 51]
systems_cleaned[systems_cleaned['system_id'].isin(best_systems)]

,system_id,system_public_name,site_location,timezone_or_utc_offset,latitude,longitude,elevation_m,dc_capacity_kW,kg_climate,pvcz_composite,...,has_power_data,has_current_data,has_voltage_data,has_ac_data,has_dc_data,module_type,simplified_type,system_source,num_days_actual_records,sample_year
3,10,NREL CIS -1,"Golden, CO",7,39.7404,-105.1774,1792.8,1.12,BSk,12,...,True,True,True,True,True,cis family thin-film,thin_film,PVDAQ General,5893,2007
8,50,NREL x-Si 6,"Golden, CO",7,39.7420,-105.1727,1994.7,6.00,BSk,12,...,True,True,True,True,True,Unknown,unknown,PVDAQ General,8455,1995
9,51,NREL x-Si 7,"Golden, CO",7,39.7416,-105.1734,1994.7,6.00,BSk,12,...,True,True,True,True,True,Unknown,unknown,PVDAQ General,8032,1995

In [4]:
name_val = (('inverter', 'inverter'), ('meter', 'meter'), ('other', 'None'))
names_list = ('inverter', 'meter', 'other')
# 1332 dropped!
systems_good_timezones_manual_edit = [4, 10, 33, 36, 50, 51, 1199, 1204, 1283, 1284, 1289, 4902, 4903]

In [5]:
def custom_xgb_obj(preds: np.ndarray, eval_data: xgb.DMatrix):
    y_true = eval_data.get_label()
    # first derivative is (2x) * [0.5 signum(x) + 1.5]
    multiplier = 1.5 + 0.5 * np.sign(preds - y_true)
    grad = 2 * (preds - y_true) * multiplier
    hess = 2 * multiplier * np.ones_like(preds)
    return (grad, hess)


def custom_xgb_eval(preds: np.ndarray, eval_data: xgb.DMatrix):
    y_true = eval_data.get_label()
    metric_name = 'weight_over'
    value = PostRun.custom_error(y_true, preds,a=1,b=2)
    is_higher_better = False
    return (metric_name, value,)

In [ ]:
params_b = {
    'objective': custom_obj,
    'task': 'train',
    'num_leaves': 10,
    'learning_rate': 0.1,
    'max_depth': 10,
    'num_iterations': 1000,
    'metric': 'custom',
    'verbose': -1
}

In [6]:
starter_kit = PreRun(50, './test_results/50-None', None, systems_cleaned)
starter_kit.add_energy_features_only(daily_lags=2, include_last_year=True, include_hour_cyclic=True, include_day_of_year_cyclic=True)
starter_kit.add_weather_features_only()
starter_kit.good_end_days_naive(streak=7)
good_ends = starter_kit.end_days_naive.copy(deep=True)
df = starter_kit.amended_data.copy(deep=True)
df['year'] = df['time'].dt.year
my_cols = ['year', 'hour_sin', 'hour_cos', 'day_of_year_sin', 'day_of_year_cos', 'last_year', '2_days_ago', 'cloud_cover', 'global_tilted_irradiance', 'proportion_daytime']
df_train = df.iloc[0:int(len(df)*0.8)]
outer_cv = k_fold_split_option_a(
    df_train=df_train,
    good_ends=good_ends,
    n_splits=1,
    window_size=None,
    front_or_back='back',
    gap_day=True,
    return_type='index'
)
last_train, last_test = outer_cv[0]

In [7]:
X_tt = df_train[my_cols]
y_tt = df_train['energy']
X_test = df_train[my_cols]
y_test = df_train['energy']
xgb_last_tt = xgb.DMatrix(data=X_tt,label=y_tt)
xgb_last_ho = xgb.DMatrix(data=X_test,label=y_test)

In [16]:
X_tt.tail()

,year,hour_sin,hour_cos,day_of_year_sin,day_of_year_cos,last_year,2_days_ago,cloud_cover,global_tilted_irradiance,proportion_daytime
58529,2018,1.000000,6.123234e-17,0.628763,-0.777597,1.308301,1.175016,0.00,84.239639,1.0
58530,2018,0.965926,-2.588190e-01,0.628763,-0.777597,2.715960,2.330695,0.00,293.458344,1.0
58531,2018,0.866025,-5.000000e-01,0.628763,-0.777597,3.688462,3.325220,0.00,523.726440,1.0
58532,2018,0.707107,-7.071068e-01,0.628763,-0.777597,4.426120,3.967925,0.32,714.760376,1.0
58533,2018,0.500000,-8.660254e-01,0.628763,-0.777597,4.637175,4.241940,0.22,855.164673,1.0

In [11]:
xgb_last_tt

In [17]:
params_b = {
    'objective': custom_xgb_obj,
    'num_leaves': 31,
    'eta': 0.1,
    'max_depth': 5,
    'num_iterations': 1000,
    'metric': 'custom',
    'verbosity': 0,
    'subsample': 0.8,
    'eval_metric': custom_xgb_eval,
}

In [ ]:
bst_a = xgb.train(params=params_b, dtrain=xgb_last_tt, num_boost_round=100, evals = [xgb_last_ho,], obj=custom_xgb_obj, maximize=False)

TypeError: cannot unpack non-iterable DMatrix object

## Try scikit-learn variant.

In [27]:
def custom_xgb_reg_obj(y_true: np.ndarray, preds: np.ndarray):
    # first derivative is (2x) * [0.5 signum(x) + 1.5]
    multiplier = 1.5 + 0.5 * np.sign(preds - y_true)
    grad = 2 * (preds - y_true) * multiplier
    hess = 2 * multiplier * np.ones_like(preds)
    return (grad, hess)


def custom_xgb_reg_eval(y_true: np.ndarray, preds: np.ndarray):
    metric_name = 'weight_over'
    value = PostRun.custom_error(y_true, preds,a=1,b=2)
    return value

In [28]:
try_again = xgb.XGBRegressor(n_estimators=100, max_depth=5, max_leaves=31, learning_rate=0.1,
                             objective=custom_xgb_reg_obj, eval_metric = custom_xgb_reg_eval)
try_again.fit(X_tt.values, y_tt, eval_set=[(X_test.values, y_test),])

[0]	validation_0-rmse:2.44360	validation_0-custom_xgb_reg_eval:6.01150
[1]	validation_0-rmse:2.24063	validation_0-custom_xgb_reg_eval:5.06068
[2]	validation_0-rmse:2.06270	validation_0-custom_xgb_reg_eval:4.29778
[3]	validation_0-rmse:1.90650	validation_0-custom_xgb_reg_eval:3.68274
[4]	validation_0-rmse:1.76918	validation_0-custom_xgb_reg_eval:3.18494
[5]	validation_0-rmse:1.65030	validation_0-custom_xgb_reg_eval:2.78674
[6]	validation_0-rmse:1.54581	validation_0-custom_xgb_reg_eval:2.46263
[7]	validation_0-rmse:1.45438	validation_0-custom_xgb_reg_eval:2.19916
[8]	validation_0-rmse:1.37544	validation_0-custom_xgb_reg_eval:1.98678
[9]	validation_0-rmse:1.30694	validation_0-custom_xgb_reg_eval:1.81426
[10]	validation_0-rmse:1.24645	validation_0-custom_xgb_reg_eval:1.67106
[11]	validation_0-rmse:1.19417	validation_0-custom_xgb_reg_eval:1.55432
[12]	validation_0-rmse:1.14906	validation_0-custom_xgb_reg_eval:1.45927
[13]	validation_0-rmse:1.10996	validation_0-custom_xgb_reg_eval:1.38132
[14]	validation_0-rmse:1.07667	validation_0-custom_xgb_reg_eval:1.31826
[15]	validation_0-rmse:1.04764	validation_0-custom_xgb_reg_eval:1.26603
[16]	validation_0-rmse:1.02278	validation_0-custom_xgb_reg_eval:1.22332
[17]	validation_0-rmse:0.99938	validation_0-custom_xgb_reg_eval:1.18367
[18]	validation_0-rmse:0.97953	validation_0-custom_xgb_reg_eval:1.15191
[19]	validation_0-rmse:0.96157	validation_0-custom_xgb_reg_eval:1.12391
[20]	validation_0-rmse:0.94432	validation_0-custom_xgb_reg_eval:1.09451
[21]	validation_0-rmse:0.92971	validation_0-custom_xgb_reg_eval:1.07072
[22]	validation_0-rmse:0.91826	validation_0-custom_xgb_reg_eval:1.05488
[23]	validation_0-rmse:0.90871	validation_0-custom_xgb_reg_eval:1.04174
[24]	validation_0-rmse:0.89972	validation_0-custom_xgb_reg_eval:1.02930
[25]	validation_0-rmse:0.89132	validation_0-custom_xgb_reg_eval:1.01814
[26]	validation_0-rmse:0.88483	validation_0-custom_xgb_reg_eval:1.01002
[27]	validation_0-rmse:0.87911	validation_0-custom_xgb_reg_eval:1.00298
[28]	validation_0-rmse:0.87373	validation_0-custom_xgb_reg_eval:0.99618
[29]	validation_0-rmse:0.86835	validation_0-custom_xgb_reg_eval:0.98961
[30]	validation_0-rmse:0.86446	validation_0-custom_xgb_reg_eval:0.98523
[31]	validation_0-rmse:0.86090	validation_0-custom_xgb_reg_eval:0.98114
[32]	validation_0-rmse:0.85665	validation_0-custom_xgb_reg_eval:0.97491
[33]	validation_0-rmse:0.85362	validation_0-custom_xgb_reg_eval:0.97151
[34]	validation_0-rmse:0.85066	validation_0-custom_xgb_reg_eval:0.96723
[35]	validation_0-rmse:0.84851	validation_0-custom_xgb_reg_eval:0.96453
[36]	validation_0-rmse:0.84570	validation_0-custom_xgb_reg_eval:0.96044
[37]	validation_0-rmse:0.84348	validation_0-custom_xgb_reg_eval:0.95773
[38]	validation_0-rmse:0.84142	validation_0-custom_xgb_reg_eval:0.95469
[39]	validation_0-rmse:0.83951	validation_0-custom_xgb_reg_eval:0.95217
[40]	validation_0-rmse:0.83692	validation_0-custom_xgb_reg_eval:0.94779
[41]	validation_0-rmse:0.83526	validation_0-custom_xgb_reg_eval:0.94588
[42]	validation_0-rmse:0.83353	validation_0-custom_xgb_reg_eval:0.94323
[43]	validation_0-rmse:0.83186	validation_0-custom_xgb_reg_eval:0.94112
[44]	validation_0-rmse:0.82861	validation_0-custom_xgb_reg_eval:0.93407
[45]	validation_0-rmse:0.82748	validation_0-custom_xgb_reg_eval:0.93217
[46]	validation_0-rmse:0.82648	validation_0-custom_xgb_reg_eval:0.93101
[47]	validation_0-rmse:0.82483	validation_0-custom_xgb_reg_eval:0.92806
[48]	validation_0-rmse:0.82330	validation_0-custom_xgb_reg_eval:0.92526
[49]	validation_0-rmse:0.82253	validation_0-custom_xgb_reg_eval:0.92376
[50]	validation_0-rmse:0.82170	validation_0-custom_xgb_reg_eval:0.92255
[51]	validation_0-rmse:0.82079	validation_0-custom_xgb_reg_eval:0.92086
[52]	validation_0-rmse:0.81968	validation_0-custom_xgb_reg_eval:0.91906
[53]	validation_0-rmse:0.81924	validation_0-custom_xgb_reg_eval:0.91812
[54]	validation_0-rmse:0.81849	validation_0-custom_xgb_reg_eval:0.91656
[55]	validation_0-rmse:0.81774	validation_0-custom_xgb_reg_eval:0.91541
[56]	validation_0-rmse:0.81658	validation_0-custom_xgb_reg_eval:0.91288
[57]	validation_0-rmse:0.81615	validation_0-custom_xgb_reg_eval:0.91222
[58]	validation_0-rmse:0.81571	validation_0-custom_xgb_reg_eval:0.91153
[59]	validation_0-rmse:0.81497	validation_0-custom_xgb_reg_eval:0.90984
[60]	validation_0-rmse:0.81445	validation_0-custom_xgb_reg_eval:0.90883
[61]	validation_0-rmse:0.81349	validation_0-custom_xgb_reg_eval:0.90705
[62]	validation_0-rmse:0.81243	validation_0-custom_xgb_reg_eval:0.90473
[63]	validation_0-rmse:0.81180	validation_0-custom_xgb_reg_eval:0.90341
[64]	validation_0-rmse:0.81132	validation_0-custom_xgb_reg_eval:0.90228
[65]	validation_0-rmse:0.81100	validation_0-custom_xgb_reg_eval:0.90171
[66]	validation_0-rmse:0.81005	validation_0-custom_xgb_reg_eval:0.89976
[67]	validation_0-rmse:0.80836	validation_0-custom_xgb_reg_eval:0.89574
[68]	validation_0-rmse:0.80795	validation_0-custom_xgb_reg_eval:0.89503
[69]	validation_0-rmse:0.80652	validation_0-custom_xgb_reg_eval:0.89168
[70]	validation_0-rmse:0.80608	validation_0-custom_xgb_reg_eval:0.89063
[71]	validation_0-rmse:0.80576	validation_0-custom_xgb_reg_eval:0.88997
[72]	validation_0-rmse:0.80528	validation_0-custom_xgb_reg_eval:0.88911
[73]	validation_0-rmse:0.80393	validation_0-custom_xgb_reg_eval:0.88602
[74]	validation_0-rmse:0.80366	validation_0-custom_xgb_reg_eval:0.88523
[75]	validation_0-rmse:0.80312	validation_0-custom_xgb_reg_eval:0.88421
[76]	validation_0-rmse:0.80202	validation_0-custom_xgb_reg_eval:0.88175
[77]	validation_0-rmse:0.80136	validation_0-custom_xgb_reg_eval:0.88037
[78]	validation_0-rmse:0.80105	validation_0-custom_xgb_reg_eval:0.87964
[79]	validation_0-rmse:0.80037	validation_0-custom_xgb_reg_eval:0.87803
[80]	validation_0-rmse:0.79983	validation_0-custom_xgb_reg_eval:0.87698
[81]	validation_0-rmse:0.79951	validation_0-custom_xgb_reg_eval:0.87622
[82]	validation_0-rmse:0.79899	validation_0-custom_xgb_reg_eval:0.87485
[83]	validation_0-rmse:0.79863	validation_0-custom_xgb_reg_eval:0.87414
[84]	validation_0-rmse:0.79802	validation_0-custom_xgb_reg_eval:0.87283
[85]	validation_0-rmse:0.79752	validation_0-custom_xgb_reg_eval:0.87140
[86]	validation_0-rmse:0.79709	validation_0-custom_xgb_reg_eval:0.87062
[87]	validation_0-rmse:0.79650	validation_0-custom_xgb_reg_eval:0.86929
[88]	validation_0-rmse:0.79575	validation_0-custom_xgb_reg_eval:0.86759
[89]	validation_0-rmse:0.79538	validation_0-custom_xgb_reg_eval:0.86659
[90]	validation_0-rmse:0.79504	validation_0-custom_xgb_reg_eval:0.86598
[91]	validation_0-rmse:0.79454	validation_0-custom_xgb_reg_eval:0.86478
[92]	validation_0-rmse:0.79400	validation_0-custom_xgb_reg_eval:0.86364
[93]	validation_0-rmse:0.79366	validation_0-custom_xgb_reg_eval:0.86277
[94]	validation_0-rmse:0.79315	validation_0-custom_xgb_reg_eval:0.86180
[95]	validation_0-rmse:0.79253	validation_0-custom_xgb_reg_eval:0.86083
[96]	validation_0-rmse:0.79210	validation_0-custom_xgb_reg_eval:0.85988
[97]	validation_0-rmse:0.79168	validation_0-custom_xgb_reg_eval:0.85889
[98]	validation_0-rmse:0.79124	validation_0-custom_xgb_reg_eval:0.85812
[99]	validation_0-rmse:0.79038	validation_0-custom_xgb_reg_eval:0.85630

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False,
             eval_metric=<function custom_xgb_reg_eval at 0x00000263D21420C0>,
             feature_types=None, feature_weights=None, gamma=None,
             grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=5, max_leaves=31,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=100, n_jobs=None,
             num_parallel_tree=None, ...)

In [21]:
PostRun.custom_error(y_test, y_pred)

np.float64(0.8562987292718526)

In [22]:
config = try_again.best_iteration
print(config)

AttributeError: `best_iteration` is only defined when early stopping is used.

In [39]:
def xgb_one_layer_d(system_id: int, read_path: str, met_or_inv, systems_cleaned: pd.DataFrame, streak_len: int,
                    n_splits_outer: int, sample_spacing: int):
    prerun_system = PreRun(system_id, read_path, met_or_inv, systems_cleaned)
    prerun_system.add_energy_features_only(daily_lags=2, include_last_year=True, include_hour_cyclic=True, include_day_of_year_cyclic=True)
    prerun_system.add_weather_features_only()
    prerun_system.good_end_days_naive(streak=streak_len)
    good_ends = prerun_system.end_days_naive.copy(deep=True)
    df = prerun_system.amended_data.copy(deep=True)
    df['year'] = df['time'].dt.year
    my_cols = ['year', 'hour_sin', 'hour_cos', 'day_of_year_sin', 'day_of_year_cos', 'last_year', '2_days_ago', 'cloud_cover', 'global_tilted_irradiance', 'proportion_daytime']
    df_train = df.iloc[0:int(len(df)*0.8)]
    outer_cv = k_fold_split_option_a(
        df_train=df_train,
        good_ends=good_ends,
        n_splits=n_splits_outer,
        window_size=None,
        front_or_back='back',
        gap_day=True,
        return_type='index',
        sample_spacing=sample_spacing)
    param_grid = {
        'num_leaves': (7, 15, 31),
        'max_depth': (5, 7, 10),
        'learning_rate': (0.1, 0.2),
        'subsample': (0.8, 1.0),
        'colsample_bytree': (0.8, 1.0),
    }
    col_names = [str(param_settings) for param_settings in product(
        param_grid['num_leaves'],
        param_grid['max_depth'],
        param_grid['learning_rate'],
        param_grid['subsample'],
        param_grid['colsample_bytree'])]
    outer_test_results = pd.DataFrame(
        np.zeros((len(outer_cv), len(col_names))),
        columns=col_names
    )
    for i, (train_ind, test_ind) in enumerate(tqdm(outer_cv)):
        df_tt = df_train.loc[train_ind]
        df_ho = df_train.loc[test_ind]
        X_tt = df_tt[my_cols]
        y_tt = df_tt['energy']
        X_ho = df_ho[my_cols]
        y_ho = df_ho['energy']
        for j, param_settings in enumerate(product(param_grid['num_leaves'],
            param_grid['max_depth'],
            param_grid['learning_rate'],
            param_grid['subsample'],
            param_grid['colsample_bytree']
        )):
            xgb_reg = xgb.XGBRegressor(
                n_estimators=100,
                max_depth=param_settings[1],
                max_leaves=param_settings[0],
                learning_rate=param_settings[2],
                subsample=param_settings[3],
                colsample_bytree=param_settings[4],
                objective=custom_xgb_reg_obj,
                eval_metric=custom_xgb_reg_eval,
                verbosity=0,
            )
            xgb_reg.fit(X_tt, y_tt)
            y_pred = xgb_reg.predict(X_ho)
            val_error = PostRun.custom_error(y_pred,y_ho,1,2)
            outer_test_results.at[i, col_names[j]] = val_error
    outer_test_results.to_csv(f'./xgboost_results/{system_id}_{met_or_inv}.csv', index=False)
    return outer_test_results

In [40]:
early_results_50_n = xgb_one_layer_d(
    50, '../../../../data_ds_project/parquet_cleaned_energy/', None, systems_cleaned, 7, -1, 5
)

100%|██████████| 294/294 [1:42:05<00:00, 20.84s/it]

In [41]:
early_results_51_n = xgb_one_layer_d(
    51, '../../../../data_ds_project/parquet_cleaned_energy/', None, systems_cleaned, 7, -1, 5
)

100%|██████████| 258/258 [1:27:08<00:00, 20.27s/it]

In [ ]:
xgb_results_10_n = xgb_one_layer_d(
    10, '../../../../data_ds_project/parquet_cleaned_energy/', None, systems_cleaned, 7, -1, 2
)

In [42]:
early_results_51_n.mean(axis=1)

0      1.949127
1      1.109273
2      0.347301
3      0.493588
4      2.077863
         ...
253    4.011964
254    2.603594
255    1.952726
256    0.201424
257    1.134723
Length: 258, dtype: float64

In [44]:
per_sys_means = early_results_51_n.mean(axis=0)

In [48]:
per_sys_means.name = 'mean'

In [49]:
per_sys_stdev = early_results_51_n.std(axis=0)
per_sys_stdev.name = 'std'

In [50]:
total = pd.merge(per_sys_means, per_sys_stdev, how = 'inner', left_index=True, right_index=True)

In [51]:
total

                             mean       std
(7, 5, 0.1, 0.8, 0.8)    1.173673  1.035820
(7, 5, 0.1, 0.8, 1.0)    1.176234  1.058969
(7, 5, 0.1, 1.0, 0.8)    1.177997  1.038767
(7, 5, 0.1, 1.0, 1.0)    1.183578  1.069728
(7, 5, 0.2, 0.8, 0.8)    1.196735  1.131202
...                           ...       ...
(31, 10, 0.1, 1.0, 1.0)  1.096101  1.040104
(31, 10, 0.2, 0.8, 0.8)  1.163299  1.142018
(31, 10, 0.2, 0.8, 1.0)  1.174024  1.172401
(31, 10, 0.2, 1.0, 0.8)  1.181832  1.259740
(31, 10, 0.2, 1.0, 1.0)  1.203905  1.230200

[72 rows x 2 columns]

In [52]:
total.describe()

            mean        std
count  72.000000  72.000000
mean    1.155438   1.096823
std     0.031226   0.055731
min     1.086789   1.011577
25%     1.136545   1.049822
50%     1.163299   1.093613
75%     1.177997   1.128639
max     1.205494   1.259740

In [ ]:
total['z'] =