In [ ]:
import openmeteo_requests

import pandas as pd
import requests_cache
from retry_requests import retry

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://historical-forecast-api.open-meteo.com/v1/forecast"
params = {
	"latitude": 52.52,
	"longitude": 13.41,
	"start_date": "2026-03-03",
	"end_date": "2026-03-17",
	"daily": ["sunshine_duration", "uv_index_max", "precipitation_sum", "shortwave_radiation_sum", "precipitation_hours", "daylight_duration"],
}
responses = openmeteo.weather_api(url, params=params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation: {response.Elevation()} m asl")
print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")

# Process daily data. The order of variables needs to be the same as requested.
daily = response.Daily()
daily_sunshine_duration = daily.Variables(0).ValuesAsNumpy()
daily_uv_index_max = daily.Variables(1).ValuesAsNumpy()
daily_precipitation_sum = daily.Variables(2).ValuesAsNumpy()
daily_shortwave_radiation_sum = daily.Variables(3).ValuesAsNumpy()
daily_precipitation_hours = daily.Variables(4).ValuesAsNumpy()
daily_daylight_duration = daily.Variables(5).ValuesAsNumpy()

daily_data = {"date": pd.date_range(
	start = pd.to_datetime(daily.Time(), unit = "s", utc = True),
	end =  pd.to_datetime(daily.TimeEnd(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = daily.Interval()),
	inclusive = "left"
)}

daily_data["sunshine_duration"] = daily_sunshine_duration
daily_data["uv_index_max"] = daily_uv_index_max
daily_data["precipitation_sum"] = daily_precipitation_sum
daily_data["shortwave_radiation_sum"] = daily_shortwave_radiation_sum
daily_data["precipitation_hours"] = daily_precipitation_hours
daily_data["daylight_duration"] = daily_daylight_duration

daily_dataframe = pd.DataFrame(data = daily_data)
print("\nDaily data\n", daily_dataframe)

Coordinates: 52.52000045776367°N 13.419998168945312°E
Elevation: 38.0 m asl
Timezone difference to GMT+0: 0s

Daily data
                         date  sunshine_duration  uv_index_max  \
0  2026-03-03 00:00:00+00:00       36116.992188          3.00
1  2026-03-04 00:00:00+00:00       36648.988281          3.05
2  2026-03-05 00:00:00+00:00       37169.648438          3.10
3  2026-03-06 00:00:00+00:00       37724.722656          3.10
4  2026-03-07 00:00:00+00:00       38146.398438          3.20
5  2026-03-08 00:00:00+00:00       29673.822266          2.60
6  2026-03-09 00:00:00+00:00       35589.632812          3.30
7  2026-03-10 00:00:00+00:00       36812.406250          3.25
8  2026-03-11 00:00:00+00:00       28704.113281          3.40
9  2026-03-12 00:00:00+00:00       38070.207031          3.50
10 2026-03-13 00:00:00+00:00       36000.000000          3.65
11 2026-03-14 00:00:00+00:00        9956.092773          2.95
12 2026-03-15 00:00:00+00:00        2079.533203          1.85
13 2026-03-16 00:00:00+00:00        9189.165039          2.10
14 2026-03-17 00:00:00+00:00       39600.000000          3.70

    precipitation_sum  shortwave_radiation_sum  precipitation_hours  \
0                 0.0                    10.84                  0.0
1                 0.0                    11.24                  0.0
2                 0.0                    11.59                  0.0
3                 0.0                    11.72                  0.0
4                 0.0                    11.71                  0.0
5                 0.0                    10.27                  0.0
6                 0.0                    11.00                  0.0
7                 0.0                    11.42                  0.0
8                 1.0                    11.02                  5.0
9                 0.0                    11.98                  0.0
10                0.0                    12.92                  0.0
11                1.5                     7.39                  7.0
12                1.2                     4.83                  2.0
13                2.6                     5.27                  5.0
14                0.0                    13.85                  0.0

    daylight_duration
0        39629.125000
1        39871.148438
2        40114.656250
3        40359.492188
4        40605.476562
5        40852.445312
6        41100.242188
7        41348.703125
8        41597.675781
9        41847.000000
10       42096.519531
11       42346.085938
12       42595.546875
13       42844.742188
14       43093.531250

In [2]:
import pandas as pd
site_info="C:\\Users\\Alex\\Desktop\\DataScience\\Solar\\spring-2026-solar-panel-degradation-team-2\\data\\core\\systems_cleaned.csv"

In [3]:
data=pd.read_csv(site_info)

In [16]:
my_sites=[2105, 2107, 7333, 9068]

In [24]:
data[data['system_id'].isin(my_sites)]

,system_id,system_public_name,site_location,timezone_or_utc_offset,latitude,longitude,elevation_m,dc_capacity_kW,kg_climate,pvcz_composite,...,has_temperature_data,has_power_data,has_current_data,has_voltage_data,has_ac_data,has_dc_data,module_type,simplified_type,system_source,num_days_actual_records
154,2105,Maui Ocean Center,"Maui, HI",10,20.792530,-156.512000,10.0,110.0,Cfb,36,...,True,True,False,True,True,True,mono-Si,monocrystalline_Si,Prize,0
155,2107,Farm Solar Array,"Arbuckle, CA",PST8PDT,38.996306,-122.134111,10.0,893.0,Csa,33,...,True,True,True,True,True,True,mono-Si,monocrystalline_Si,Prize,0
160,7333,Shine On Solar Facility - 10sec,"Levis, CA",8,36.578000,-120.401600,330.1,205300.0,Bsk,34,...,True,True,True,True,True,True,multi-Si,multicrystalline_Si,Prize,0
161,9068,SR_CO,"Kersey, CO",7,40.386400,-104.551200,1407.0,4738.0,Bsk,12,...,True,True,True,True,True,True,CdTe,thin_film,Prize,0

In [ ]:
data[data['system_source'] == "Prize"]

,system_id,system_public_name,site_location,timezone_or_utc_offset,latitude,longitude,elevation_m,dc_capacity_kW,kg_climate,pvcz_composite,...,has_temperature_data,has_power_data,has_current_data,has_voltage_data,has_ac_data,has_dc_data,module_type,simplified_type,system_source,num_days_actual_records
154,2105,Maui Ocean Center,"Maui, HI",10,20.792530,-156.512000,10.0,110.0,Cfb,36,...,True,True,False,True,True,True,mono-Si,monocrystalline_Si,Prize,0
155,2107,Farm Solar Array,"Arbuckle, CA",PST8PDT,38.996306,-122.134111,10.0,893.0,Csa,33,...,True,True,True,True,True,True,mono-Si,monocrystalline_Si,Prize,0
160,7333,Shine On Solar Facility - 10sec,"Levis, CA",8,36.578000,-120.401600,330.1,205300.0,Bsk,34,...,True,True,True,True,True,True,multi-Si,multicrystalline_Si,Prize,0
161,9068,SR_CO,"Kersey, CO",7,40.386400,-104.551200,1407.0,4738.0,Bsk,12,...,True,True,True,True,True,True,CdTe,thin_film,Prize,0
162,9069,Simon Solar Farm,"Social Circle, GA",5,33.676200,-83.676000,330.1,33000.0,Cfa,35,...,True,True,True,True,True,True,multi-Si,multicrystalline_Si,Prize,0

In [49]:
data[data['system_id']==2105]['longitude'].item()

-156.512

In [ ]:
import openmeteo_requests

import pandas as pd
import requests_cache
from retry_requests import retry

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://historical-forecast-api.open-meteo.com/v1/forecast"
params = {
	"latitude": data[data['system_id']==2107]['latitude'].item(),
	"longitude": data[data['system_id']==2107]['longitude'].item(),
	"start_date": "2018-12-15",
	"end_date": "2023-11-09",
	"daily": ["sunshine_duration", "uv_index_max", "precipitation_sum", "shortwave_radiation_sum", "precipitation_hours", "daylight_duration"],
	"timezone": "auto",
}
responses = openmeteo.weather_api(url, params=params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation: {response.Elevation()} m asl")
print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")

# Process daily data. The order of variables needs to be the same as requested.
daily = response.Daily()
daily_sunshine_duration = daily.Variables(0).ValuesAsNumpy()
daily_uv_index_max = daily.Variables(1).ValuesAsNumpy()
daily_precipitation_sum = daily.Variables(2).ValuesAsNumpy()
daily_shortwave_radiation_sum = daily.Variables(3).ValuesAsNumpy()
daily_precipitation_hours = daily.Variables(4).ValuesAsNumpy()
daily_daylight_duration = daily.Variables(5).ValuesAsNumpy()

daily_data = {"date": pd.date_range(
	start = pd.to_datetime(daily.Time(), unit = "s", utc = True),
	end =  pd.to_datetime(daily.TimeEnd(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = daily.Interval()),
	inclusive = "left"
)}

daily_data["sunshine_duration"] = daily_sunshine_duration
daily_data["uv_index_max"] = daily_uv_index_max
daily_data["precipitation_sum"] = daily_precipitation_sum
daily_data["shortwave_radiation_sum"] = daily_shortwave_radiation_sum
daily_data["precipitation_hours"] = daily_precipitation_hours
daily_data["daylight_duration"] = daily_daylight_duration

daily_dataframe = pd.DataFrame(data = daily_data)
print("\nDaily data\n", daily_dataframe)

Coordinates: 38.99906921386719°N -122.13370513916016°E
Elevation: 110.0 m asl
Timezone difference to GMT+0: 0s

Daily data
                           date  sunshine_duration  uv_index_max  \
0    2018-12-15 00:00:00+00:00        3656.925049           NaN
1    2018-12-16 00:00:00+00:00        2066.758301           NaN
2    2018-12-17 00:00:00+00:00       27209.916016           NaN
3    2018-12-18 00:00:00+00:00       29211.679688           NaN
4    2018-12-19 00:00:00+00:00       29930.531250           NaN
...                        ...                ...           ...
1786 2023-11-05 00:00:00+00:00        7200.000000          3.30
1787 2023-11-06 00:00:00+00:00       29465.570312          4.00
1788 2023-11-07 00:00:00+00:00       35876.496094          3.85
1789 2023-11-08 00:00:00+00:00       35814.898438          3.80
1790 2023-11-09 00:00:00+00:00       35755.039062          3.35

      precipitation_sum  shortwave_radiation_sum  precipitation_hours  \
0                   0.0                     4.91                  0.0
1                   1.4                     5.04                  1.0
2                   4.4                     9.07                  5.0
3                   0.0                     8.93                  0.0
4                   0.0                     9.32                  0.0
...                 ...                      ...                  ...
1786                0.0                     5.61                  0.0
1787                0.2                    10.76                  1.0
1788                0.0                    12.58                  0.0
1789                0.0                    13.27                  0.0
1790                0.0                    12.53                  0.0

      daylight_duration
0          34017.707031
1          33995.839844
2          33977.539062
3          33962.812500
4          33951.683594
...                 ...
1786       37438.656250
1787       37308.554688
1788       37180.062500
1789       37053.335938
1790       36928.535156

[1791 rows x 7 columns]

In [76]:
test_frame=daily_dataframe.copy()

In [ ]:
def date_change(row):
    date = row['date']
    old_string=str(date).split(" ")[0].split("-")
    my_string=f"{old_string[1]}/{old_string[2]}/{old_string[0][-2:]}"
    return my_string
test_frame['new_date']=test_frame.apply(date_change, axis=1)

In [ ]:
my_string=str(daily_dataframe.iloc[20]['date']).split(" ")[0].split("-")
new_string=f"{my_string[1]}/{my_string[2]}/{my_string[0][-2:]}"

01/04/19

In [108]:
test_frame_2=test_frame.copy()
test_frame_2['date']=test_frame_2['new_date']
test_frame_2.drop('new_date', axis=1, inplace=True)

,sunshine_duration,uv_index_max,precipitation_sum,shortwave_radiation_sum,precipitation_hours,daylight_duration
count,1791.000000,962.000000,1791.000000,1791.000000,1791.000000,1791.000000
mean,35875.957031,5.920166,0.839866,19.946466,0.476829,44082.511719
std,12567.610352,2.117119,4.403731,8.425050,1.915941,6738.475586
min,0.000000,0.200000,0.000000,1.150000,0.000000,33933.898438
25%,30682.626953,4.100000,0.000000,12.375000,0.000000,37685.550781
50%,38363.679688,6.600000,0.000000,20.240000,0.000000,44263.515625
75%,45364.363281,7.850000,0.000000,28.000000,0.000000,50617.900391
max,50400.000000,8.400000,77.899994,33.310001,24.000000,53664.945312

In [118]:
test_frame_2.to_csv("C:\\Users\\Alex\\Desktop\\DataScience\\Solar\\spring-2026-solar-panel-degradation-team-2\\notebooks\\eda\\AM\\weather_CSVs\\2107_weather.csv", index=False)

In [119]:
to_read=pd.read_csv("C:\\Users\\Alex\\Desktop\\DataScience\\Solar\\spring-2026-solar-panel-degradation-team-2\\notebooks\\eda\\AM\\weather_CSVs\\2107_weather.csv")

In [120]:
to_read

,date,sunshine_duration,uv_index_max,precipitation_sum,shortwave_radiation_sum,precipitation_hours,daylight_duration
0,12/15/18,3656.9250,NaN,0.0,4.91,0.0,34017.707
1,12/16/18,2066.7583,NaN,1.4,5.04,1.0,33995.840
2,12/17/18,27209.9160,NaN,4.4,9.07,5.0,33977.540
3,12/18/18,29211.6800,NaN,0.0,8.93,0.0,33962.812
4,12/19/18,29930.5310,NaN,0.0,9.32,0.0,33951.684
...,...,...,...,...,...,...,...
1786,11/05/23,7200.0000,3.30,0.0,5.61,0.0,37438.656
1787,11/06/23,29465.5700,4.00,0.2,10.76,1.0,37308.555
1788,11/07/23,35876.4960,3.85,0.0,12.58,0.0,37180.062
1789,11/08/23,35814.9000,3.80,0.0,13.27,0.0,37053.336
1790,11/09/23,35755.0400,3.35,0.0,12.53,0.0,36928.535

In [121]:
import openmeteo_requests

import pandas as pd
import requests_cache
from retry_requests import retry

#Converts Date Column into Roberta format
def date_change(row):
    date = row['date']
    old_string=str(date).split(" ")[0].split("-")
    my_string=f"{old_string[1]}/{old_string[2]}/{old_string[0][-2:]}"
    return my_string

def csv_maker(system_id, start_date, end_date):
    #dates in "YYYY-MM-DD" format
    # Setup the Open-Meteo API client with cache and retry on error
    cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
    retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
    openmeteo = openmeteo_requests.Client(session = retry_session)

    # Make sure all required weather variables are listed here
    # The order of variables in hourly or daily is important to assign them correctly below
    url = "https://historical-forecast-api.open-meteo.com/v1/forecast"
    params = {
        "latitude": data[data['system_id']==system_id]['latitude'].item(),
        "longitude": data[data['system_id']==system_id]['longitude'].item(),
        "start_date": start_date,
        "end_date": end_date,
        "daily": ["sunshine_duration", "uv_index_max", "precipitation_sum", "shortwave_radiation_sum", "precipitation_hours", "daylight_duration"],
        "timezone": "auto",
    }
    responses = openmeteo.weather_api(url, params=params)

    # Process first location. Add a for-loop for multiple locations or weather models
    response = responses[0]
    print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
    print(f"Elevation: {response.Elevation()} m asl")
    print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")

    # Process daily data. The order of variables needs to be the same as requested.
    daily = response.Daily()
    daily_sunshine_duration = daily.Variables(0).ValuesAsNumpy()
    daily_uv_index_max = daily.Variables(1).ValuesAsNumpy()
    daily_precipitation_sum = daily.Variables(2).ValuesAsNumpy()
    daily_shortwave_radiation_sum = daily.Variables(3).ValuesAsNumpy()
    daily_precipitation_hours = daily.Variables(4).ValuesAsNumpy()
    daily_daylight_duration = daily.Variables(5).ValuesAsNumpy()

    daily_data = {"date": pd.date_range(
        start = pd.to_datetime(daily.Time(), unit = "s", utc = True),
        end =  pd.to_datetime(daily.TimeEnd(), unit = "s", utc = True),
        freq = pd.Timedelta(seconds = daily.Interval()),
        inclusive = "left"
    )}

    daily_data["sunshine_duration"] = daily_sunshine_duration
    daily_data["uv_index_max"] = daily_uv_index_max
    daily_data["precipitation_sum"] = daily_precipitation_sum
    daily_data["shortwave_radiation_sum"] = daily_shortwave_radiation_sum
    daily_data["precipitation_hours"] = daily_precipitation_hours
    daily_data["daylight_duration"] = daily_daylight_duration

    daily_dataframe = pd.DataFrame(data = daily_data)

    daily_dataframe['new_date']=daily_dataframe.apply(date_change, axis=1)
    daily_dataframe['date']=daily_dataframe['new_date']
    daily_dataframe.drop('new_date', axis=1, inplace=True)

    daily_dataframe.to_csv(f"C:\\Users\\Alex\\Desktop\\DataScience\\Solar\\spring-2026-solar-panel-degradation-team-2\\notebooks\\eda\\AM\\weather_CSVs\\{system_id}_weather.csv", index=False)

In [129]:
my_list = [[2105, "2018-12-15", "2023-11-09"], [2107, "2017-11-01", "2023-11-06"], [7333, "2016-11-01", "2023-10-31"], [9068, "2017-08-24", "2025-04-30"]]
for item in my_list:
    csv_maker(item[0], item[1], item[2])

Coordinates: 20.75°N -156.5°E
Elevation: 14.0 m asl
Timezone difference to GMT+0: -36000s
Coordinates: 38.99906921386719°N -122.13370513916016°E
Elevation: 110.0 m asl
Timezone difference to GMT+0: -25200s
Coordinates: 36.570064544677734°N -120.40391540527344°E
Elevation: 69.0 m asl
Timezone difference to GMT+0: -25200s
Coordinates: 40.39503860473633°N -104.5592041015625°E
Elevation: 1405.0 m asl
Timezone difference to GMT+0: -21600s

In [139]:
file="C:\\Users\\Alex\\Desktop\\DataScience\\Solar\\spring-2026-solar-panel-degradation-team-2\\notebooks\\eda\\AM\\weather_CSVs\\2105_weather.csv"

In [140]:
test=pd.read_csv(file)

In [141]:
test.describe()

,sunshine_duration,uv_index_max,precipitation_sum,shortwave_radiation_sum,precipitation_hours,daylight_duration
count,962.000000,963.000000,962.000000,962.000000,1791.000000,1791.000000
mean,40828.306538,7.702960,0.686902,20.962422,0.983250,43801.092486
std,6398.134004,1.289401,3.303474,4.707664,2.518701,3113.297893
min,0.000000,0.950000,0.000000,3.100000,0.000000,39135.137000
25%,38927.162750,6.875000,0.000000,17.752500,0.000000,40819.455500
50%,41645.317000,8.050000,0.000000,21.160000,0.000000,43886.184000
75%,45331.149500,8.750000,0.300000,24.377500,0.000000,46829.798000
max,46896.758000,9.250000,55.800003,29.880000,22.000000,48210.586000