In [3]:
import pandas as pd
import pyarrow.parquet as pq
from pathlib import Path

In [4]:
test_dir = Path('../../../data_ds_project/sorted_by_metric/4901_parquet_c/')
test_pq = pq.ParquetDataset(test_dir)
test_df = test_pq.read().to_pandas()

In [5]:
test_df

,measured_on,CR1000Temp_C_Avg,Pyra1_mV_Avg,Pyra2_mV_Avg,Pyra3_mV_Avg,RefCell1_Wm2_Avg,RefCell2_Wm2_Avg,AmbTemp_C_Avg,InvVDVoltage_V_Avg,InvVa_Avg,...,RTD_C_Avg_2,RTD_C_Avg_3,RTD_C_Avg_4,RTD_C_Avg_5,RTD_C_Avg_6,RTD_C_Avg_7,RTD_C_Avg_8,RTD_C_Avg_9,RTD_C_Avg_10,year
0,2014-07-29 07:59:00,20.410,3.436,3.358,3.901,415.800,415.800,16.680,354.60,273.8,...,28.810,24.070,26.910,25.250,27.210,26.470,27.590,25.020,29.870,2014
1,2014-07-29 08:00:00,20.460,3.466,3.386,3.931,418.400,419.100,16.560,354.60,274.0,...,28.860,23.930,26.730,25.040,27.040,26.280,27.430,24.970,29.900,2014
2,2014-07-29 08:01:00,20.520,3.498,3.415,3.964,421.300,422.700,16.610,355.20,273.9,...,29.020,24.070,26.880,25.220,27.240,26.410,27.590,25.130,29.920,2014
3,2014-07-29 08:02:00,20.580,3.531,3.447,3.999,424.400,426.700,16.780,354.90,273.8,...,29.230,24.230,26.920,25.220,27.300,26.500,27.780,25.400,29.930,2014
4,2014-07-29 08:03:00,20.630,3.570,3.485,4.040,428.200,431.700,16.940,354.40,273.8,...,29.100,24.240,26.870,25.040,27.240,26.420,27.730,25.610,30.000,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1904970,2018-03-14 23:55:00,1.931,-0.013,-0.013,-0.013,-0.340,-0.098,0.626,13.57,271.9,...,-1.629,-1.729,-1.121,-1.135,-1.367,-1.197,-1.345,-0.897,4.632,2018
1904971,2018-03-14 23:56:00,1.927,-0.013,-0.013,-0.013,-0.353,-0.099,0.608,13.52,271.9,...,-1.653,-1.729,-1.071,-1.153,-1.349,-1.165,-1.345,-0.914,4.615,2018
1904972,2018-03-14 23:57:00,1.911,-0.013,-0.013,-0.013,-0.353,-0.099,0.511,13.52,271.5,...,-1.699,-1.729,-1.124,-1.153,-1.367,-1.180,-1.345,-0.978,4.615,2018
1904973,2018-03-14 23:58:00,1.903,-0.013,-0.014,-0.013,-0.354,-0.100,0.507,13.52,271.8,...,-1.746,-1.778,-1.153,-1.202,-1.413,-1.230,-1.409,-1.057,4.615,2018
1904974,2018-03-14 23:59:00,1.884,-0.016,-0.017,-0.013,-0.349,-0.095,0.478,13.52,271.8,...,-1.859,-1.921,-1.266,-1.330,-1.527,-1.295,-1.537,-1.057,4.615,2018

In [13]:
test_df.columns

Index(['measured_on', 'CR1000Temp_C_Avg', 'Pyra1_mV_Avg', 'Pyra2_mV_Avg',
       'Pyra3_mV_Avg', 'RefCell1_Wm2_Avg', 'RefCell2_Wm2_Avg', 'AmbTemp_C_Avg',
       'InvVDVoltage_V_Avg', 'InvVa_Avg', 'InvVb_Avg', 'InvVc_Avg',
       'InvIa_Avg', 'InvIb_Avg', 'InvIc_Avg', 'InvVDCin_Avg', 'InvPAC_kW_Avg',
       'InvVPVin_Avg', 'InvPDC_kW_Avg', 'InvVoltageFault_Max',
       'InvTempFault_Max', 'SEWSAmbientTemp_C_Avg', 'SEWSModuleTemp_C_Avg',
       'SEWSPOAIrrad_Wm2_Avg', 'PwrMtrPhaseRev_Avg', 'PwrMtrVa_Avg',
       'PwrMtrVb_Avg', 'PwrMtrVc_Avg', 'PwrMtrP_kW_Avg', 'PwrMtrP_kVAR_Avg',
       'PwrMtrP_kVA_Avg', 'PwrMtrEdel_kWh_Max', 'PwrMtrErec_kWh_Max',
       'PwrMtrEdel_kVARh_Max', 'PwrMtrErec_kVARh_Max', 'PwrMtrPF_Avg',
       'PwrMtrVaTHDMax_Max', 'PwrMtrVbTHDMax_Max', 'PwrMtrVcTHDMax_Max',
       'ShuntCurrent_A_Avg_1', 'ShuntCurrent_A_Avg_2', 'ShuntCurrent_A_Avg_3',
       'ShuntCurrent_A_Avg_4', 'ShuntCurrent_A_Avg_5', 'ShuntCurrent_A_Avg_6',
       'ShuntCurrent_A_Avg_7', 'ShuntPDC_kW_Avg_1', 'ShuntPDC_kW_Avg_2',
       'ShuntPDC_kW_Avg_3', 'ShuntPDC_kW_Avg_4', 'ShuntPDC_kW_Avg_5',
       'ShuntPDC_kW_Avg_6', 'ShuntPDC_kW_Avg_7', 'Battery_V_Min',
       'Battery_A_Avg', 'RTD_C_Avg_1', 'RTD_C_Avg_2', 'RTD_C_Avg_3',
       'RTD_C_Avg_4', 'RTD_C_Avg_5', 'RTD_C_Avg_6', 'RTD_C_Avg_7',
       'RTD_C_Avg_8', 'RTD_C_Avg_9', 'RTD_C_Avg_10', 'year'],
      dtype='str', name='')

In [6]:
metrics_dir = Path("../../data/raw/parquet-metrics/")
metrics_pq = pq.ParquetDataset(metrics_dir)
metrics_df = metrics_pq.read().to_pandas()
metrics_id_set = set(metrics_df.system_id)

In [7]:
metrics_4901 = metrics_df[metrics_df.system_id == 4901]

In [8]:
def metrics_search_for_fragment_df(df: pd.DataFrame, fragment: str):
    '''Search for fragments of a name in sensor_name and common_name'''
    fragment = fragment.lower()
    return df[
        (df.loc[:, 'sensor_name'].str.contains(fragment, case=False))
        | (df.loc[:, 'common_name'].str.contains(fragment, case=False))
    ]


def metrics_search_for_two_fragments_df(df: pd.DataFrame, fragment_1: str,
                                        fragment_2: str, and_or: str):
    '''Search for fragments of two names in sensor_name and common name.
    Use and_or to switch between "both" and "at least one" modes'''
    fragment_1 = fragment_1.lower()
    fragment_2 = fragment_2.lower()
    if and_or == 'and':
        return df[
            ((df.loc[:, 'sensor_name'].str.contains(fragment_1, case=False))
                | (df.loc[:, 'common_name'].str.contains(fragment_1, case=False)))
            & ((df.loc[:, 'sensor_name'].str.contains(fragment_2, case=False))
                | (df.loc[:, 'common_name'].str.contains(fragment_2, case=False)))
        ]
    elif and_or == 'or':
        return df[
            ((df.loc[:, 'sensor_name'].str.contains(fragment_1, case=False))
                | (df.loc[:, 'common_name'].str.contains(fragment_1, case=False)))
            | ((df.loc[:, 'sensor_name'].str.contains(fragment_2, case=False))
                | (df.loc[:, 'common_name'].str.contains(fragment_2, case=False)))
        ]

In [14]:
metrics_4901_rtd = metrics_search_for_fragment_df(
    metrics_4901, 'RTD'
)

In [15]:
metrics_4901_rtd

,system_id,metric_id,sensor_name,common_name,raw_units,units,calc_scale,calc_offset,calc_details,aggregation_type,source_type,source_id,comments,standard_name
1432,4901,82581,RTD_C_Avg_1,Temperature backsheet,C,C,1.0,0.0,,avg,OTHER,NaN,module location varies by system,rtd_c_avg_1__82581
1433,4901,82590,RTD_C_Avg_10,Temperature backsheet,C,C,1.0,0.0,,avg,OTHER,NaN,module location varies by system,rtd_c_avg_10__82590
1434,4901,82582,RTD_C_Avg_2,Temperature backsheet,C,C,1.0,0.0,,avg,OTHER,NaN,module location varies by system,rtd_c_avg_2__82582
1435,4901,82583,RTD_C_Avg_3,Temperature backsheet,C,C,1.0,0.0,,avg,OTHER,NaN,module location varies by system,rtd_c_avg_3__82583
1436,4901,82584,RTD_C_Avg_4,Temperature backsheet,C,C,1.0,0.0,,avg,OTHER,NaN,module location varies by system,rtd_c_avg_4__82584
1437,4901,82585,RTD_C_Avg_5,Temperature backsheet,C,C,1.0,0.0,,avg,OTHER,NaN,module location varies by system,rtd_c_avg_5__82585
1438,4901,82586,RTD_C_Avg_6,Temperature backsheet,C,C,1.0,0.0,,avg,OTHER,NaN,module location varies by system,rtd_c_avg_6__82586
1439,4901,82587,RTD_C_Avg_7,Temperature backsheet,C,C,1.0,0.0,,avg,OTHER,NaN,module location varies by system,rtd_c_avg_7__82587
1440,4901,82588,RTD_C_Avg_8,Temperature backsheet,C,C,1.0,0.0,,avg,OTHER,NaN,module location varies by system,rtd_c_avg_8__82588
1441,4901,82589,RTD_C_Avg_9,Temperature backsheet,C,C,1.0,0.0,,avg,OTHER,NaN,module location varies by system,rtd_c_avg_9__82589