In [3]:
import numpy as np
import pandas as pd

In [5]:
data_10000_2012 = pd.read_csv(
    '../../../data_ds_project/systems/csv/10000/10000_ac_20120101_20121231.csv'
)

In [6]:
data_10000_2012.head()

,Unnamed: 0,ac_power_inv_16421_daily_max,ac_power_inv_16421_daily_mean,ac_energy_inv_16421_daily_sum
0,2012-01-01,0.098,0.040000,0.279
1,2012-01-02,0.782,0.363406,3.054
2,2012-01-03,0.623,0.206950,1.740
3,2012-01-04,1.853,0.515769,4.467
4,2012-01-05,1.161,0.418226,3.695

In [8]:
data_10000_2012.columns

Index(['Unnamed: 0', 'ac_power_inv_16421_daily_max',
       'ac_power_inv_16421_daily_mean', 'ac_energy_inv_16421_daily_sum'],
      dtype='str')

In [9]:
data_10000_2012 = data_10000_2012.rename(
    columns = {'Unnamed: 0': 'date'}
)

In [11]:
data_10000_2012.dtypes

date                                 str
ac_power_inv_16421_daily_max     float64
ac_power_inv_16421_daily_mean    float64
ac_energy_inv_16421_daily_sum    float64
dtype: object

In [12]:
data_10000_2012['date'] = pd.to_datetime(
        data_10000_2012['date'], format='%Y-%m-%d'
    ).astype('datetime64[s]')
data_10000_2012['date'] = data_10000_2012['date'].dt.date

In [13]:
data_10000_2012.dtypes

date                              object
ac_power_inv_16421_daily_max     float64
ac_power_inv_16421_daily_mean    float64
ac_energy_inv_16421_daily_sum    float64
dtype: object

In [14]:
data_10000_2012.head()

,date,ac_power_inv_16421_daily_max,ac_power_inv_16421_daily_mean,ac_energy_inv_16421_daily_sum
0,2012-01-01,0.098,0.040000,0.279
1,2012-01-02,0.782,0.363406,3.054
2,2012-01-03,0.623,0.206950,1.740
3,2012-01-04,1.853,0.515769,4.467
4,2012-01-05,1.161,0.418226,3.695

In [16]:
data_10000_2012['ratio'] = data_10000_2012['ac_energy_inv_16421_daily_sum'] / data_10000_2012['ac_power_inv_16421_daily_mean']
data_10000_2012['ratio'].describe()

count    364.000000
mean      11.657422
std        2.479917
min        4.498153
25%        9.336758
50%       11.914183
75%       13.835294
max       16.189708
Name: ratio, dtype: float64

OK, so variable ratio.  So not 24-hour mean, but active-mean, with high probability.